canal.port = 11111
canal.metrics.pull.port = 11112
canal.serverMode = kafka
canal.destinations = example
canal.auto.scan = true
canal.conf.dir = ../conf
canal.file.data.dir = /home/admin/canal-server/data
canal.instance.tsdb.enable = true
canal.instance.tsdb.spring.xml = classpath:spring/tsdb/h2-tsdb.xml
canal.instance.global.spring.xml = classpath:spring/file-instance.xml
canal.mq.flatMessage = true
kafka.bootstrap.servers = kafka:9092
