Name: gateway
Host: 0.0.0.0
Port: 8086

Jwt:
  AccessSecret: "change-me-gateway-access-secret"

UserRpc:
  Etcd:
    Hosts:
      - etcd:2379
    Key: user.rpc

ContentRpc:
  Etcd:
    Hosts:
      - etcd:2379
    Key: content.rpc

FeedRpc:
  Etcd:
    Hosts:
      - etcd:2379
    Key: feed.rpc

CommentRpc:
  Etcd:
    Hosts:
      - etcd:2379
    Key: comment.rpc

RelationRpc:
  Etcd:
    Hosts:
      - etcd:2379
    Key: relation.rpc

InteractionRpc:
  Etcd:
    Hosts:
      - etcd:2379
    Key: interaction.rpc

SearchRpc:
  Etcd:
    Hosts:
      - etcd:2379
    Key: search.rpc
