canal.instance.master.address=mysql:3306
canal.instance.dbUsername=root
canal.instance.dbPassword=123456
canal.instance.connectionCharset=UTF-8
canal.instance.gtidon=false
canal.instance.filter.regex=schill\\..*
canal.instance.filter.black.regex=mysql\\.slave_.*
canal.mq.topic=canal_topic
canal.mq.partitionsNum=1
canal.mq.partitionHash=false
