// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: relation.proto

package relationcenter

import (
	"context"

	"SChill/service/relation/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchCheckFollowStatusReq  = pb.BatchCheckFollowStatusReq
	BatchCheckFollowStatusResp = pb.BatchCheckFollowStatusResp
	CheckFollowStatusReq       = pb.CheckFollowStatusReq
	CheckFollowStatusResp      = pb.CheckFollowStatusResp
	FollowInfo                 = pb.FollowInfo
	FollowReq                  = pb.FollowReq
	FollowResp                 = pb.FollowResp
	FollowStatusItem           = pb.FollowStatusItem
	GetFollowerListReq         = pb.GetFollowerListReq
	GetFollowerListResp        = pb.GetFollowerListResp
	GetFollowingListReq        = pb.GetFollowingListReq
	GetFollowingListResp       = pb.GetFollowingListResp
	UnfollowReq                = pb.UnfollowReq
	UnfollowResp               = pb.UnfollowResp

	RelationCenter interface {
		Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error)
		Unfollow(ctx context.Context, in *UnfollowReq, opts ...grpc.CallOption) (*UnfollowResp, error)
		CheckFollowStatus(ctx context.Context, in *CheckFollowStatusReq, opts ...grpc.CallOption) (*CheckFollowStatusResp, error)
		GetFollowingList(ctx context.Context, in *GetFollowingListReq, opts ...grpc.CallOption) (*GetFollowingListResp, error)
		GetFollowerList(ctx context.Context, in *GetFollowerListReq, opts ...grpc.CallOption) (*GetFollowerListResp, error)
		BatchCheckFollowStatus(ctx context.Context, in *BatchCheckFollowStatusReq, opts ...grpc.CallOption) (*BatchCheckFollowStatusResp, error)
	}

	defaultRelationCenter struct {
		cli zrpc.Client
	}
)

func NewRelationCenter(cli zrpc.Client) RelationCenter {
	return &defaultRelationCenter{
		cli: cli,
	}
}

func (m *defaultRelationCenter) Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error) {
	client := pb.NewRelationCenterClient(m.cli.Conn())
	return client.Follow(ctx, in, opts...)
}

func (m *defaultRelationCenter) Unfollow(ctx context.Context, in *UnfollowReq, opts ...grpc.CallOption) (*UnfollowResp, error) {
	client := pb.NewRelationCenterClient(m.cli.Conn())
	return client.Unfollow(ctx, in, opts...)
}

func (m *defaultRelationCenter) CheckFollowStatus(ctx context.Context, in *CheckFollowStatusReq, opts ...grpc.CallOption) (*CheckFollowStatusResp, error) {
	client := pb.NewRelationCenterClient(m.cli.Conn())
	return client.CheckFollowStatus(ctx, in, opts...)
}

func (m *defaultRelationCenter) GetFollowingList(ctx context.Context, in *GetFollowingListReq, opts ...grpc.CallOption) (*GetFollowingListResp, error) {
	client := pb.NewRelationCenterClient(m.cli.Conn())
	return client.GetFollowingList(ctx, in, opts...)
}

func (m *defaultRelationCenter) GetFollowerList(ctx context.Context, in *GetFollowerListReq, opts ...grpc.CallOption) (*GetFollowerListResp, error) {
	client := pb.NewRelationCenterClient(m.cli.Conn())
	return client.GetFollowerList(ctx, in, opts...)
}

func (m *defaultRelationCenter) BatchCheckFollowStatus(ctx context.Context, in *BatchCheckFollowStatusReq, opts ...grpc.CallOption) (*BatchCheckFollowStatusResp, error) {
	client := pb.NewRelationCenterClient(m.cli.Conn())
	return client.BatchCheckFollowStatus(ctx, in, opts...)
}
