// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: interaction.proto

package interactioncenter

import (
	"context"

	"SChill/service/interaction/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchCheckPostCollectionReq  = pb.BatchCheckPostCollectionReq
	BatchCheckPostCollectionResp = pb.BatchCheckPostCollectionResp
	BatchCheckPostStarReq        = pb.BatchCheckPostStarReq
	BatchCheckPostStarResp       = pb.BatchCheckPostStarResp
	CheckPostCollectionReq       = pb.CheckPostCollectionReq
	CheckPostCollectionResp      = pb.CheckPostCollectionResp
	CheckPostStarReq             = pb.CheckPostStarReq
	CheckPostStarResp            = pb.CheckPostStarResp
	CollectPostReq               = pb.CollectPostReq
	CollectPostResp              = pb.CollectPostResp
	CollectionStatus             = pb.CollectionStatus
	SharePostReq                 = pb.SharePostReq
	SharePostResp                = pb.SharePostResp
	StarPostReq                  = pb.StarPostReq
	StarPostResp                 = pb.StarPostResp
	StarStatus                   = pb.StarStatus
	UncollectPostReq             = pb.UncollectPostReq
	UncollectPostResp            = pb.UncollectPostResp
	UnstarPostReq                = pb.UnstarPostReq
	UnstarPostResp               = pb.UnstarPostResp

	InteractionCenter interface {
		// 动态点赞
		StarPost(ctx context.Context, in *StarPostReq, opts ...grpc.CallOption) (*StarPostResp, error)
		// 动态取消点赞
		UnstarPost(ctx context.Context, in *UnstarPostReq, opts ...grpc.CallOption) (*UnstarPostResp, error)
		// 检查动态点赞状态
		CheckPostStar(ctx context.Context, in *CheckPostStarReq, opts ...grpc.CallOption) (*CheckPostStarResp, error)
		// 批量检查动态点赞状态
		BatchCheckPostStar(ctx context.Context, in *BatchCheckPostStarReq, opts ...grpc.CallOption) (*BatchCheckPostStarResp, error)
		// 动态收藏
		CollectPost(ctx context.Context, in *CollectPostReq, opts ...grpc.CallOption) (*CollectPostResp, error)
		// 动态取消收藏
		UncollectPost(ctx context.Context, in *UncollectPostReq, opts ...grpc.CallOption) (*UncollectPostResp, error)
		// 检查动态收藏状态
		CheckPostCollection(ctx context.Context, in *CheckPostCollectionReq, opts ...grpc.CallOption) (*CheckPostCollectionResp, error)
		// 批量检查动态收藏状态
		BatchCheckPostCollection(ctx context.Context, in *BatchCheckPostCollectionReq, opts ...grpc.CallOption) (*BatchCheckPostCollectionResp, error)
		// 动态分享
		SharePost(ctx context.Context, in *SharePostReq, opts ...grpc.CallOption) (*SharePostResp, error)
	}

	defaultInteractionCenter struct {
		cli zrpc.Client
	}
)

func NewInteractionCenter(cli zrpc.Client) InteractionCenter {
	return &defaultInteractionCenter{
		cli: cli,
	}
}

// 动态点赞
func (m *defaultInteractionCenter) StarPost(ctx context.Context, in *StarPostReq, opts ...grpc.CallOption) (*StarPostResp, error) {
	client := pb.NewInteractionCenterClient(m.cli.Conn())
	return client.StarPost(ctx, in, opts...)
}

// 动态取消点赞
func (m *defaultInteractionCenter) UnstarPost(ctx context.Context, in *UnstarPostReq, opts ...grpc.CallOption) (*UnstarPostResp, error) {
	client := pb.NewInteractionCenterClient(m.cli.Conn())
	return client.UnstarPost(ctx, in, opts...)
}

// 检查动态点赞状态
func (m *defaultInteractionCenter) CheckPostStar(ctx context.Context, in *CheckPostStarReq, opts ...grpc.CallOption) (*CheckPostStarResp, error) {
	client := pb.NewInteractionCenterClient(m.cli.Conn())
	return client.CheckPostStar(ctx, in, opts...)
}

// 批量检查动态点赞状态
func (m *defaultInteractionCenter) BatchCheckPostStar(ctx context.Context, in *BatchCheckPostStarReq, opts ...grpc.CallOption) (*BatchCheckPostStarResp, error) {
	client := pb.NewInteractionCenterClient(m.cli.Conn())
	return client.BatchCheckPostStar(ctx, in, opts...)
}

// 动态收藏
func (m *defaultInteractionCenter) CollectPost(ctx context.Context, in *CollectPostReq, opts ...grpc.CallOption) (*CollectPostResp, error) {
	client := pb.NewInteractionCenterClient(m.cli.Conn())
	return client.CollectPost(ctx, in, opts...)
}

// 动态取消收藏
func (m *defaultInteractionCenter) UncollectPost(ctx context.Context, in *UncollectPostReq, opts ...grpc.CallOption) (*UncollectPostResp, error) {
	client := pb.NewInteractionCenterClient(m.cli.Conn())
	return client.UncollectPost(ctx, in, opts...)
}

// 检查动态收藏状态
func (m *defaultInteractionCenter) CheckPostCollection(ctx context.Context, in *CheckPostCollectionReq, opts ...grpc.CallOption) (*CheckPostCollectionResp, error) {
	client := pb.NewInteractionCenterClient(m.cli.Conn())
	return client.CheckPostCollection(ctx, in, opts...)
}

// 批量检查动态收藏状态
func (m *defaultInteractionCenter) BatchCheckPostCollection(ctx context.Context, in *BatchCheckPostCollectionReq, opts ...grpc.CallOption) (*BatchCheckPostCollectionResp, error) {
	client := pb.NewInteractionCenterClient(m.cli.Conn())
	return client.BatchCheckPostCollection(ctx, in, opts...)
}

// 动态分享
func (m *defaultInteractionCenter) SharePost(ctx context.Context, in *SharePostReq, opts ...grpc.CallOption) (*SharePostResp, error) {
	client := pb.NewInteractionCenterClient(m.cli.Conn())
	return client.SharePost(ctx, in, opts...)
}
