// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BatchCheckFollowStatusReq struct {
	TargetUserIds []uint64 `json:"targetUserIds" validate:"required,min=1,max=100"`
}

type BatchCheckFollowStatusResp struct {
	Code   int                `json:"code"`
	Msg    string             `json:"msg"`
	Status []FollowStatusItem `json:"status"`
}

type CheckFollowStatusReq struct {
	TargetUserId uint64 `form:"targetUserId" validate:"required"`
}

type FollowInfo struct {
	UserId     uint64 `json:"userId"`
	Username   string `json:"username"`
	Avatar     string `json:"avatar"`
	FollowTime int64  `json:"followTime"` // 关注时间（时间戳）
}

type FollowListResp struct {
	Code  int          `json:"code"`
	Msg   string       `json:"msg"`
	Total int64        `json:"total"`
	List  []FollowInfo `json:"list"`
}

type FollowReq struct {
	TargetUserId uint64 `json:"targetUserId" validate:"required"`
}

type FollowResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type FollowStatusItem struct {
	UserId   uint64 `json:"userId"`
	IsFollow bool   `json:"isFollow"`
}

type FollowStatusResp struct {
	Code     int    `json:"code"`
	Msg      string `json:"msg"`
	IsFollow bool   `json:"isFollow"`
}

type GetFollowerListReq struct {
	UserId uint64 `form:"userId,optional"`
	PageReq
}

type GetFollowingListReq struct {
	UserId uint64 `form:"userId,optional"`
	PageReq
}

type PageReq struct {
	Page     int64 `form:"page,default=1" validate:"min=1"`
	PageSize int64 `form:"pageSize,default=20" validate:"min=1,max=100"`
}

type UnfollowReq struct {
	TargetUserId uint64 `path:"targetUserId" validate:"required"`
}

type UnfollowResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
