// Code generated by goctl. Safe to edit.

package searchcenter

import (
	"context"

	"SChill/service/search/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SearchReq       = pb.SearchReq
	SearchPostItem  = pb.SearchPostItem
	SearchPostResp  = pb.SearchPostResp
	SearchUserItem  = pb.SearchUserItem
	SearchUserResp  = pb.SearchUserResp
	SearchTopicItem = pb.SearchTopicItem
	SearchTopicResp = pb.SearchTopicResp

	SearchCenter interface {
		SearchPost(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchPostResp, error)
		SearchUser(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchUserResp, error)
		SearchTopic(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchTopicResp, error)
	}

	defaultSearchCenter struct {
		cli zrpc.Client
	}
)

func NewSearchCenter(cli zrpc.Client) SearchCenter {
	return &defaultSearchCenter{
		cli: cli,
	}
}

func (m *defaultSearchCenter) SearchPost(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchPostResp, error) {
	client := pb.NewSearchCenterClient(m.cli.Conn())
	return client.SearchPost(ctx, in, opts...)
}

func (m *defaultSearchCenter) SearchUser(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchUserResp, error) {
	client := pb.NewSearchCenterClient(m.cli.Conn())
	return client.SearchUser(ctx, in, opts...)
}

func (m *defaultSearchCenter) SearchTopic(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchTopicResp, error) {
	client := pb.NewSearchCenterClient(m.cli.Conn())
	return client.SearchTopic(ctx, in, opts...)
}
