// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: interaction.proto

package server

import (
	"context"

	"SChill/service/interaction/rpc/internal/logic"
	"SChill/service/interaction/rpc/internal/svc"
	"SChill/service/interaction/rpc/pb"
)

type InteractionCenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedInteractionCenterServer
}

func NewInteractionCenterServer(svcCtx *svc.ServiceContext) *InteractionCenterServer {
	return &InteractionCenterServer{
		svcCtx: svcCtx,
	}
}

// 动态点赞
func (s *InteractionCenterServer) StarPost(ctx context.Context, in *pb.StarPostReq) (*pb.StarPostResp, error) {
	l := logic.NewStarPostLogic(ctx, s.svcCtx)
	return l.StarPost(in)
}

// 动态取消点赞
func (s *InteractionCenterServer) UnstarPost(ctx context.Context, in *pb.UnstarPostReq) (*pb.UnstarPostResp, error) {
	l := logic.NewUnstarPostLogic(ctx, s.svcCtx)
	return l.UnstarPost(in)
}

// 检查动态点赞状态
func (s *InteractionCenterServer) CheckPostStar(ctx context.Context, in *pb.CheckPostStarReq) (*pb.CheckPostStarResp, error) {
	l := logic.NewCheckPostStarLogic(ctx, s.svcCtx)
	return l.CheckPostStar(in)
}

// 批量检查动态点赞状态
func (s *InteractionCenterServer) BatchCheckPostStar(ctx context.Context, in *pb.BatchCheckPostStarReq) (*pb.BatchCheckPostStarResp, error) {
	l := logic.NewBatchCheckPostStarLogic(ctx, s.svcCtx)
	return l.BatchCheckPostStar(in)
}

// 动态收藏
func (s *InteractionCenterServer) CollectPost(ctx context.Context, in *pb.CollectPostReq) (*pb.CollectPostResp, error) {
	l := logic.NewCollectPostLogic(ctx, s.svcCtx)
	return l.CollectPost(in)
}

// 动态取消收藏
func (s *InteractionCenterServer) UncollectPost(ctx context.Context, in *pb.UncollectPostReq) (*pb.UncollectPostResp, error) {
	l := logic.NewUncollectPostLogic(ctx, s.svcCtx)
	return l.UncollectPost(in)
}

// 检查动态收藏状态
func (s *InteractionCenterServer) CheckPostCollection(ctx context.Context, in *pb.CheckPostCollectionReq) (*pb.CheckPostCollectionResp, error) {
	l := logic.NewCheckPostCollectionLogic(ctx, s.svcCtx)
	return l.CheckPostCollection(in)
}

// 批量检查动态收藏状态
func (s *InteractionCenterServer) BatchCheckPostCollection(ctx context.Context, in *pb.BatchCheckPostCollectionReq) (*pb.BatchCheckPostCollectionResp, error) {
	l := logic.NewBatchCheckPostCollectionLogic(ctx, s.svcCtx)
	return l.BatchCheckPostCollection(in)
}

// 动态分享
func (s *InteractionCenterServer) SharePost(ctx context.Context, in *pb.SharePostReq) (*pb.SharePostResp, error) {
	l := logic.NewSharePostLogic(ctx, s.svcCtx)
	return l.SharePost(in)
}

// 获取用户收藏列表
func (s *InteractionCenterServer) ListUserCollections(ctx context.Context, in *pb.ListUserCollectionsReq) (*pb.ListUserCollectionsResp, error) {
	l := logic.NewListUserCollectionsLogic(ctx, s.svcCtx)
	return l.ListUserCollections(in)
}
