// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: comment.proto

package commentcenter

import (
	"context"

	"SChill/service/comment/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommentInfo        = pb.CommentInfo
	CreateCommentReq   = pb.CreateCommentReq
	CreateCommentResp  = pb.CreateCommentResp
	DeleteCommentReq   = pb.DeleteCommentReq
	DeleteCommentResp  = pb.DeleteCommentResp
	GetCommentListReq  = pb.GetCommentListReq
	GetCommentListResp = pb.GetCommentListResp
	GetReplyListReq    = pb.GetReplyListReq
	GetReplyListResp   = pb.GetReplyListResp
	VoteCommentReq     = pb.VoteCommentReq
	VoteCommentResp    = pb.VoteCommentResp

	CommentCenter interface {
		CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CreateCommentResp, error)
		DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error)
		GetCommentList(ctx context.Context, in *GetCommentListReq, opts ...grpc.CallOption) (*GetCommentListResp, error)
		GetReplyList(ctx context.Context, in *GetReplyListReq, opts ...grpc.CallOption) (*GetReplyListResp, error)
		VoteComment(ctx context.Context, in *VoteCommentReq, opts ...grpc.CallOption) (*VoteCommentResp, error)
	}

	defaultCommentCenter struct {
		cli zrpc.Client
	}
)

func NewCommentCenter(cli zrpc.Client) CommentCenter {
	return &defaultCommentCenter{
		cli: cli,
	}
}

func (m *defaultCommentCenter) CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CreateCommentResp, error) {
	client := pb.NewCommentCenterClient(m.cli.Conn())
	return client.CreateComment(ctx, in, opts...)
}

func (m *defaultCommentCenter) DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error) {
	client := pb.NewCommentCenterClient(m.cli.Conn())
	return client.DeleteComment(ctx, in, opts...)
}

func (m *defaultCommentCenter) GetCommentList(ctx context.Context, in *GetCommentListReq, opts ...grpc.CallOption) (*GetCommentListResp, error) {
	client := pb.NewCommentCenterClient(m.cli.Conn())
	return client.GetCommentList(ctx, in, opts...)
}

func (m *defaultCommentCenter) GetReplyList(ctx context.Context, in *GetReplyListReq, opts ...grpc.CallOption) (*GetReplyListResp, error) {
	client := pb.NewCommentCenterClient(m.cli.Conn())
	return client.GetReplyList(ctx, in, opts...)
}

func (m *defaultCommentCenter) VoteComment(ctx context.Context, in *VoteCommentReq, opts ...grpc.CallOption) (*VoteCommentResp, error) {
	client := pb.NewCommentCenterClient(m.cli.Conn())
	return client.VoteComment(ctx, in, opts...)
}
