version: '3.8'

services:
  gateway:
    build:
      context: ..
      dockerfile: service/gateway/Dockerfile
    image: schill-gateway:latest
    container_name: gateway
    ports:
      - "8086:8086"
    volumes:
      - ./gateway.compose.yaml:/app/etc/gateway.yaml:ro
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge
