// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: content.proto

package server

import (
	"context"

	"SChill/service/content/rpc/internal/logic"
	"SChill/service/content/rpc/internal/svc"
	"SChill/service/content/rpc/pb"
)

type ContentCenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedContentCenterServer
}

func NewContentCenterServer(svcCtx *svc.ServiceContext) *ContentCenterServer {
	return &ContentCenterServer{
		svcCtx: svcCtx,
	}
}

func (s *ContentCenterServer) CreatePost(ctx context.Context, in *pb.CreatePostReq) (*pb.CreatePostResp, error) {
	l := logic.NewCreatePostLogic(ctx, s.svcCtx)
	return l.CreatePost(in)
}

func (s *ContentCenterServer) UpdatePost(ctx context.Context, in *pb.UpdatePostReq) (*pb.UpdatePostResp, error) {
	l := logic.NewUpdatePostLogic(ctx, s.svcCtx)
	return l.UpdatePost(in)
}

func (s *ContentCenterServer) DeletePost(ctx context.Context, in *pb.DeletePostReq) (*pb.DeletePostResp, error) {
	l := logic.NewDeletePostLogic(ctx, s.svcCtx)
	return l.DeletePost(in)
}

func (s *ContentCenterServer) GetPostDetail(ctx context.Context, in *pb.GetPostDetailReq) (*pb.GetPostDetailResp, error) {
	l := logic.NewGetPostDetailLogic(ctx, s.svcCtx)
	return l.GetPostDetail(in)
}

func (s *ContentCenterServer) GetPostList(ctx context.Context, in *pb.GetPostListReq) (*pb.GetPostListResp, error) {
	l := logic.NewGetPostListLogic(ctx, s.svcCtx)
	return l.GetPostList(in)
}

func (s *ContentCenterServer) BatchGetPost(ctx context.Context, in *pb.BatchGetPostReq) (*pb.BatchGetPostResp, error) {
	l := logic.NewBatchGetPostLogic(ctx, s.svcCtx)
	return l.BatchGetPost(in)
}

func (s *ContentCenterServer) IncViewCount(ctx context.Context, in *pb.IncViewCountReq) (*pb.IncViewCountResp, error) {
	l := logic.NewIncViewCountLogic(ctx, s.svcCtx)
	return l.IncViewCount(in)
}
