// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: content.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 动态内容项
type PostContentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Sort          int32                  `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostContentItem) Reset() {
	*x = PostContentItem{}
	mi := &file_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostContentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostContentItem) ProtoMessage() {}

func (x *PostContentItem) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostContentItem.ProtoReflect.Descriptor instead.
func (*PostContentItem) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{0}
}

func (x *PostContentItem) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PostContentItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostContentItem) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

// 帖子基本信息
type PostInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          uint64                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Cover           string                 `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	CommentCount    uint64                 `protobuf:"varint,5,opt,name=commentCount,proto3" json:"commentCount,omitempty"`
	CollectionCount uint64                 `protobuf:"varint,6,opt,name=collectionCount,proto3" json:"collectionCount,omitempty"`
	UpvoteCount     uint64                 `protobuf:"varint,7,opt,name=upvoteCount,proto3" json:"upvoteCount,omitempty"`
	ShareCount      uint64                 `protobuf:"varint,8,opt,name=shareCount,proto3" json:"shareCount,omitempty"`
	Visibility      int32                  `protobuf:"varint,9,opt,name=visibility,proto3" json:"visibility,omitempty"`
	IsTop           int32                  `protobuf:"varint,10,opt,name=isTop,proto3" json:"isTop,omitempty"`
	IsEssence       int32                  `protobuf:"varint,11,opt,name=isEssence,proto3" json:"isEssence,omitempty"`
	IsLock          int32                  `protobuf:"varint,12,opt,name=isLock,proto3" json:"isLock,omitempty"`
	LatestRepliedAt int64                  `protobuf:"varint,13,opt,name=latestRepliedAt,proto3" json:"latestRepliedAt,omitempty"`
	Tags            string                 `protobuf:"bytes,14,opt,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,15,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,16,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PostInfo) Reset() {
	*x = PostInfo{}
	mi := &file_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfo) ProtoMessage() {}

func (x *PostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfo.ProtoReflect.Descriptor instead.
func (*PostInfo) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{1}
}

func (x *PostInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostInfo) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *PostInfo) GetCommentCount() uint64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *PostInfo) GetCollectionCount() uint64 {
	if x != nil {
		return x.CollectionCount
	}
	return 0
}

func (x *PostInfo) GetUpvoteCount() uint64 {
	if x != nil {
		return x.UpvoteCount
	}
	return 0
}

func (x *PostInfo) GetShareCount() uint64 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

func (x *PostInfo) GetVisibility() int32 {
	if x != nil {
		return x.Visibility
	}
	return 0
}

func (x *PostInfo) GetIsTop() int32 {
	if x != nil {
		return x.IsTop
	}
	return 0
}

func (x *PostInfo) GetIsEssence() int32 {
	if x != nil {
		return x.IsEssence
	}
	return 0
}

func (x *PostInfo) GetIsLock() int32 {
	if x != nil {
		return x.IsLock
	}
	return 0
}

func (x *PostInfo) GetLatestRepliedAt() int64 {
	if x != nil {
		return x.LatestRepliedAt
	}
	return 0
}

func (x *PostInfo) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *PostInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PostInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 帖子话题信息
type PostTopic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	TopicId       uint64                 `protobuf:"varint,2,opt,name=topicId,proto3" json:"topicId,omitempty"`
	TopicName     string                 `protobuf:"bytes,3,opt,name=topicName,proto3" json:"topicName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTopic) Reset() {
	*x = PostTopic{}
	mi := &file_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTopic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTopic) ProtoMessage() {}

func (x *PostTopic) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTopic.ProtoReflect.Descriptor instead.
func (*PostTopic) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{2}
}

func (x *PostTopic) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostTopic) GetTopicId() uint64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *PostTopic) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

// 话题信息
type TopicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	QuoteNum      int64                  `protobuf:"varint,3,opt,name=quoteNum,proto3" json:"quoteNum,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicInfo) Reset() {
	*x = TopicInfo{}
	mi := &file_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicInfo) ProtoMessage() {}

func (x *TopicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicInfo.ProtoReflect.Descriptor instead.
func (*TopicInfo) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{3}
}

func (x *TopicInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TopicInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopicInfo) GetQuoteNum() int64 {
	if x != nil {
		return x.QuoteNum
	}
	return 0
}

func (x *TopicInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TopicInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 创建帖子请求
type CreatePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Cover         string                 `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	Visibility    int32                  `protobuf:"varint,4,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Contents      []*PostContentItem     `protobuf:"bytes,5,rep,name=contents,proto3" json:"contents,omitempty"`
	Topics        []string               `protobuf:"bytes,6,rep,name=topics,proto3" json:"topics,omitempty"`
	Tags          string                 `protobuf:"bytes,7,opt,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostReq) Reset() {
	*x = CreatePostReq{}
	mi := &file_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostReq) ProtoMessage() {}

func (x *CreatePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostReq.ProtoReflect.Descriptor instead.
func (*CreatePostReq) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePostReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePostReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostReq) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *CreatePostReq) GetVisibility() int32 {
	if x != nil {
		return x.Visibility
	}
	return 0
}

func (x *CreatePostReq) GetContents() []*PostContentItem {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *CreatePostReq) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *CreatePostReq) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

// 创建帖子响应
type CreatePostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResp) Reset() {
	*x = CreatePostResp{}
	mi := &file_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResp) ProtoMessage() {}

func (x *CreatePostResp) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResp.ProtoReflect.Descriptor instead.
func (*CreatePostResp) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePostResp) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

// 更新帖子请求
type UpdatePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Cover         string                 `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Visibility    int32                  `protobuf:"varint,5,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Contents      []*PostContentItem     `protobuf:"bytes,6,rep,name=contents,proto3" json:"contents,omitempty"`
	Topics        []string               `protobuf:"bytes,7,rep,name=topics,proto3" json:"topics,omitempty"`
	Tags          string                 `protobuf:"bytes,8,opt,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostReq) Reset() {
	*x = UpdatePostReq{}
	mi := &file_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostReq) ProtoMessage() {}

func (x *UpdatePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostReq.ProtoReflect.Descriptor instead.
func (*UpdatePostReq) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePostReq) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *UpdatePostReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdatePostReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePostReq) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *UpdatePostReq) GetVisibility() int32 {
	if x != nil {
		return x.Visibility
	}
	return 0
}

func (x *UpdatePostReq) GetContents() []*PostContentItem {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *UpdatePostReq) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *UpdatePostReq) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

// 更新帖子响应
type UpdatePostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostResp) Reset() {
	*x = UpdatePostResp{}
	mi := &file_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostResp) ProtoMessage() {}

func (x *UpdatePostResp) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostResp.ProtoReflect.Descriptor instead.
func (*UpdatePostResp) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePostResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 删除帖子请求
type DeletePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostReq) Reset() {
	*x = DeletePostReq{}
	mi := &file_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostReq) ProtoMessage() {}

func (x *DeletePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostReq.ProtoReflect.Descriptor instead.
func (*DeletePostReq) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePostReq) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *DeletePostReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 删除帖子响应
type DeletePostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostResp) Reset() {
	*x = DeletePostResp{}
	mi := &file_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostResp) ProtoMessage() {}

func (x *DeletePostResp) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostResp.ProtoReflect.Descriptor instead.
func (*DeletePostResp) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePostResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 获取帖子详情请求
type GetPostDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	CurrentUserId uint64                 `protobuf:"varint,2,opt,name=currentUserId,proto3" json:"currentUserId,omitempty"` // 当前用户ID，用于权限检查
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostDetailReq) Reset() {
	*x = GetPostDetailReq{}
	mi := &file_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostDetailReq) ProtoMessage() {}

func (x *GetPostDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostDetailReq.ProtoReflect.Descriptor instead.
func (*GetPostDetailReq) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{10}
}

func (x *GetPostDetailReq) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *GetPostDetailReq) GetCurrentUserId() uint64 {
	if x != nil {
		return x.CurrentUserId
	}
	return 0
}

// 获取帖子详情响应
type GetPostDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *PostInfo              `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	Contents      []*PostContentItem     `protobuf:"bytes,2,rep,name=contents,proto3" json:"contents,omitempty"`
	Topics        []*PostTopic           `protobuf:"bytes,3,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostDetailResp) Reset() {
	*x = GetPostDetailResp{}
	mi := &file_content_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostDetailResp) ProtoMessage() {}

func (x *GetPostDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostDetailResp.ProtoReflect.Descriptor instead.
func (*GetPostDetailResp) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{11}
}

func (x *GetPostDetailResp) GetPost() *PostInfo {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *GetPostDetailResp) GetContents() []*PostContentItem {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *GetPostDetailResp) GetTopics() []*PostTopic {
	if x != nil {
		return x.Topics
	}
	return nil
}

// 获取帖子列表请求
type GetPostListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	CurrentUserId uint64                 `protobuf:"varint,4,opt,name=currentUserId,proto3" json:"currentUserId,omitempty"` // 当前用户ID，用于权限检查
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostListReq) Reset() {
	*x = GetPostListReq{}
	mi := &file_content_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostListReq) ProtoMessage() {}

func (x *GetPostListReq) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostListReq.ProtoReflect.Descriptor instead.
func (*GetPostListReq) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{12}
}

func (x *GetPostListReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPostListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPostListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetPostListReq) GetCurrentUserId() uint64 {
	if x != nil {
		return x.CurrentUserId
	}
	return 0
}

// 获取帖子列表响应
type GetPostListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*PostInfo            `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostListResp) Reset() {
	*x = GetPostListResp{}
	mi := &file_content_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostListResp) ProtoMessage() {}

func (x *GetPostListResp) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostListResp.ProtoReflect.Descriptor instead.
func (*GetPostListResp) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{13}
}

func (x *GetPostListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetPostListResp) GetList() []*PostInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// 批量获取帖子请求
type BatchGetPostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostIds       []uint64               `protobuf:"varint,1,rep,packed,name=postIds,proto3" json:"postIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetPostReq) Reset() {
	*x = BatchGetPostReq{}
	mi := &file_content_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetPostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetPostReq) ProtoMessage() {}

func (x *BatchGetPostReq) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetPostReq.ProtoReflect.Descriptor instead.
func (*BatchGetPostReq) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{14}
}

func (x *BatchGetPostReq) GetPostIds() []uint64 {
	if x != nil {
		return x.PostIds
	}
	return nil
}

// 批量获取帖子响应
type BatchGetPostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostInfo            `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetPostResp) Reset() {
	*x = BatchGetPostResp{}
	mi := &file_content_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetPostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetPostResp) ProtoMessage() {}

func (x *BatchGetPostResp) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetPostResp.ProtoReflect.Descriptor instead.
func (*BatchGetPostResp) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{15}
}

func (x *BatchGetPostResp) GetPosts() []*PostInfo {
	if x != nil {
		return x.Posts
	}
	return nil
}

type PostSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Cover         string                 `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	TopicNames    []string               `protobuf:"bytes,6,rep,name=topicNames,proto3" json:"topicNames,omitempty"`
	Visibility    int32                  `protobuf:"varint,7,opt,name=visibility,proto3" json:"visibility,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostSummary) Reset() {
	*x = PostSummary{}
	mi := &file_content_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostSummary) ProtoMessage() {}

func (x *PostSummary) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostSummary.ProtoReflect.Descriptor instead.
func (*PostSummary) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{16}
}

func (x *PostSummary) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostSummary) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostSummary) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *PostSummary) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PostSummary) GetTopicNames() []string {
	if x != nil {
		return x.TopicNames
	}
	return nil
}

func (x *PostSummary) GetVisibility() int32 {
	if x != nil {
		return x.Visibility
	}
	return 0
}

func (x *PostSummary) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PostSummary) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type BatchGetPostSummaryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostIds       []uint64               `protobuf:"varint,1,rep,packed,name=postIds,proto3" json:"postIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetPostSummaryReq) Reset() {
	*x = BatchGetPostSummaryReq{}
	mi := &file_content_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetPostSummaryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetPostSummaryReq) ProtoMessage() {}

func (x *BatchGetPostSummaryReq) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetPostSummaryReq.ProtoReflect.Descriptor instead.
func (*BatchGetPostSummaryReq) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{17}
}

func (x *BatchGetPostSummaryReq) GetPostIds() []uint64 {
	if x != nil {
		return x.PostIds
	}
	return nil
}

type BatchGetPostSummaryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostSummary         `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetPostSummaryResp) Reset() {
	*x = BatchGetPostSummaryResp{}
	mi := &file_content_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetPostSummaryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetPostSummaryResp) ProtoMessage() {}

func (x *BatchGetPostSummaryResp) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetPostSummaryResp.ProtoReflect.Descriptor instead.
func (*BatchGetPostSummaryResp) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{18}
}

func (x *BatchGetPostSummaryResp) GetPosts() []*PostSummary {
	if x != nil {
		return x.Posts
	}
	return nil
}

// 增加浏览量请求
type IncViewCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncViewCountReq) Reset() {
	*x = IncViewCountReq{}
	mi := &file_content_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncViewCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncViewCountReq) ProtoMessage() {}

func (x *IncViewCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncViewCountReq.ProtoReflect.Descriptor instead.
func (*IncViewCountReq) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{19}
}

func (x *IncViewCountReq) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

// 增加浏览量响应
type IncViewCountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncViewCountResp) Reset() {
	*x = IncViewCountResp{}
	mi := &file_content_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncViewCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncViewCountResp) ProtoMessage() {}

func (x *IncViewCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncViewCountResp.ProtoReflect.Descriptor instead.
func (*IncViewCountResp) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{20}
}

func (x *IncViewCountResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 获取话题列表请求
type GetTopicListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"` // "hot" or "new"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicListReq) Reset() {
	*x = GetTopicListReq{}
	mi := &file_content_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicListReq) ProtoMessage() {}

func (x *GetTopicListReq) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicListReq.ProtoReflect.Descriptor instead.
func (*GetTopicListReq) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{21}
}

func (x *GetTopicListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTopicListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetTopicListReq) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

// 获取话题列表响应
type GetTopicListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*TopicInfo           `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicListResp) Reset() {
	*x = GetTopicListResp{}
	mi := &file_content_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicListResp) ProtoMessage() {}

func (x *GetTopicListResp) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicListResp.ProtoReflect.Descriptor instead.
func (*GetTopicListResp) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{22}
}

func (x *GetTopicListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetTopicListResp) GetList() []*TopicInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// 置顶帖子请求
type SetTopPostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	IsTop         int32                  `protobuf:"varint,3,opt,name=isTop,proto3" json:"isTop,omitempty"` // 0 or 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTopPostReq) Reset() {
	*x = SetTopPostReq{}
	mi := &file_content_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTopPostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTopPostReq) ProtoMessage() {}

func (x *SetTopPostReq) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTopPostReq.ProtoReflect.Descriptor instead.
func (*SetTopPostReq) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{23}
}

func (x *SetTopPostReq) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *SetTopPostReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetTopPostReq) GetIsTop() int32 {
	if x != nil {
		return x.IsTop
	}
	return 0
}

// 置顶帖子响应
type SetTopPostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTopPostResp) Reset() {
	*x = SetTopPostResp{}
	mi := &file_content_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTopPostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTopPostResp) ProtoMessage() {}

func (x *SetTopPostResp) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTopPostResp.ProtoReflect.Descriptor instead.
func (*SetTopPostResp) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{24}
}

func (x *SetTopPostResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 加精帖子请求
type SetEssencePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	IsEssence     int32                  `protobuf:"varint,3,opt,name=isEssence,proto3" json:"isEssence,omitempty"` // 0 or 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEssencePostReq) Reset() {
	*x = SetEssencePostReq{}
	mi := &file_content_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEssencePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEssencePostReq) ProtoMessage() {}

func (x *SetEssencePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEssencePostReq.ProtoReflect.Descriptor instead.
func (*SetEssencePostReq) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{25}
}

func (x *SetEssencePostReq) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *SetEssencePostReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetEssencePostReq) GetIsEssence() int32 {
	if x != nil {
		return x.IsEssence
	}
	return 0
}

// 加精帖子响应
type SetEssencePostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEssencePostResp) Reset() {
	*x = SetEssencePostResp{}
	mi := &file_content_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEssencePostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEssencePostResp) ProtoMessage() {}

func (x *SetEssencePostResp) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEssencePostResp.ProtoReflect.Descriptor instead.
func (*SetEssencePostResp) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{26}
}

func (x *SetEssencePostResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_content_proto protoreflect.FileDescriptor

const file_content_proto_rawDesc = "" +
	"\n" +
	"\rcontent.proto\x12\acontent\"S\n" +
	"\x0fPostContentItem\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\x05R\x04sort\"\xd4\x03\n" +
	"\bPostInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05cover\x18\x04 \x01(\tR\x05cover\x12\"\n" +
	"\fcommentCount\x18\x05 \x01(\x04R\fcommentCount\x12(\n" +
	"\x0fcollectionCount\x18\x06 \x01(\x04R\x0fcollectionCount\x12 \n" +
	"\vupvoteCount\x18\a \x01(\x04R\vupvoteCount\x12\x1e\n" +
	"\n" +
	"shareCount\x18\b \x01(\x04R\n" +
	"shareCount\x12\x1e\n" +
	"\n" +
	"visibility\x18\t \x01(\x05R\n" +
	"visibility\x12\x14\n" +
	"\x05isTop\x18\n" +
	" \x01(\x05R\x05isTop\x12\x1c\n" +
	"\tisEssence\x18\v \x01(\x05R\tisEssence\x12\x16\n" +
	"\x06isLock\x18\f \x01(\x05R\x06isLock\x12(\n" +
	"\x0flatestRepliedAt\x18\r \x01(\x03R\x0flatestRepliedAt\x12\x12\n" +
	"\x04tags\x18\x0e \x01(\tR\x04tags\x12\x1c\n" +
	"\tcreatedAt\x18\x0f \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x10 \x01(\x03R\tupdatedAt\"[\n" +
	"\tPostTopic\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x04R\x06postId\x12\x18\n" +
	"\atopicId\x18\x02 \x01(\x04R\atopicId\x12\x1c\n" +
	"\ttopicName\x18\x03 \x01(\tR\ttopicName\"\x87\x01\n" +
	"\tTopicInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bquoteNum\x18\x03 \x01(\x03R\bquoteNum\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x05 \x01(\x03R\tupdatedAt\"\xd5\x01\n" +
	"\rCreatePostReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05cover\x18\x03 \x01(\tR\x05cover\x12\x1e\n" +
	"\n" +
	"visibility\x18\x04 \x01(\x05R\n" +
	"visibility\x124\n" +
	"\bcontents\x18\x05 \x03(\v2\x18.content.PostContentItemR\bcontents\x12\x16\n" +
	"\x06topics\x18\x06 \x03(\tR\x06topics\x12\x12\n" +
	"\x04tags\x18\a \x01(\tR\x04tags\"(\n" +
	"\x0eCreatePostResp\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x04R\x06postId\"\xed\x01\n" +
	"\rUpdatePostReq\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x04R\x06postId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05cover\x18\x04 \x01(\tR\x05cover\x12\x1e\n" +
	"\n" +
	"visibility\x18\x05 \x01(\x05R\n" +
	"visibility\x124\n" +
	"\bcontents\x18\x06 \x03(\v2\x18.content.PostContentItemR\bcontents\x12\x16\n" +
	"\x06topics\x18\a \x03(\tR\x06topics\x12\x12\n" +
	"\x04tags\x18\b \x01(\tR\x04tags\"*\n" +
	"\x0eUpdatePostResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"?\n" +
	"\rDeletePostReq\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x04R\x06postId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x04R\x06userId\"*\n" +
	"\x0eDeletePostResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"P\n" +
	"\x10GetPostDetailReq\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x04R\x06postId\x12$\n" +
	"\rcurrentUserId\x18\x02 \x01(\x04R\rcurrentUserId\"\x9c\x01\n" +
	"\x11GetPostDetailResp\x12%\n" +
	"\x04post\x18\x01 \x01(\v2\x11.content.PostInfoR\x04post\x124\n" +
	"\bcontents\x18\x02 \x03(\v2\x18.content.PostContentItemR\bcontents\x12*\n" +
	"\x06topics\x18\x03 \x03(\v2\x12.content.PostTopicR\x06topics\"~\n" +
	"\x0eGetPostListReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\x12$\n" +
	"\rcurrentUserId\x18\x04 \x01(\x04R\rcurrentUserId\"N\n" +
	"\x0fGetPostListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12%\n" +
	"\x04list\x18\x02 \x03(\v2\x11.content.PostInfoR\x04list\"+\n" +
	"\x0fBatchGetPostReq\x12\x18\n" +
	"\apostIds\x18\x01 \x03(\x04R\apostIds\";\n" +
	"\x10BatchGetPostResp\x12'\n" +
	"\x05posts\x18\x01 \x03(\v2\x11.content.PostInfoR\x05posts\"\xf7\x01\n" +
	"\vPostSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05cover\x18\x04 \x01(\tR\x05cover\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x1e\n" +
	"\n" +
	"topicNames\x18\x06 \x03(\tR\n" +
	"topicNames\x12\x1e\n" +
	"\n" +
	"visibility\x18\a \x01(\x05R\n" +
	"visibility\x12\x1c\n" +
	"\tcreatedAt\x18\b \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\t \x01(\x03R\tupdatedAt\"2\n" +
	"\x16BatchGetPostSummaryReq\x12\x18\n" +
	"\apostIds\x18\x01 \x03(\x04R\apostIds\"E\n" +
	"\x17BatchGetPostSummaryResp\x12*\n" +
	"\x05posts\x18\x01 \x03(\v2\x14.content.PostSummaryR\x05posts\")\n" +
	"\x0fIncViewCountReq\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x04R\x06postId\",\n" +
	"\x10IncViewCountResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"U\n" +
	"\x0fGetTopicListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\"P\n" +
	"\x10GetTopicListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12&\n" +
	"\x04list\x18\x02 \x03(\v2\x12.content.TopicInfoR\x04list\"U\n" +
	"\rSetTopPostReq\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x04R\x06postId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05isTop\x18\x03 \x01(\x05R\x05isTop\"*\n" +
	"\x0eSetTopPostResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"a\n" +
	"\x11SetEssencePostReq\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x04R\x06postId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x04R\x06userId\x12\x1c\n" +
	"\tisEssence\x18\x03 \x01(\x05R\tisEssence\".\n" +
	"\x12SetEssencePostResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x89\x06\n" +
	"\rContentCenter\x12=\n" +
	"\n" +
	"CreatePost\x12\x16.content.CreatePostReq\x1a\x17.content.CreatePostResp\x12=\n" +
	"\n" +
	"UpdatePost\x12\x16.content.UpdatePostReq\x1a\x17.content.UpdatePostResp\x12=\n" +
	"\n" +
	"DeletePost\x12\x16.content.DeletePostReq\x1a\x17.content.DeletePostResp\x12F\n" +
	"\rGetPostDetail\x12\x19.content.GetPostDetailReq\x1a\x1a.content.GetPostDetailResp\x12@\n" +
	"\vGetPostList\x12\x17.content.GetPostListReq\x1a\x18.content.GetPostListResp\x12C\n" +
	"\fBatchGetPost\x12\x18.content.BatchGetPostReq\x1a\x19.content.BatchGetPostResp\x12X\n" +
	"\x13BatchGetPostSummary\x12\x1f.content.BatchGetPostSummaryReq\x1a .content.BatchGetPostSummaryResp\x12C\n" +
	"\fIncViewCount\x12\x18.content.IncViewCountReq\x1a\x19.content.IncViewCountResp\x12C\n" +
	"\fGetTopicList\x12\x18.content.GetTopicListReq\x1a\x19.content.GetTopicListResp\x12=\n" +
	"\n" +
	"SetTopPost\x12\x16.content.SetTopPostReq\x1a\x17.content.SetTopPostResp\x12I\n" +
	"\x0eSetEssencePost\x12\x1a.content.SetEssencePostReq\x1a\x1b.content.SetEssencePostRespB\x05Z\x03/pbb\x06proto3"

var (
	file_content_proto_rawDescOnce sync.Once
	file_content_proto_rawDescData []byte
)

func file_content_proto_rawDescGZIP() []byte {
	file_content_proto_rawDescOnce.Do(func() {
		file_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_content_proto_rawDesc), len(file_content_proto_rawDesc)))
	})
	return file_content_proto_rawDescData
}

var file_content_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_content_proto_goTypes = []any{
	(*PostContentItem)(nil),         // 0: content.PostContentItem
	(*PostInfo)(nil),                // 1: content.PostInfo
	(*PostTopic)(nil),               // 2: content.PostTopic
	(*TopicInfo)(nil),               // 3: content.TopicInfo
	(*CreatePostReq)(nil),           // 4: content.CreatePostReq
	(*CreatePostResp)(nil),          // 5: content.CreatePostResp
	(*UpdatePostReq)(nil),           // 6: content.UpdatePostReq
	(*UpdatePostResp)(nil),          // 7: content.UpdatePostResp
	(*DeletePostReq)(nil),           // 8: content.DeletePostReq
	(*DeletePostResp)(nil),          // 9: content.DeletePostResp
	(*GetPostDetailReq)(nil),        // 10: content.GetPostDetailReq
	(*GetPostDetailResp)(nil),       // 11: content.GetPostDetailResp
	(*GetPostListReq)(nil),          // 12: content.GetPostListReq
	(*GetPostListResp)(nil),         // 13: content.GetPostListResp
	(*BatchGetPostReq)(nil),         // 14: content.BatchGetPostReq
	(*BatchGetPostResp)(nil),        // 15: content.BatchGetPostResp
	(*PostSummary)(nil),             // 16: content.PostSummary
	(*BatchGetPostSummaryReq)(nil),  // 17: content.BatchGetPostSummaryReq
	(*BatchGetPostSummaryResp)(nil), // 18: content.BatchGetPostSummaryResp
	(*IncViewCountReq)(nil),         // 19: content.IncViewCountReq
	(*IncViewCountResp)(nil),        // 20: content.IncViewCountResp
	(*GetTopicListReq)(nil),         // 21: content.GetTopicListReq
	(*GetTopicListResp)(nil),        // 22: content.GetTopicListResp
	(*SetTopPostReq)(nil),           // 23: content.SetTopPostReq
	(*SetTopPostResp)(nil),          // 24: content.SetTopPostResp
	(*SetEssencePostReq)(nil),       // 25: content.SetEssencePostReq
	(*SetEssencePostResp)(nil),      // 26: content.SetEssencePostResp
}
var file_content_proto_depIdxs = []int32{
	0,  // 0: content.CreatePostReq.contents:type_name -> content.PostContentItem
	0,  // 1: content.UpdatePostReq.contents:type_name -> content.PostContentItem
	1,  // 2: content.GetPostDetailResp.post:type_name -> content.PostInfo
	0,  // 3: content.GetPostDetailResp.contents:type_name -> content.PostContentItem
	2,  // 4: content.GetPostDetailResp.topics:type_name -> content.PostTopic
	1,  // 5: content.GetPostListResp.list:type_name -> content.PostInfo
	1,  // 6: content.BatchGetPostResp.posts:type_name -> content.PostInfo
	16, // 7: content.BatchGetPostSummaryResp.posts:type_name -> content.PostSummary
	3,  // 8: content.GetTopicListResp.list:type_name -> content.TopicInfo
	4,  // 9: content.ContentCenter.CreatePost:input_type -> content.CreatePostReq
	6,  // 10: content.ContentCenter.UpdatePost:input_type -> content.UpdatePostReq
	8,  // 11: content.ContentCenter.DeletePost:input_type -> content.DeletePostReq
	10, // 12: content.ContentCenter.GetPostDetail:input_type -> content.GetPostDetailReq
	12, // 13: content.ContentCenter.GetPostList:input_type -> content.GetPostListReq
	14, // 14: content.ContentCenter.BatchGetPost:input_type -> content.BatchGetPostReq
	17, // 15: content.ContentCenter.BatchGetPostSummary:input_type -> content.BatchGetPostSummaryReq
	19, // 16: content.ContentCenter.IncViewCount:input_type -> content.IncViewCountReq
	21, // 17: content.ContentCenter.GetTopicList:input_type -> content.GetTopicListReq
	23, // 18: content.ContentCenter.SetTopPost:input_type -> content.SetTopPostReq
	25, // 19: content.ContentCenter.SetEssencePost:input_type -> content.SetEssencePostReq
	5,  // 20: content.ContentCenter.CreatePost:output_type -> content.CreatePostResp
	7,  // 21: content.ContentCenter.UpdatePost:output_type -> content.UpdatePostResp
	9,  // 22: content.ContentCenter.DeletePost:output_type -> content.DeletePostResp
	11, // 23: content.ContentCenter.GetPostDetail:output_type -> content.GetPostDetailResp
	13, // 24: content.ContentCenter.GetPostList:output_type -> content.GetPostListResp
	15, // 25: content.ContentCenter.BatchGetPost:output_type -> content.BatchGetPostResp
	18, // 26: content.ContentCenter.BatchGetPostSummary:output_type -> content.BatchGetPostSummaryResp
	20, // 27: content.ContentCenter.IncViewCount:output_type -> content.IncViewCountResp
	22, // 28: content.ContentCenter.GetTopicList:output_type -> content.GetTopicListResp
	24, // 29: content.ContentCenter.SetTopPost:output_type -> content.SetTopPostResp
	26, // 30: content.ContentCenter.SetEssencePost:output_type -> content.SetEssencePostResp
	20, // [20:31] is the sub-list for method output_type
	9,  // [9:20] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_content_proto_init() }
func file_content_proto_init() {
	if File_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_content_proto_rawDesc), len(file_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_content_proto_goTypes,
		DependencyIndexes: file_content_proto_depIdxs,
		MessageInfos:      file_content_proto_msgTypes,
	}.Build()
	File_content_proto = out.File
	file_content_proto_goTypes = nil
	file_content_proto_depIdxs = nil
}
