// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: content.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContentCenter_CreatePost_FullMethodName    = "/content.ContentCenter/CreatePost"
	ContentCenter_UpdatePost_FullMethodName    = "/content.ContentCenter/UpdatePost"
	ContentCenter_DeletePost_FullMethodName    = "/content.ContentCenter/DeletePost"
	ContentCenter_GetPostDetail_FullMethodName = "/content.ContentCenter/GetPostDetail"
	ContentCenter_GetPostList_FullMethodName   = "/content.ContentCenter/GetPostList"
	ContentCenter_BatchGetPost_FullMethodName  = "/content.ContentCenter/BatchGetPost"
	ContentCenter_IncViewCount_FullMethodName  = "/content.ContentCenter/IncViewCount"
)

// ContentCenterClient is the client API for ContentCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC服务定义
type ContentCenterClient interface {
	CreatePost(ctx context.Context, in *CreatePostReq, opts ...grpc.CallOption) (*CreatePostResp, error)
	UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*UpdatePostResp, error)
	DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*DeletePostResp, error)
	GetPostDetail(ctx context.Context, in *GetPostDetailReq, opts ...grpc.CallOption) (*GetPostDetailResp, error)
	GetPostList(ctx context.Context, in *GetPostListReq, opts ...grpc.CallOption) (*GetPostListResp, error)
	BatchGetPost(ctx context.Context, in *BatchGetPostReq, opts ...grpc.CallOption) (*BatchGetPostResp, error)
	IncViewCount(ctx context.Context, in *IncViewCountReq, opts ...grpc.CallOption) (*IncViewCountResp, error)
}

type contentCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewContentCenterClient(cc grpc.ClientConnInterface) ContentCenterClient {
	return &contentCenterClient{cc}
}

func (c *contentCenterClient) CreatePost(ctx context.Context, in *CreatePostReq, opts ...grpc.CallOption) (*CreatePostResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePostResp)
	err := c.cc.Invoke(ctx, ContentCenter_CreatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentCenterClient) UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*UpdatePostResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePostResp)
	err := c.cc.Invoke(ctx, ContentCenter_UpdatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentCenterClient) DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*DeletePostResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePostResp)
	err := c.cc.Invoke(ctx, ContentCenter_DeletePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentCenterClient) GetPostDetail(ctx context.Context, in *GetPostDetailReq, opts ...grpc.CallOption) (*GetPostDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostDetailResp)
	err := c.cc.Invoke(ctx, ContentCenter_GetPostDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentCenterClient) GetPostList(ctx context.Context, in *GetPostListReq, opts ...grpc.CallOption) (*GetPostListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostListResp)
	err := c.cc.Invoke(ctx, ContentCenter_GetPostList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentCenterClient) BatchGetPost(ctx context.Context, in *BatchGetPostReq, opts ...grpc.CallOption) (*BatchGetPostResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetPostResp)
	err := c.cc.Invoke(ctx, ContentCenter_BatchGetPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentCenterClient) IncViewCount(ctx context.Context, in *IncViewCountReq, opts ...grpc.CallOption) (*IncViewCountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncViewCountResp)
	err := c.cc.Invoke(ctx, ContentCenter_IncViewCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentCenterServer is the server API for ContentCenter service.
// All implementations must embed UnimplementedContentCenterServer
// for forward compatibility.
//
// gRPC服务定义
type ContentCenterServer interface {
	CreatePost(context.Context, *CreatePostReq) (*CreatePostResp, error)
	UpdatePost(context.Context, *UpdatePostReq) (*UpdatePostResp, error)
	DeletePost(context.Context, *DeletePostReq) (*DeletePostResp, error)
	GetPostDetail(context.Context, *GetPostDetailReq) (*GetPostDetailResp, error)
	GetPostList(context.Context, *GetPostListReq) (*GetPostListResp, error)
	BatchGetPost(context.Context, *BatchGetPostReq) (*BatchGetPostResp, error)
	IncViewCount(context.Context, *IncViewCountReq) (*IncViewCountResp, error)
	mustEmbedUnimplementedContentCenterServer()
}

// UnimplementedContentCenterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentCenterServer struct{}

func (UnimplementedContentCenterServer) CreatePost(context.Context, *CreatePostReq) (*CreatePostResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (UnimplementedContentCenterServer) UpdatePost(context.Context, *UpdatePostReq) (*UpdatePostResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePost not implemented")
}
func (UnimplementedContentCenterServer) DeletePost(context.Context, *DeletePostReq) (*DeletePostResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}
func (UnimplementedContentCenterServer) GetPostDetail(context.Context, *GetPostDetailReq) (*GetPostDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostDetail not implemented")
}
func (UnimplementedContentCenterServer) GetPostList(context.Context, *GetPostListReq) (*GetPostListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostList not implemented")
}
func (UnimplementedContentCenterServer) BatchGetPost(context.Context, *BatchGetPostReq) (*BatchGetPostResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetPost not implemented")
}
func (UnimplementedContentCenterServer) IncViewCount(context.Context, *IncViewCountReq) (*IncViewCountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncViewCount not implemented")
}
func (UnimplementedContentCenterServer) mustEmbedUnimplementedContentCenterServer() {}
func (UnimplementedContentCenterServer) testEmbeddedByValue()                       {}

// UnsafeContentCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentCenterServer will
// result in compilation errors.
type UnsafeContentCenterServer interface {
	mustEmbedUnimplementedContentCenterServer()
}

func RegisterContentCenterServer(s grpc.ServiceRegistrar, srv ContentCenterServer) {
	// If the following call pancis, it indicates UnimplementedContentCenterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContentCenter_ServiceDesc, srv)
}

func _ContentCenter_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentCenterServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentCenter_CreatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentCenterServer).CreatePost(ctx, req.(*CreatePostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentCenter_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentCenterServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentCenter_UpdatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentCenterServer).UpdatePost(ctx, req.(*UpdatePostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentCenter_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentCenterServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentCenter_DeletePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentCenterServer).DeletePost(ctx, req.(*DeletePostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentCenter_GetPostDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentCenterServer).GetPostDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentCenter_GetPostDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentCenterServer).GetPostDetail(ctx, req.(*GetPostDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentCenter_GetPostList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentCenterServer).GetPostList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentCenter_GetPostList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentCenterServer).GetPostList(ctx, req.(*GetPostListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentCenter_BatchGetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetPostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentCenterServer).BatchGetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentCenter_BatchGetPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentCenterServer).BatchGetPost(ctx, req.(*BatchGetPostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentCenter_IncViewCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncViewCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentCenterServer).IncViewCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentCenter_IncViewCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentCenterServer).IncViewCount(ctx, req.(*IncViewCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ContentCenter_ServiceDesc is the grpc.ServiceDesc for ContentCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "content.ContentCenter",
	HandlerType: (*ContentCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _ContentCenter_CreatePost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _ContentCenter_UpdatePost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _ContentCenter_DeletePost_Handler,
		},
		{
			MethodName: "GetPostDetail",
			Handler:    _ContentCenter_GetPostDetail_Handler,
		},
		{
			MethodName: "GetPostList",
			Handler:    _ContentCenter_GetPostList_Handler,
		},
		{
			MethodName: "BatchGetPost",
			Handler:    _ContentCenter_BatchGetPost_Handler,
		},
		{
			MethodName: "IncViewCount",
			Handler:    _ContentCenter_IncViewCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "content.proto",
}
