// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: content.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 帖子基本信息
type PostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                     // 帖子ID
	UserId        uint64                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`             // 发布者用户ID
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                // 帖子标题
	Cover         string                 `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`                // 封面图URL
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`                 // 帖子类型：1-图文，2-视频，3-链接等
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`             // 状态：0-草稿，1-已发布，2-审核中，3-已删除等
	ViewCount     int64                  `protobuf:"varint,7,opt,name=viewCount,proto3" json:"viewCount,omitempty"`       // 浏览量
	LikeCount     int64                  `protobuf:"varint,8,opt,name=likeCount,proto3" json:"likeCount,omitempty"`       // 点赞数
	CommentCount  int64                  `protobuf:"varint,9,opt,name=commentCount,proto3" json:"commentCount,omitempty"` // 评论数
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`      // 创建时间（Unix时间戳，秒）
	UpdatedAt     int64                  `protobuf:"varint,11,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`      // 更新时间（Unix时间戳，秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfo) Reset() {
	*x = PostInfo{}
	mi := &file_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfo) ProtoMessage() {}

func (x *PostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfo.ProtoReflect.Descriptor instead.
func (*PostInfo) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{0}
}

func (x *PostInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostInfo) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *PostInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PostInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PostInfo) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *PostInfo) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *PostInfo) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *PostInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PostInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 帖子内容信息
type PostContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`  // 所属帖子ID
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 帖子正文内容（支持富文本/Markdown）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostContent) Reset() {
	*x = PostContent{}
	mi := &file_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostContent) ProtoMessage() {}

func (x *PostContent) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostContent.ProtoReflect.Descriptor instead.
func (*PostContent) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{1}
}

func (x *PostContent) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 帖子话题信息
type PostTopic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`      // 帖子ID
	TopicId       uint64                 `protobuf:"varint,2,opt,name=topicId,proto3" json:"topicId,omitempty"`    // 话题ID
	TopicName     string                 `protobuf:"bytes,3,opt,name=topicName,proto3" json:"topicName,omitempty"` // 话题名称（冗余字段，便于展示）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTopic) Reset() {
	*x = PostTopic{}
	mi := &file_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTopic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTopic) ProtoMessage() {}

func (x *PostTopic) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTopic.ProtoReflect.Descriptor instead.
func (*PostTopic) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{2}
}

func (x *PostTopic) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostTopic) GetTopicId() uint64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *PostTopic) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

// 创建帖子请求
type CreatePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`  // 用户ID（发布者）
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`     // 标题
	Cover         string                 `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`     // 封面URL
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`      // 帖子类型
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"` // 帖子内容
	Topics        []string               `protobuf:"bytes,6,rep,name=topics,proto3" json:"topics,omitempty"`   // 关联的话题名称列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostReq) Reset() {
	*x = CreatePostReq{}
	mi := &file_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostReq) ProtoMessage() {}

func (x *CreatePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostReq.ProtoReflect.Descriptor instead.
func (*CreatePostReq) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePostReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePostReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostReq) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *CreatePostReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreatePostReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePostReq) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

// 创建帖子响应
type CreatePostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"` // 新创建的帖子ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResp) Reset() {
	*x = CreatePostResp{}
	mi := &file_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResp) ProtoMessage() {}

func (x *CreatePostResp) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResp.ProtoReflect.Descriptor instead.
func (*CreatePostResp) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePostResp) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

// 更新帖子请求
type UpdatePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`  // 帖子ID
	UserId        uint64                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`  // 操作用户ID（用于权限校验）
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`     // 标题
	Cover         string                 `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`     // 封面URL
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`      // 帖子类型
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"` // 帖子内容
	Topics        []string               `protobuf:"bytes,7,rep,name=topics,proto3" json:"topics,omitempty"`   // 关联的话题名称列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostReq) Reset() {
	*x = UpdatePostReq{}
	mi := &file_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostReq) ProtoMessage() {}

func (x *UpdatePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostReq.ProtoReflect.Descriptor instead.
func (*UpdatePostReq) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePostReq) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *UpdatePostReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdatePostReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePostReq) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *UpdatePostReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UpdatePostReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdatePostReq) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

// 更新帖子响应
type UpdatePostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否更新成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostResp) Reset() {
	*x = UpdatePostResp{}
	mi := &file_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostResp) ProtoMessage() {}

func (x *UpdatePostResp) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostResp.ProtoReflect.Descriptor instead.
func (*UpdatePostResp) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePostResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 删除帖子请求
type DeletePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"` // 帖子ID
	UserId        uint64                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"` // 操作用户ID（用于权限校验）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostReq) Reset() {
	*x = DeletePostReq{}
	mi := &file_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostReq) ProtoMessage() {}

func (x *DeletePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostReq.ProtoReflect.Descriptor instead.
func (*DeletePostReq) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePostReq) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *DeletePostReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 删除帖子响应
type DeletePostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否删除成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostResp) Reset() {
	*x = DeletePostResp{}
	mi := &file_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostResp) ProtoMessage() {}

func (x *DeletePostResp) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostResp.ProtoReflect.Descriptor instead.
func (*DeletePostResp) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePostResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 获取帖子详情请求
type GetPostDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"` // 帖子ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostDetailReq) Reset() {
	*x = GetPostDetailReq{}
	mi := &file_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostDetailReq) ProtoMessage() {}

func (x *GetPostDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostDetailReq.ProtoReflect.Descriptor instead.
func (*GetPostDetailReq) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{9}
}

func (x *GetPostDetailReq) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

// 获取帖子详情响应
type GetPostDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *PostInfo              `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`       // 帖子基本信息
	Content       *PostContent           `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 帖子正文内容
	Topics        []*PostTopic           `protobuf:"bytes,3,rep,name=topics,proto3" json:"topics,omitempty"`   // 帖子关联的话题列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostDetailResp) Reset() {
	*x = GetPostDetailResp{}
	mi := &file_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostDetailResp) ProtoMessage() {}

func (x *GetPostDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostDetailResp.ProtoReflect.Descriptor instead.
func (*GetPostDetailResp) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{10}
}

func (x *GetPostDetailResp) GetPost() *PostInfo {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *GetPostDetailResp) GetContent() *PostContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GetPostDetailResp) GetTopics() []*PostTopic {
	if x != nil {
		return x.Topics
	}
	return nil
}

// 获取帖子列表请求
type GetPostListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`     // 用户ID（可选，用于筛选某个用户的帖子）
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`         // 帖子类型（可选，0表示不过滤）
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`         // 页码，从1开始
	PageSize      int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostListReq) Reset() {
	*x = GetPostListReq{}
	mi := &file_content_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostListReq) ProtoMessage() {}

func (x *GetPostListReq) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostListReq.ProtoReflect.Descriptor instead.
func (*GetPostListReq) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{11}
}

func (x *GetPostListReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPostListReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GetPostListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPostListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取帖子列表响应
type GetPostListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"` // 总数
	List          []*PostInfo            `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`    // 帖子列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostListResp) Reset() {
	*x = GetPostListResp{}
	mi := &file_content_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostListResp) ProtoMessage() {}

func (x *GetPostListResp) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostListResp.ProtoReflect.Descriptor instead.
func (*GetPostListResp) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{12}
}

func (x *GetPostListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetPostListResp) GetList() []*PostInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// 批量获取帖子请求
type BatchGetPostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostIds       []uint64               `protobuf:"varint,1,rep,packed,name=postIds,proto3" json:"postIds,omitempty"` // 帖子ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetPostReq) Reset() {
	*x = BatchGetPostReq{}
	mi := &file_content_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetPostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetPostReq) ProtoMessage() {}

func (x *BatchGetPostReq) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetPostReq.ProtoReflect.Descriptor instead.
func (*BatchGetPostReq) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{13}
}

func (x *BatchGetPostReq) GetPostIds() []uint64 {
	if x != nil {
		return x.PostIds
	}
	return nil
}

// 批量获取帖子响应
type BatchGetPostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostInfo            `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"` // 帖子基本信息列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetPostResp) Reset() {
	*x = BatchGetPostResp{}
	mi := &file_content_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetPostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetPostResp) ProtoMessage() {}

func (x *BatchGetPostResp) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetPostResp.ProtoReflect.Descriptor instead.
func (*BatchGetPostResp) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{14}
}

func (x *BatchGetPostResp) GetPosts() []*PostInfo {
	if x != nil {
		return x.Posts
	}
	return nil
}

// 增加浏览量请求
type IncViewCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"` // 帖子ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncViewCountReq) Reset() {
	*x = IncViewCountReq{}
	mi := &file_content_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncViewCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncViewCountReq) ProtoMessage() {}

func (x *IncViewCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncViewCountReq.ProtoReflect.Descriptor instead.
func (*IncViewCountReq) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{15}
}

func (x *IncViewCountReq) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

// 增加浏览量响应
type IncViewCountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncViewCountResp) Reset() {
	*x = IncViewCountResp{}
	mi := &file_content_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncViewCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncViewCountResp) ProtoMessage() {}

func (x *IncViewCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_content_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncViewCountResp.ProtoReflect.Descriptor instead.
func (*IncViewCountResp) Descriptor() ([]byte, []int) {
	return file_content_proto_rawDescGZIP(), []int{16}
}

func (x *IncViewCountResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_content_proto protoreflect.FileDescriptor

const file_content_proto_rawDesc = "" +
	"\n" +
	"\rcontent.proto\x12\acontent\"\xa6\x02\n" +
	"\bPostInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05cover\x18\x04 \x01(\tR\x05cover\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1c\n" +
	"\tviewCount\x18\a \x01(\x03R\tviewCount\x12\x1c\n" +
	"\tlikeCount\x18\b \x01(\x03R\tlikeCount\x12\"\n" +
	"\fcommentCount\x18\t \x01(\x03R\fcommentCount\x12\x1c\n" +
	"\tcreatedAt\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\v \x01(\x03R\tupdatedAt\"?\n" +
	"\vPostContent\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x04R\x06postId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"[\n" +
	"\tPostTopic\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x04R\x06postId\x12\x18\n" +
	"\atopicId\x18\x02 \x01(\x04R\atopicId\x12\x1c\n" +
	"\ttopicName\x18\x03 \x01(\tR\ttopicName\"\x99\x01\n" +
	"\rCreatePostReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05cover\x18\x03 \x01(\tR\x05cover\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x16\n" +
	"\x06topics\x18\x06 \x03(\tR\x06topics\"(\n" +
	"\x0eCreatePostResp\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x04R\x06postId\"\xb1\x01\n" +
	"\rUpdatePostReq\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x04R\x06postId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05cover\x18\x04 \x01(\tR\x05cover\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x16\n" +
	"\x06topics\x18\a \x03(\tR\x06topics\"*\n" +
	"\x0eUpdatePostResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"?\n" +
	"\rDeletePostReq\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x04R\x06postId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x04R\x06userId\"*\n" +
	"\x0eDeletePostResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x10GetPostDetailReq\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x04R\x06postId\"\x96\x01\n" +
	"\x11GetPostDetailResp\x12%\n" +
	"\x04post\x18\x01 \x01(\v2\x11.content.PostInfoR\x04post\x12.\n" +
	"\acontent\x18\x02 \x01(\v2\x14.content.PostContentR\acontent\x12*\n" +
	"\x06topics\x18\x03 \x03(\v2\x12.content.PostTopicR\x06topics\"l\n" +
	"\x0eGetPostListReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\"N\n" +
	"\x0fGetPostListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12%\n" +
	"\x04list\x18\x02 \x03(\v2\x11.content.PostInfoR\x04list\"+\n" +
	"\x0fBatchGetPostReq\x12\x18\n" +
	"\apostIds\x18\x01 \x03(\x04R\apostIds\";\n" +
	"\x10BatchGetPostResp\x12'\n" +
	"\x05posts\x18\x01 \x03(\v2\x11.content.PostInfoR\x05posts\")\n" +
	"\x0fIncViewCountReq\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x04R\x06postId\",\n" +
	"\x10IncViewCountResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe0\x03\n" +
	"\rContentCenter\x12=\n" +
	"\n" +
	"CreatePost\x12\x16.content.CreatePostReq\x1a\x17.content.CreatePostResp\x12=\n" +
	"\n" +
	"UpdatePost\x12\x16.content.UpdatePostReq\x1a\x17.content.UpdatePostResp\x12=\n" +
	"\n" +
	"DeletePost\x12\x16.content.DeletePostReq\x1a\x17.content.DeletePostResp\x12F\n" +
	"\rGetPostDetail\x12\x19.content.GetPostDetailReq\x1a\x1a.content.GetPostDetailResp\x12@\n" +
	"\vGetPostList\x12\x17.content.GetPostListReq\x1a\x18.content.GetPostListResp\x12C\n" +
	"\fBatchGetPost\x12\x18.content.BatchGetPostReq\x1a\x19.content.BatchGetPostResp\x12C\n" +
	"\fIncViewCount\x12\x18.content.IncViewCountReq\x1a\x19.content.IncViewCountRespB\x05Z\x03/pbb\x06proto3"

var (
	file_content_proto_rawDescOnce sync.Once
	file_content_proto_rawDescData []byte
)

func file_content_proto_rawDescGZIP() []byte {
	file_content_proto_rawDescOnce.Do(func() {
		file_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_content_proto_rawDesc), len(file_content_proto_rawDesc)))
	})
	return file_content_proto_rawDescData
}

var file_content_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_content_proto_goTypes = []any{
	(*PostInfo)(nil),          // 0: content.PostInfo
	(*PostContent)(nil),       // 1: content.PostContent
	(*PostTopic)(nil),         // 2: content.PostTopic
	(*CreatePostReq)(nil),     // 3: content.CreatePostReq
	(*CreatePostResp)(nil),    // 4: content.CreatePostResp
	(*UpdatePostReq)(nil),     // 5: content.UpdatePostReq
	(*UpdatePostResp)(nil),    // 6: content.UpdatePostResp
	(*DeletePostReq)(nil),     // 7: content.DeletePostReq
	(*DeletePostResp)(nil),    // 8: content.DeletePostResp
	(*GetPostDetailReq)(nil),  // 9: content.GetPostDetailReq
	(*GetPostDetailResp)(nil), // 10: content.GetPostDetailResp
	(*GetPostListReq)(nil),    // 11: content.GetPostListReq
	(*GetPostListResp)(nil),   // 12: content.GetPostListResp
	(*BatchGetPostReq)(nil),   // 13: content.BatchGetPostReq
	(*BatchGetPostResp)(nil),  // 14: content.BatchGetPostResp
	(*IncViewCountReq)(nil),   // 15: content.IncViewCountReq
	(*IncViewCountResp)(nil),  // 16: content.IncViewCountResp
}
var file_content_proto_depIdxs = []int32{
	0,  // 0: content.GetPostDetailResp.post:type_name -> content.PostInfo
	1,  // 1: content.GetPostDetailResp.content:type_name -> content.PostContent
	2,  // 2: content.GetPostDetailResp.topics:type_name -> content.PostTopic
	0,  // 3: content.GetPostListResp.list:type_name -> content.PostInfo
	0,  // 4: content.BatchGetPostResp.posts:type_name -> content.PostInfo
	3,  // 5: content.ContentCenter.CreatePost:input_type -> content.CreatePostReq
	5,  // 6: content.ContentCenter.UpdatePost:input_type -> content.UpdatePostReq
	7,  // 7: content.ContentCenter.DeletePost:input_type -> content.DeletePostReq
	9,  // 8: content.ContentCenter.GetPostDetail:input_type -> content.GetPostDetailReq
	11, // 9: content.ContentCenter.GetPostList:input_type -> content.GetPostListReq
	13, // 10: content.ContentCenter.BatchGetPost:input_type -> content.BatchGetPostReq
	15, // 11: content.ContentCenter.IncViewCount:input_type -> content.IncViewCountReq
	4,  // 12: content.ContentCenter.CreatePost:output_type -> content.CreatePostResp
	6,  // 13: content.ContentCenter.UpdatePost:output_type -> content.UpdatePostResp
	8,  // 14: content.ContentCenter.DeletePost:output_type -> content.DeletePostResp
	10, // 15: content.ContentCenter.GetPostDetail:output_type -> content.GetPostDetailResp
	12, // 16: content.ContentCenter.GetPostList:output_type -> content.GetPostListResp
	14, // 17: content.ContentCenter.BatchGetPost:output_type -> content.BatchGetPostResp
	16, // 18: content.ContentCenter.IncViewCount:output_type -> content.IncViewCountResp
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_content_proto_init() }
func file_content_proto_init() {
	if File_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_content_proto_rawDesc), len(file_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_content_proto_goTypes,
		DependencyIndexes: file_content_proto_depIdxs,
		MessageInfos:      file_content_proto_msgTypes,
	}.Build()
	File_content_proto = out.File
	file_content_proto_goTypes = nil
	file_content_proto_depIdxs = nil
}
