// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package usercenter

import (
	"context"

	"SChill/service/user/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserInfoReq            = pb.GetUserInfoReq
	GetUserInfoResp           = pb.GetUserInfoResp
	GetUserProfileInfoReq     = pb.GetUserProfileInfoReq
	GetUserProfileInfoResp    = pb.GetUserProfileInfoResp
	GetUserStatReq            = pb.GetUserStatReq
	GetUserStatResp           = pb.GetUserStatResp
	LoginReq                  = pb.LoginReq
	LoginResp                 = pb.LoginResp
	RegisterReq               = pb.RegisterReq
	RegisterResp              = pb.RegisterResp
	UpdateAvatarReq           = pb.UpdateAvatarReq
	UpdateAvatarResp          = pb.UpdateAvatarResp
	UpdateUserProfileInfoReq  = pb.UpdateUserProfileInfoReq
	UpdateUserProfileInfoResp = pb.UpdateUserProfileInfoResp
	UpdateUserStatusReq       = pb.UpdateUserStatusReq
	UpdateUserStatusResp      = pb.UpdateUserStatusResp
	UserInfo                  = pb.UserInfo
	UserProfile               = pb.UserProfile
	UserStat                  = pb.UserStat

	UserCenter interface {
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		UpdateUserStatus(ctx context.Context, in *UpdateUserStatusReq, opts ...grpc.CallOption) (*UpdateUserStatusResp, error)
		UpdateUserProfileInfo(ctx context.Context, in *UpdateUserProfileInfoReq, opts ...grpc.CallOption) (*UpdateUserProfileInfoResp, error)
		GetUserStat(ctx context.Context, in *GetUserStatReq, opts ...grpc.CallOption) (*GetUserStatResp, error)
		GetUserProfileInfo(ctx context.Context, in *GetUserProfileInfoReq, opts ...grpc.CallOption) (*GetUserProfileInfoResp, error)
		UpdateAvatar(ctx context.Context, in *UpdateAvatarReq, opts ...grpc.CallOption) (*UpdateAvatarResp, error)
	}

	defaultUserCenter struct {
		cli zrpc.Client
	}
)

func NewUserCenter(cli zrpc.Client) UserCenter {
	return &defaultUserCenter{
		cli: cli,
	}
}

func (m *defaultUserCenter) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := pb.NewUserCenterClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUserCenter) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewUserCenterClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUserCenter) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := pb.NewUserCenterClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUserCenter) UpdateUserStatus(ctx context.Context, in *UpdateUserStatusReq, opts ...grpc.CallOption) (*UpdateUserStatusResp, error) {
	client := pb.NewUserCenterClient(m.cli.Conn())
	return client.UpdateUserStatus(ctx, in, opts...)
}

func (m *defaultUserCenter) UpdateUserProfileInfo(ctx context.Context, in *UpdateUserProfileInfoReq, opts ...grpc.CallOption) (*UpdateUserProfileInfoResp, error) {
	client := pb.NewUserCenterClient(m.cli.Conn())
	return client.UpdateUserProfileInfo(ctx, in, opts...)
}

func (m *defaultUserCenter) GetUserStat(ctx context.Context, in *GetUserStatReq, opts ...grpc.CallOption) (*GetUserStatResp, error) {
	client := pb.NewUserCenterClient(m.cli.Conn())
	return client.GetUserStat(ctx, in, opts...)
}

func (m *defaultUserCenter) GetUserProfileInfo(ctx context.Context, in *GetUserProfileInfoReq, opts ...grpc.CallOption) (*GetUserProfileInfoResp, error) {
	client := pb.NewUserCenterClient(m.cli.Conn())
	return client.GetUserProfileInfo(ctx, in, opts...)
}

func (m *defaultUserCenter) UpdateAvatar(ctx context.Context, in *UpdateAvatarReq, opts ...grpc.CallOption) (*UpdateAvatarResp, error) {
	client := pb.NewUserCenterClient(m.cli.Conn())
	return client.UpdateAvatar(ctx, in, opts...)
}
