// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"SChill/service/user/rpc/internal/logic"
	"SChill/service/user/rpc/internal/svc"
	"SChill/service/user/rpc/pb"
)

type UserCenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserCenterServer
}

func NewUserCenterServer(svcCtx *svc.ServiceContext) *UserCenterServer {
	return &UserCenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UserCenterServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserCenterServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserCenterServer) GetUserInfo(ctx context.Context, in *pb.GetUserInfoReq) (*pb.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserCenterServer) UpdateUserStatus(ctx context.Context, in *pb.UpdateUserStatusReq) (*pb.UpdateUserStatusResp, error) {
	l := logic.NewUpdateUserStatusLogic(ctx, s.svcCtx)
	return l.UpdateUserStatus(in)
}

func (s *UserCenterServer) UpdateUserProfileInfo(ctx context.Context, in *pb.UpdateUserProfileInfoReq) (*pb.UpdateUserProfileInfoResp, error) {
	l := logic.NewUpdateUserProfileInfoLogic(ctx, s.svcCtx)
	return l.UpdateUserProfileInfo(in)
}

func (s *UserCenterServer) GetUserStat(ctx context.Context, in *pb.GetUserStatReq) (*pb.GetUserStatResp, error) {
	l := logic.NewGetUserStatLogic(ctx, s.svcCtx)
	return l.GetUserStat(in)
}

func (s *UserCenterServer) GetUserProfileInfo(ctx context.Context, in *pb.GetUserProfileInfoReq) (*pb.GetUserProfileInfoResp, error) {
	l := logic.NewGetUserProfileInfoLogic(ctx, s.svcCtx)
	return l.GetUserProfileInfo(in)
}

func (s *UserCenterServer) UpdateAvatar(ctx context.Context, in *pb.UpdateAvatarReq) (*pb.UpdateAvatarResp, error) {
	l := logic.NewUpdateAvatarLogic(ctx, s.svcCtx)
	return l.UpdateAvatar(in)
}
