// Code generated by goctl. Safe to edit.

package feedcenter

import (
	"context"

	"SChill/service/feed/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetFeedListReq  = pb.GetFeedListReq
	GetFeedListResp = pb.GetFeedListResp
	FeedAuthor      = pb.FeedAuthor
	FeedItem        = pb.FeedItem
	FeedViewerState = pb.FeedViewerState

	FeedCenter interface {
		GetFeedList(ctx context.Context, in *GetFeedListReq, opts ...grpc.CallOption) (*GetFeedListResp, error)
	}

	defaultFeedCenter struct {
		cli zrpc.Client
	}
)

func NewFeedCenter(cli zrpc.Client) FeedCenter {
	return &defaultFeedCenter{
		cli: cli,
	}
}

func (m *defaultFeedCenter) GetFeedList(ctx context.Context, in *GetFeedListReq, opts ...grpc.CallOption) (*GetFeedListResp, error) {
	client := pb.NewFeedCenterClient(m.cli.Conn())
	return client.GetFeedList(ctx, in, opts...)
}
