// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: interaction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 互动类型枚举
type InteractionType int32

const (
	InteractionType_INTERACTION_TYPE_UNSPECIFIED     InteractionType = 0
	InteractionType_INTERACTION_TYPE_POST_STAR       InteractionType = 1 // 动态点赞
	InteractionType_INTERACTION_TYPE_POST_COLLECTION InteractionType = 2 // 动态收藏
	InteractionType_INTERACTION_TYPE_POST_SHARE      InteractionType = 3 // 动态分享
	InteractionType_INTERACTION_TYPE_COMMENT_VOTE    InteractionType = 4 // 评论点赞
)

// Enum value maps for InteractionType.
var (
	InteractionType_name = map[int32]string{
		0: "INTERACTION_TYPE_UNSPECIFIED",
		1: "INTERACTION_TYPE_POST_STAR",
		2: "INTERACTION_TYPE_POST_COLLECTION",
		3: "INTERACTION_TYPE_POST_SHARE",
		4: "INTERACTION_TYPE_COMMENT_VOTE",
	}
	InteractionType_value = map[string]int32{
		"INTERACTION_TYPE_UNSPECIFIED":     0,
		"INTERACTION_TYPE_POST_STAR":       1,
		"INTERACTION_TYPE_POST_COLLECTION": 2,
		"INTERACTION_TYPE_POST_SHARE":      3,
		"INTERACTION_TYPE_COMMENT_VOTE":    4,
	}
)

func (x InteractionType) Enum() *InteractionType {
	p := new(InteractionType)
	*p = x
	return p
}

func (x InteractionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InteractionType) Descriptor() protoreflect.EnumDescriptor {
	return file_interaction_proto_enumTypes[0].Descriptor()
}

func (InteractionType) Type() protoreflect.EnumType {
	return &file_interaction_proto_enumTypes[0]
}

func (x InteractionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InteractionType.Descriptor instead.
func (InteractionType) EnumDescriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{0}
}

// 点赞状态响应
type StarStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsStarred     bool                   `protobuf:"varint,1,opt,name=isStarred,proto3" json:"isStarred,omitempty"` // 是否已点赞
	StarCount     int64                  `protobuf:"varint,2,opt,name=starCount,proto3" json:"starCount,omitempty"` // 点赞数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarStatus) Reset() {
	*x = StarStatus{}
	mi := &file_interaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarStatus) ProtoMessage() {}

func (x *StarStatus) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarStatus.ProtoReflect.Descriptor instead.
func (*StarStatus) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{0}
}

func (x *StarStatus) GetIsStarred() bool {
	if x != nil {
		return x.IsStarred
	}
	return false
}

func (x *StarStatus) GetStarCount() int64 {
	if x != nil {
		return x.StarCount
	}
	return 0
}

// 收藏状态响应
type CollectionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCollected   bool                   `protobuf:"varint,1,opt,name=isCollected,proto3" json:"isCollected,omitempty"` // 是否已收藏
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionStatus) Reset() {
	*x = CollectionStatus{}
	mi := &file_interaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionStatus) ProtoMessage() {}

func (x *CollectionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionStatus.ProtoReflect.Descriptor instead.
func (*CollectionStatus) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{1}
}

func (x *CollectionStatus) GetIsCollected() bool {
	if x != nil {
		return x.IsCollected
	}
	return false
}

// 动态点赞请求
type StarPostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=postId,proto3" json:"postId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarPostReq) Reset() {
	*x = StarPostReq{}
	mi := &file_interaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarPostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarPostReq) ProtoMessage() {}

func (x *StarPostReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarPostReq.ProtoReflect.Descriptor instead.
func (*StarPostReq) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{2}
}

func (x *StarPostReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StarPostReq) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

// 动态点赞响应
type StarPostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	IsStarred     bool                   `protobuf:"varint,2,opt,name=isStarred,proto3" json:"isStarred,omitempty"`
	StarCount     int64                  `protobuf:"varint,3,opt,name=starCount,proto3" json:"starCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarPostResp) Reset() {
	*x = StarPostResp{}
	mi := &file_interaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarPostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarPostResp) ProtoMessage() {}

func (x *StarPostResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarPostResp.ProtoReflect.Descriptor instead.
func (*StarPostResp) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{3}
}

func (x *StarPostResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StarPostResp) GetIsStarred() bool {
	if x != nil {
		return x.IsStarred
	}
	return false
}

func (x *StarPostResp) GetStarCount() int64 {
	if x != nil {
		return x.StarCount
	}
	return 0
}

// 动态取消点赞请求
type UnstarPostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=postId,proto3" json:"postId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnstarPostReq) Reset() {
	*x = UnstarPostReq{}
	mi := &file_interaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnstarPostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnstarPostReq) ProtoMessage() {}

func (x *UnstarPostReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnstarPostReq.ProtoReflect.Descriptor instead.
func (*UnstarPostReq) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{4}
}

func (x *UnstarPostReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnstarPostReq) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

// 动态取消点赞响应
type UnstarPostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	IsStarred     bool                   `protobuf:"varint,2,opt,name=isStarred,proto3" json:"isStarred,omitempty"`
	StarCount     int64                  `protobuf:"varint,3,opt,name=starCount,proto3" json:"starCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnstarPostResp) Reset() {
	*x = UnstarPostResp{}
	mi := &file_interaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnstarPostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnstarPostResp) ProtoMessage() {}

func (x *UnstarPostResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnstarPostResp.ProtoReflect.Descriptor instead.
func (*UnstarPostResp) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{5}
}

func (x *UnstarPostResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnstarPostResp) GetIsStarred() bool {
	if x != nil {
		return x.IsStarred
	}
	return false
}

func (x *UnstarPostResp) GetStarCount() int64 {
	if x != nil {
		return x.StarCount
	}
	return 0
}

// 检查动态点赞状态请求
type CheckPostStarReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=postId,proto3" json:"postId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPostStarReq) Reset() {
	*x = CheckPostStarReq{}
	mi := &file_interaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPostStarReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPostStarReq) ProtoMessage() {}

func (x *CheckPostStarReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPostStarReq.ProtoReflect.Descriptor instead.
func (*CheckPostStarReq) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{6}
}

func (x *CheckPostStarReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckPostStarReq) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

// 检查动态点赞状态响应
type CheckPostStarResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsStarred     bool                   `protobuf:"varint,1,opt,name=isStarred,proto3" json:"isStarred,omitempty"`
	StarCount     int64                  `protobuf:"varint,2,opt,name=starCount,proto3" json:"starCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPostStarResp) Reset() {
	*x = CheckPostStarResp{}
	mi := &file_interaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPostStarResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPostStarResp) ProtoMessage() {}

func (x *CheckPostStarResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPostStarResp.ProtoReflect.Descriptor instead.
func (*CheckPostStarResp) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{7}
}

func (x *CheckPostStarResp) GetIsStarred() bool {
	if x != nil {
		return x.IsStarred
	}
	return false
}

func (x *CheckPostStarResp) GetStarCount() int64 {
	if x != nil {
		return x.StarCount
	}
	return 0
}

// 批量检查动态点赞状态请求
type BatchCheckPostStarReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostIds       []uint64               `protobuf:"varint,2,rep,packed,name=postIds,proto3" json:"postIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckPostStarReq) Reset() {
	*x = BatchCheckPostStarReq{}
	mi := &file_interaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckPostStarReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckPostStarReq) ProtoMessage() {}

func (x *BatchCheckPostStarReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckPostStarReq.ProtoReflect.Descriptor instead.
func (*BatchCheckPostStarReq) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{8}
}

func (x *BatchCheckPostStarReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BatchCheckPostStarReq) GetPostIds() []uint64 {
	if x != nil {
		return x.PostIds
	}
	return nil
}

// 批量检查动态点赞状态响应
type BatchCheckPostStarResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StarStatus    map[uint64]bool        `protobuf:"bytes,1,rep,name=starStatus,proto3" json:"starStatus,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // postId -> isStarred
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckPostStarResp) Reset() {
	*x = BatchCheckPostStarResp{}
	mi := &file_interaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckPostStarResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckPostStarResp) ProtoMessage() {}

func (x *BatchCheckPostStarResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckPostStarResp.ProtoReflect.Descriptor instead.
func (*BatchCheckPostStarResp) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{9}
}

func (x *BatchCheckPostStarResp) GetStarStatus() map[uint64]bool {
	if x != nil {
		return x.StarStatus
	}
	return nil
}

// 动态收藏请求
type CollectPostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=postId,proto3" json:"postId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectPostReq) Reset() {
	*x = CollectPostReq{}
	mi := &file_interaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectPostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectPostReq) ProtoMessage() {}

func (x *CollectPostReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectPostReq.ProtoReflect.Descriptor instead.
func (*CollectPostReq) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{10}
}

func (x *CollectPostReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CollectPostReq) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

// 动态收藏响应
type CollectPostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	IsCollected   bool                   `protobuf:"varint,2,opt,name=isCollected,proto3" json:"isCollected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectPostResp) Reset() {
	*x = CollectPostResp{}
	mi := &file_interaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectPostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectPostResp) ProtoMessage() {}

func (x *CollectPostResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectPostResp.ProtoReflect.Descriptor instead.
func (*CollectPostResp) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{11}
}

func (x *CollectPostResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CollectPostResp) GetIsCollected() bool {
	if x != nil {
		return x.IsCollected
	}
	return false
}

// 动态取消收藏请求
type UncollectPostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=postId,proto3" json:"postId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UncollectPostReq) Reset() {
	*x = UncollectPostReq{}
	mi := &file_interaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UncollectPostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UncollectPostReq) ProtoMessage() {}

func (x *UncollectPostReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UncollectPostReq.ProtoReflect.Descriptor instead.
func (*UncollectPostReq) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{12}
}

func (x *UncollectPostReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UncollectPostReq) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

// 动态取消收藏响应
type UncollectPostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	IsCollected   bool                   `protobuf:"varint,2,opt,name=isCollected,proto3" json:"isCollected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UncollectPostResp) Reset() {
	*x = UncollectPostResp{}
	mi := &file_interaction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UncollectPostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UncollectPostResp) ProtoMessage() {}

func (x *UncollectPostResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UncollectPostResp.ProtoReflect.Descriptor instead.
func (*UncollectPostResp) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{13}
}

func (x *UncollectPostResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UncollectPostResp) GetIsCollected() bool {
	if x != nil {
		return x.IsCollected
	}
	return false
}

// 检查动态收藏状态请求
type CheckPostCollectionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=postId,proto3" json:"postId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPostCollectionReq) Reset() {
	*x = CheckPostCollectionReq{}
	mi := &file_interaction_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPostCollectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPostCollectionReq) ProtoMessage() {}

func (x *CheckPostCollectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPostCollectionReq.ProtoReflect.Descriptor instead.
func (*CheckPostCollectionReq) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{14}
}

func (x *CheckPostCollectionReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckPostCollectionReq) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

// 检查动态收藏状态响应
type CheckPostCollectionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCollected   bool                   `protobuf:"varint,1,opt,name=isCollected,proto3" json:"isCollected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPostCollectionResp) Reset() {
	*x = CheckPostCollectionResp{}
	mi := &file_interaction_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPostCollectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPostCollectionResp) ProtoMessage() {}

func (x *CheckPostCollectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPostCollectionResp.ProtoReflect.Descriptor instead.
func (*CheckPostCollectionResp) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{15}
}

func (x *CheckPostCollectionResp) GetIsCollected() bool {
	if x != nil {
		return x.IsCollected
	}
	return false
}

// 批量检查动态收藏状态请求
type BatchCheckPostCollectionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostIds       []uint64               `protobuf:"varint,2,rep,packed,name=postIds,proto3" json:"postIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckPostCollectionReq) Reset() {
	*x = BatchCheckPostCollectionReq{}
	mi := &file_interaction_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckPostCollectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckPostCollectionReq) ProtoMessage() {}

func (x *BatchCheckPostCollectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckPostCollectionReq.ProtoReflect.Descriptor instead.
func (*BatchCheckPostCollectionReq) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{16}
}

func (x *BatchCheckPostCollectionReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BatchCheckPostCollectionReq) GetPostIds() []uint64 {
	if x != nil {
		return x.PostIds
	}
	return nil
}

// 批量检查动态收藏状态响应
type BatchCheckPostCollectionResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CollectionStatus map[uint64]bool        `protobuf:"bytes,1,rep,name=collectionStatus,proto3" json:"collectionStatus,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // postId -> isCollected
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchCheckPostCollectionResp) Reset() {
	*x = BatchCheckPostCollectionResp{}
	mi := &file_interaction_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckPostCollectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckPostCollectionResp) ProtoMessage() {}

func (x *BatchCheckPostCollectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckPostCollectionResp.ProtoReflect.Descriptor instead.
func (*BatchCheckPostCollectionResp) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{17}
}

func (x *BatchCheckPostCollectionResp) GetCollectionStatus() map[uint64]bool {
	if x != nil {
		return x.CollectionStatus
	}
	return nil
}

// 动态分享请求
type SharePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=postId,proto3" json:"postId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharePostReq) Reset() {
	*x = SharePostReq{}
	mi := &file_interaction_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharePostReq) ProtoMessage() {}

func (x *SharePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharePostReq.ProtoReflect.Descriptor instead.
func (*SharePostReq) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{18}
}

func (x *SharePostReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SharePostReq) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

// 动态分享响应
type SharePostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ShareCount    int64                  `protobuf:"varint,2,opt,name=shareCount,proto3" json:"shareCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharePostResp) Reset() {
	*x = SharePostResp{}
	mi := &file_interaction_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharePostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharePostResp) ProtoMessage() {}

func (x *SharePostResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharePostResp.ProtoReflect.Descriptor instead.
func (*SharePostResp) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{19}
}

func (x *SharePostResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SharePostResp) GetShareCount() int64 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

var File_interaction_proto protoreflect.FileDescriptor

const file_interaction_proto_rawDesc = "" +
	"\n" +
	"\x11interaction.proto\x12\vinteraction\"H\n" +
	"\n" +
	"StarStatus\x12\x1c\n" +
	"\tisStarred\x18\x01 \x01(\bR\tisStarred\x12\x1c\n" +
	"\tstarCount\x18\x02 \x01(\x03R\tstarCount\"4\n" +
	"\x10CollectionStatus\x12 \n" +
	"\visCollected\x18\x01 \x01(\bR\visCollected\"=\n" +
	"\vStarPostReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06postId\x18\x02 \x01(\x04R\x06postId\"d\n" +
	"\fStarPostResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1c\n" +
	"\tisStarred\x18\x02 \x01(\bR\tisStarred\x12\x1c\n" +
	"\tstarCount\x18\x03 \x01(\x03R\tstarCount\"?\n" +
	"\rUnstarPostReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06postId\x18\x02 \x01(\x04R\x06postId\"f\n" +
	"\x0eUnstarPostResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1c\n" +
	"\tisStarred\x18\x02 \x01(\bR\tisStarred\x12\x1c\n" +
	"\tstarCount\x18\x03 \x01(\x03R\tstarCount\"B\n" +
	"\x10CheckPostStarReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06postId\x18\x02 \x01(\x04R\x06postId\"O\n" +
	"\x11CheckPostStarResp\x12\x1c\n" +
	"\tisStarred\x18\x01 \x01(\bR\tisStarred\x12\x1c\n" +
	"\tstarCount\x18\x02 \x01(\x03R\tstarCount\"I\n" +
	"\x15BatchCheckPostStarReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x18\n" +
	"\apostIds\x18\x02 \x03(\x04R\apostIds\"\xac\x01\n" +
	"\x16BatchCheckPostStarResp\x12S\n" +
	"\n" +
	"starStatus\x18\x01 \x03(\v23.interaction.BatchCheckPostStarResp.StarStatusEntryR\n" +
	"starStatus\x1a=\n" +
	"\x0fStarStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"@\n" +
	"\x0eCollectPostReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06postId\x18\x02 \x01(\x04R\x06postId\"M\n" +
	"\x0fCollectPostResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12 \n" +
	"\visCollected\x18\x02 \x01(\bR\visCollected\"B\n" +
	"\x10UncollectPostReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06postId\x18\x02 \x01(\x04R\x06postId\"O\n" +
	"\x11UncollectPostResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12 \n" +
	"\visCollected\x18\x02 \x01(\bR\visCollected\"H\n" +
	"\x16CheckPostCollectionReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06postId\x18\x02 \x01(\x04R\x06postId\";\n" +
	"\x17CheckPostCollectionResp\x12 \n" +
	"\visCollected\x18\x01 \x01(\bR\visCollected\"O\n" +
	"\x1bBatchCheckPostCollectionReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x18\n" +
	"\apostIds\x18\x02 \x03(\x04R\apostIds\"\xd0\x01\n" +
	"\x1cBatchCheckPostCollectionResp\x12k\n" +
	"\x10collectionStatus\x18\x01 \x03(\v2?.interaction.BatchCheckPostCollectionResp.CollectionStatusEntryR\x10collectionStatus\x1aC\n" +
	"\x15CollectionStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\">\n" +
	"\fSharePostReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06postId\x18\x02 \x01(\x04R\x06postId\"I\n" +
	"\rSharePostResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1e\n" +
	"\n" +
	"shareCount\x18\x02 \x01(\x03R\n" +
	"shareCount*\xbd\x01\n" +
	"\x0fInteractionType\x12 \n" +
	"\x1cINTERACTION_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aINTERACTION_TYPE_POST_STAR\x10\x01\x12$\n" +
	" INTERACTION_TYPE_POST_COLLECTION\x10\x02\x12\x1f\n" +
	"\x1bINTERACTION_TYPE_POST_SHARE\x10\x03\x12!\n" +
	"\x1dINTERACTION_TYPE_COMMENT_VOTE\x10\x042\xfb\x05\n" +
	"\x11InteractionCenter\x12?\n" +
	"\bStarPost\x12\x18.interaction.StarPostReq\x1a\x19.interaction.StarPostResp\x12E\n" +
	"\n" +
	"UnstarPost\x12\x1a.interaction.UnstarPostReq\x1a\x1b.interaction.UnstarPostResp\x12N\n" +
	"\rCheckPostStar\x12\x1d.interaction.CheckPostStarReq\x1a\x1e.interaction.CheckPostStarResp\x12]\n" +
	"\x12BatchCheckPostStar\x12\".interaction.BatchCheckPostStarReq\x1a#.interaction.BatchCheckPostStarResp\x12H\n" +
	"\vCollectPost\x12\x1b.interaction.CollectPostReq\x1a\x1c.interaction.CollectPostResp\x12N\n" +
	"\rUncollectPost\x12\x1d.interaction.UncollectPostReq\x1a\x1e.interaction.UncollectPostResp\x12`\n" +
	"\x13CheckPostCollection\x12#.interaction.CheckPostCollectionReq\x1a$.interaction.CheckPostCollectionResp\x12o\n" +
	"\x18BatchCheckPostCollection\x12(.interaction.BatchCheckPostCollectionReq\x1a).interaction.BatchCheckPostCollectionResp\x12B\n" +
	"\tSharePost\x12\x19.interaction.SharePostReq\x1a\x1a.interaction.SharePostRespB\x05Z\x03/pbb\x06proto3"

var (
	file_interaction_proto_rawDescOnce sync.Once
	file_interaction_proto_rawDescData []byte
)

func file_interaction_proto_rawDescGZIP() []byte {
	file_interaction_proto_rawDescOnce.Do(func() {
		file_interaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interaction_proto_rawDesc), len(file_interaction_proto_rawDesc)))
	})
	return file_interaction_proto_rawDescData
}

var file_interaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_interaction_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_interaction_proto_goTypes = []any{
	(InteractionType)(0),                 // 0: interaction.InteractionType
	(*StarStatus)(nil),                   // 1: interaction.StarStatus
	(*CollectionStatus)(nil),             // 2: interaction.CollectionStatus
	(*StarPostReq)(nil),                  // 3: interaction.StarPostReq
	(*StarPostResp)(nil),                 // 4: interaction.StarPostResp
	(*UnstarPostReq)(nil),                // 5: interaction.UnstarPostReq
	(*UnstarPostResp)(nil),               // 6: interaction.UnstarPostResp
	(*CheckPostStarReq)(nil),             // 7: interaction.CheckPostStarReq
	(*CheckPostStarResp)(nil),            // 8: interaction.CheckPostStarResp
	(*BatchCheckPostStarReq)(nil),        // 9: interaction.BatchCheckPostStarReq
	(*BatchCheckPostStarResp)(nil),       // 10: interaction.BatchCheckPostStarResp
	(*CollectPostReq)(nil),               // 11: interaction.CollectPostReq
	(*CollectPostResp)(nil),              // 12: interaction.CollectPostResp
	(*UncollectPostReq)(nil),             // 13: interaction.UncollectPostReq
	(*UncollectPostResp)(nil),            // 14: interaction.UncollectPostResp
	(*CheckPostCollectionReq)(nil),       // 15: interaction.CheckPostCollectionReq
	(*CheckPostCollectionResp)(nil),      // 16: interaction.CheckPostCollectionResp
	(*BatchCheckPostCollectionReq)(nil),  // 17: interaction.BatchCheckPostCollectionReq
	(*BatchCheckPostCollectionResp)(nil), // 18: interaction.BatchCheckPostCollectionResp
	(*SharePostReq)(nil),                 // 19: interaction.SharePostReq
	(*SharePostResp)(nil),                // 20: interaction.SharePostResp
	nil,                                  // 21: interaction.BatchCheckPostStarResp.StarStatusEntry
	nil,                                  // 22: interaction.BatchCheckPostCollectionResp.CollectionStatusEntry
}
var file_interaction_proto_depIdxs = []int32{
	21, // 0: interaction.BatchCheckPostStarResp.starStatus:type_name -> interaction.BatchCheckPostStarResp.StarStatusEntry
	22, // 1: interaction.BatchCheckPostCollectionResp.collectionStatus:type_name -> interaction.BatchCheckPostCollectionResp.CollectionStatusEntry
	3,  // 2: interaction.InteractionCenter.StarPost:input_type -> interaction.StarPostReq
	5,  // 3: interaction.InteractionCenter.UnstarPost:input_type -> interaction.UnstarPostReq
	7,  // 4: interaction.InteractionCenter.CheckPostStar:input_type -> interaction.CheckPostStarReq
	9,  // 5: interaction.InteractionCenter.BatchCheckPostStar:input_type -> interaction.BatchCheckPostStarReq
	11, // 6: interaction.InteractionCenter.CollectPost:input_type -> interaction.CollectPostReq
	13, // 7: interaction.InteractionCenter.UncollectPost:input_type -> interaction.UncollectPostReq
	15, // 8: interaction.InteractionCenter.CheckPostCollection:input_type -> interaction.CheckPostCollectionReq
	17, // 9: interaction.InteractionCenter.BatchCheckPostCollection:input_type -> interaction.BatchCheckPostCollectionReq
	19, // 10: interaction.InteractionCenter.SharePost:input_type -> interaction.SharePostReq
	4,  // 11: interaction.InteractionCenter.StarPost:output_type -> interaction.StarPostResp
	6,  // 12: interaction.InteractionCenter.UnstarPost:output_type -> interaction.UnstarPostResp
	8,  // 13: interaction.InteractionCenter.CheckPostStar:output_type -> interaction.CheckPostStarResp
	10, // 14: interaction.InteractionCenter.BatchCheckPostStar:output_type -> interaction.BatchCheckPostStarResp
	12, // 15: interaction.InteractionCenter.CollectPost:output_type -> interaction.CollectPostResp
	14, // 16: interaction.InteractionCenter.UncollectPost:output_type -> interaction.UncollectPostResp
	16, // 17: interaction.InteractionCenter.CheckPostCollection:output_type -> interaction.CheckPostCollectionResp
	18, // 18: interaction.InteractionCenter.BatchCheckPostCollection:output_type -> interaction.BatchCheckPostCollectionResp
	20, // 19: interaction.InteractionCenter.SharePost:output_type -> interaction.SharePostResp
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_interaction_proto_init() }
func file_interaction_proto_init() {
	if File_interaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interaction_proto_rawDesc), len(file_interaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interaction_proto_goTypes,
		DependencyIndexes: file_interaction_proto_depIdxs,
		EnumInfos:         file_interaction_proto_enumTypes,
		MessageInfos:      file_interaction_proto_msgTypes,
	}.Build()
	File_interaction_proto = out.File
	file_interaction_proto_goTypes = nil
	file_interaction_proto_depIdxs = nil
}
