// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: interaction.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InteractionCenter_StarPost_FullMethodName                 = "/interaction.InteractionCenter/StarPost"
	InteractionCenter_UnstarPost_FullMethodName               = "/interaction.InteractionCenter/UnstarPost"
	InteractionCenter_CheckPostStar_FullMethodName            = "/interaction.InteractionCenter/CheckPostStar"
	InteractionCenter_BatchCheckPostStar_FullMethodName       = "/interaction.InteractionCenter/BatchCheckPostStar"
	InteractionCenter_CollectPost_FullMethodName              = "/interaction.InteractionCenter/CollectPost"
	InteractionCenter_UncollectPost_FullMethodName            = "/interaction.InteractionCenter/UncollectPost"
	InteractionCenter_CheckPostCollection_FullMethodName      = "/interaction.InteractionCenter/CheckPostCollection"
	InteractionCenter_BatchCheckPostCollection_FullMethodName = "/interaction.InteractionCenter/BatchCheckPostCollection"
	InteractionCenter_SharePost_FullMethodName                = "/interaction.InteractionCenter/SharePost"
)

// InteractionCenterClient is the client API for InteractionCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC服务定义
type InteractionCenterClient interface {
	// 动态点赞
	StarPost(ctx context.Context, in *StarPostReq, opts ...grpc.CallOption) (*StarPostResp, error)
	// 动态取消点赞
	UnstarPost(ctx context.Context, in *UnstarPostReq, opts ...grpc.CallOption) (*UnstarPostResp, error)
	// 检查动态点赞状态
	CheckPostStar(ctx context.Context, in *CheckPostStarReq, opts ...grpc.CallOption) (*CheckPostStarResp, error)
	// 批量检查动态点赞状态
	BatchCheckPostStar(ctx context.Context, in *BatchCheckPostStarReq, opts ...grpc.CallOption) (*BatchCheckPostStarResp, error)
	// 动态收藏
	CollectPost(ctx context.Context, in *CollectPostReq, opts ...grpc.CallOption) (*CollectPostResp, error)
	// 动态取消收藏
	UncollectPost(ctx context.Context, in *UncollectPostReq, opts ...grpc.CallOption) (*UncollectPostResp, error)
	// 检查动态收藏状态
	CheckPostCollection(ctx context.Context, in *CheckPostCollectionReq, opts ...grpc.CallOption) (*CheckPostCollectionResp, error)
	// 批量检查动态收藏状态
	BatchCheckPostCollection(ctx context.Context, in *BatchCheckPostCollectionReq, opts ...grpc.CallOption) (*BatchCheckPostCollectionResp, error)
	// 动态分享
	SharePost(ctx context.Context, in *SharePostReq, opts ...grpc.CallOption) (*SharePostResp, error)
}

type interactionCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewInteractionCenterClient(cc grpc.ClientConnInterface) InteractionCenterClient {
	return &interactionCenterClient{cc}
}

func (c *interactionCenterClient) StarPost(ctx context.Context, in *StarPostReq, opts ...grpc.CallOption) (*StarPostResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StarPostResp)
	err := c.cc.Invoke(ctx, InteractionCenter_StarPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionCenterClient) UnstarPost(ctx context.Context, in *UnstarPostReq, opts ...grpc.CallOption) (*UnstarPostResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnstarPostResp)
	err := c.cc.Invoke(ctx, InteractionCenter_UnstarPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionCenterClient) CheckPostStar(ctx context.Context, in *CheckPostStarReq, opts ...grpc.CallOption) (*CheckPostStarResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPostStarResp)
	err := c.cc.Invoke(ctx, InteractionCenter_CheckPostStar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionCenterClient) BatchCheckPostStar(ctx context.Context, in *BatchCheckPostStarReq, opts ...grpc.CallOption) (*BatchCheckPostStarResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCheckPostStarResp)
	err := c.cc.Invoke(ctx, InteractionCenter_BatchCheckPostStar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionCenterClient) CollectPost(ctx context.Context, in *CollectPostReq, opts ...grpc.CallOption) (*CollectPostResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectPostResp)
	err := c.cc.Invoke(ctx, InteractionCenter_CollectPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionCenterClient) UncollectPost(ctx context.Context, in *UncollectPostReq, opts ...grpc.CallOption) (*UncollectPostResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UncollectPostResp)
	err := c.cc.Invoke(ctx, InteractionCenter_UncollectPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionCenterClient) CheckPostCollection(ctx context.Context, in *CheckPostCollectionReq, opts ...grpc.CallOption) (*CheckPostCollectionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPostCollectionResp)
	err := c.cc.Invoke(ctx, InteractionCenter_CheckPostCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionCenterClient) BatchCheckPostCollection(ctx context.Context, in *BatchCheckPostCollectionReq, opts ...grpc.CallOption) (*BatchCheckPostCollectionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCheckPostCollectionResp)
	err := c.cc.Invoke(ctx, InteractionCenter_BatchCheckPostCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionCenterClient) SharePost(ctx context.Context, in *SharePostReq, opts ...grpc.CallOption) (*SharePostResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SharePostResp)
	err := c.cc.Invoke(ctx, InteractionCenter_SharePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteractionCenterServer is the server API for InteractionCenter service.
// All implementations must embed UnimplementedInteractionCenterServer
// for forward compatibility.
//
// gRPC服务定义
type InteractionCenterServer interface {
	// 动态点赞
	StarPost(context.Context, *StarPostReq) (*StarPostResp, error)
	// 动态取消点赞
	UnstarPost(context.Context, *UnstarPostReq) (*UnstarPostResp, error)
	// 检查动态点赞状态
	CheckPostStar(context.Context, *CheckPostStarReq) (*CheckPostStarResp, error)
	// 批量检查动态点赞状态
	BatchCheckPostStar(context.Context, *BatchCheckPostStarReq) (*BatchCheckPostStarResp, error)
	// 动态收藏
	CollectPost(context.Context, *CollectPostReq) (*CollectPostResp, error)
	// 动态取消收藏
	UncollectPost(context.Context, *UncollectPostReq) (*UncollectPostResp, error)
	// 检查动态收藏状态
	CheckPostCollection(context.Context, *CheckPostCollectionReq) (*CheckPostCollectionResp, error)
	// 批量检查动态收藏状态
	BatchCheckPostCollection(context.Context, *BatchCheckPostCollectionReq) (*BatchCheckPostCollectionResp, error)
	// 动态分享
	SharePost(context.Context, *SharePostReq) (*SharePostResp, error)
	mustEmbedUnimplementedInteractionCenterServer()
}

// UnimplementedInteractionCenterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInteractionCenterServer struct{}

func (UnimplementedInteractionCenterServer) StarPost(context.Context, *StarPostReq) (*StarPostResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StarPost not implemented")
}
func (UnimplementedInteractionCenterServer) UnstarPost(context.Context, *UnstarPostReq) (*UnstarPostResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnstarPost not implemented")
}
func (UnimplementedInteractionCenterServer) CheckPostStar(context.Context, *CheckPostStarReq) (*CheckPostStarResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPostStar not implemented")
}
func (UnimplementedInteractionCenterServer) BatchCheckPostStar(context.Context, *BatchCheckPostStarReq) (*BatchCheckPostStarResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchCheckPostStar not implemented")
}
func (UnimplementedInteractionCenterServer) CollectPost(context.Context, *CollectPostReq) (*CollectPostResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectPost not implemented")
}
func (UnimplementedInteractionCenterServer) UncollectPost(context.Context, *UncollectPostReq) (*UncollectPostResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UncollectPost not implemented")
}
func (UnimplementedInteractionCenterServer) CheckPostCollection(context.Context, *CheckPostCollectionReq) (*CheckPostCollectionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPostCollection not implemented")
}
func (UnimplementedInteractionCenterServer) BatchCheckPostCollection(context.Context, *BatchCheckPostCollectionReq) (*BatchCheckPostCollectionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchCheckPostCollection not implemented")
}
func (UnimplementedInteractionCenterServer) SharePost(context.Context, *SharePostReq) (*SharePostResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SharePost not implemented")
}
func (UnimplementedInteractionCenterServer) mustEmbedUnimplementedInteractionCenterServer() {}
func (UnimplementedInteractionCenterServer) testEmbeddedByValue()                           {}

// UnsafeInteractionCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InteractionCenterServer will
// result in compilation errors.
type UnsafeInteractionCenterServer interface {
	mustEmbedUnimplementedInteractionCenterServer()
}

func RegisterInteractionCenterServer(s grpc.ServiceRegistrar, srv InteractionCenterServer) {
	// If the following call pancis, it indicates UnimplementedInteractionCenterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InteractionCenter_ServiceDesc, srv)
}

func _InteractionCenter_StarPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarPostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionCenterServer).StarPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionCenter_StarPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionCenterServer).StarPost(ctx, req.(*StarPostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionCenter_UnstarPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnstarPostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionCenterServer).UnstarPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionCenter_UnstarPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionCenterServer).UnstarPost(ctx, req.(*UnstarPostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionCenter_CheckPostStar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPostStarReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionCenterServer).CheckPostStar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionCenter_CheckPostStar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionCenterServer).CheckPostStar(ctx, req.(*CheckPostStarReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionCenter_BatchCheckPostStar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCheckPostStarReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionCenterServer).BatchCheckPostStar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionCenter_BatchCheckPostStar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionCenterServer).BatchCheckPostStar(ctx, req.(*BatchCheckPostStarReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionCenter_CollectPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectPostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionCenterServer).CollectPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionCenter_CollectPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionCenterServer).CollectPost(ctx, req.(*CollectPostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionCenter_UncollectPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UncollectPostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionCenterServer).UncollectPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionCenter_UncollectPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionCenterServer).UncollectPost(ctx, req.(*UncollectPostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionCenter_CheckPostCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPostCollectionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionCenterServer).CheckPostCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionCenter_CheckPostCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionCenterServer).CheckPostCollection(ctx, req.(*CheckPostCollectionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionCenter_BatchCheckPostCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCheckPostCollectionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionCenterServer).BatchCheckPostCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionCenter_BatchCheckPostCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionCenterServer).BatchCheckPostCollection(ctx, req.(*BatchCheckPostCollectionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionCenter_SharePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SharePostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionCenterServer).SharePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionCenter_SharePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionCenterServer).SharePost(ctx, req.(*SharePostReq))
	}
	return interceptor(ctx, in, info, handler)
}

// InteractionCenter_ServiceDesc is the grpc.ServiceDesc for InteractionCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InteractionCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interaction.InteractionCenter",
	HandlerType: (*InteractionCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StarPost",
			Handler:    _InteractionCenter_StarPost_Handler,
		},
		{
			MethodName: "UnstarPost",
			Handler:    _InteractionCenter_UnstarPost_Handler,
		},
		{
			MethodName: "CheckPostStar",
			Handler:    _InteractionCenter_CheckPostStar_Handler,
		},
		{
			MethodName: "BatchCheckPostStar",
			Handler:    _InteractionCenter_BatchCheckPostStar_Handler,
		},
		{
			MethodName: "CollectPost",
			Handler:    _InteractionCenter_CollectPost_Handler,
		},
		{
			MethodName: "UncollectPost",
			Handler:    _InteractionCenter_UncollectPost_Handler,
		},
		{
			MethodName: "CheckPostCollection",
			Handler:    _InteractionCenter_CheckPostCollection_Handler,
		},
		{
			MethodName: "BatchCheckPostCollection",
			Handler:    _InteractionCenter_BatchCheckPostCollection_Handler,
		},
		{
			MethodName: "SharePost",
			Handler:    _InteractionCenter_SharePost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interaction.proto",
}
