// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: content.proto

package contentcenter

import (
	"context"

	"SChill/service/content/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetPostReq   = pb.BatchGetPostReq
	BatchGetPostResp  = pb.BatchGetPostResp
	CreatePostReq     = pb.CreatePostReq
	CreatePostResp    = pb.CreatePostResp
	DeletePostReq     = pb.DeletePostReq
	DeletePostResp    = pb.DeletePostResp
	GetPostDetailReq  = pb.GetPostDetailReq
	GetPostDetailResp = pb.GetPostDetailResp
	GetPostListReq    = pb.GetPostListReq
	GetPostListResp   = pb.GetPostListResp
	IncViewCountReq   = pb.IncViewCountReq
	IncViewCountResp  = pb.IncViewCountResp
	PostContentItem   = pb.PostContentItem
	PostInfo          = pb.PostInfo
	PostTopic         = pb.PostTopic
	UpdatePostReq     = pb.UpdatePostReq
	UpdatePostResp    = pb.UpdatePostResp

	ContentCenter interface {
		CreatePost(ctx context.Context, in *CreatePostReq, opts ...grpc.CallOption) (*CreatePostResp, error)
		UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*UpdatePostResp, error)
		DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*DeletePostResp, error)
		GetPostDetail(ctx context.Context, in *GetPostDetailReq, opts ...grpc.CallOption) (*GetPostDetailResp, error)
		GetPostList(ctx context.Context, in *GetPostListReq, opts ...grpc.CallOption) (*GetPostListResp, error)
		BatchGetPost(ctx context.Context, in *BatchGetPostReq, opts ...grpc.CallOption) (*BatchGetPostResp, error)
		IncViewCount(ctx context.Context, in *IncViewCountReq, opts ...grpc.CallOption) (*IncViewCountResp, error)
	}

	defaultContentCenter struct {
		cli zrpc.Client
	}
)

func NewContentCenter(cli zrpc.Client) ContentCenter {
	return &defaultContentCenter{
		cli: cli,
	}
}

func (m *defaultContentCenter) CreatePost(ctx context.Context, in *CreatePostReq, opts ...grpc.CallOption) (*CreatePostResp, error) {
	client := pb.NewContentCenterClient(m.cli.Conn())
	return client.CreatePost(ctx, in, opts...)
}

func (m *defaultContentCenter) UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*UpdatePostResp, error) {
	client := pb.NewContentCenterClient(m.cli.Conn())
	return client.UpdatePost(ctx, in, opts...)
}

func (m *defaultContentCenter) DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*DeletePostResp, error) {
	client := pb.NewContentCenterClient(m.cli.Conn())
	return client.DeletePost(ctx, in, opts...)
}

func (m *defaultContentCenter) GetPostDetail(ctx context.Context, in *GetPostDetailReq, opts ...grpc.CallOption) (*GetPostDetailResp, error) {
	client := pb.NewContentCenterClient(m.cli.Conn())
	return client.GetPostDetail(ctx, in, opts...)
}

func (m *defaultContentCenter) GetPostList(ctx context.Context, in *GetPostListReq, opts ...grpc.CallOption) (*GetPostListResp, error) {
	client := pb.NewContentCenterClient(m.cli.Conn())
	return client.GetPostList(ctx, in, opts...)
}

func (m *defaultContentCenter) BatchGetPost(ctx context.Context, in *BatchGetPostReq, opts ...grpc.CallOption) (*BatchGetPostResp, error) {
	client := pb.NewContentCenterClient(m.cli.Conn())
	return client.BatchGetPost(ctx, in, opts...)
}

func (m *defaultContentCenter) IncViewCount(ctx context.Context, in *IncViewCountReq, opts ...grpc.CallOption) (*IncViewCountResp, error) {
	client := pb.NewContentCenterClient(m.cli.Conn())
	return client.IncViewCount(ctx, in, opts...)
}
