// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: content.proto

package contentcenter

import (
	"context"

	"SChill/service/content/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetPostReq         = pb.BatchGetPostReq
	BatchGetPostResp        = pb.BatchGetPostResp
	BatchGetPostSummaryReq  = pb.BatchGetPostSummaryReq
	BatchGetPostSummaryResp = pb.BatchGetPostSummaryResp
	CreatePostReq           = pb.CreatePostReq
	CreatePostResp          = pb.CreatePostResp
	DeletePostReq           = pb.DeletePostReq
	DeletePostResp          = pb.DeletePostResp
	GetPostDetailReq        = pb.GetPostDetailReq
	GetPostDetailResp       = pb.GetPostDetailResp
	GetPostListReq          = pb.GetPostListReq
	GetPostListResp         = pb.GetPostListResp
	GetTopicListReq         = pb.GetTopicListReq
	GetTopicListResp        = pb.GetTopicListResp
	IncViewCountReq         = pb.IncViewCountReq
	IncViewCountResp        = pb.IncViewCountResp
	PostContentItem         = pb.PostContentItem
	PostInfo                = pb.PostInfo
	PostSummary             = pb.PostSummary
	PostTopic               = pb.PostTopic
	SetEssencePostReq       = pb.SetEssencePostReq
	SetEssencePostResp      = pb.SetEssencePostResp
	SetTopPostReq           = pb.SetTopPostReq
	SetTopPostResp          = pb.SetTopPostResp
	TopicInfo               = pb.TopicInfo
	UpdatePostReq           = pb.UpdatePostReq
	UpdatePostResp          = pb.UpdatePostResp

	ContentCenter interface {
		CreatePost(ctx context.Context, in *CreatePostReq, opts ...grpc.CallOption) (*CreatePostResp, error)
		UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*UpdatePostResp, error)
		DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*DeletePostResp, error)
		GetPostDetail(ctx context.Context, in *GetPostDetailReq, opts ...grpc.CallOption) (*GetPostDetailResp, error)
		GetPostList(ctx context.Context, in *GetPostListReq, opts ...grpc.CallOption) (*GetPostListResp, error)
		BatchGetPost(ctx context.Context, in *BatchGetPostReq, opts ...grpc.CallOption) (*BatchGetPostResp, error)
		BatchGetPostSummary(ctx context.Context, in *BatchGetPostSummaryReq, opts ...grpc.CallOption) (*BatchGetPostSummaryResp, error)
		IncViewCount(ctx context.Context, in *IncViewCountReq, opts ...grpc.CallOption) (*IncViewCountResp, error)
		GetTopicList(ctx context.Context, in *GetTopicListReq, opts ...grpc.CallOption) (*GetTopicListResp, error)
		SetTopPost(ctx context.Context, in *SetTopPostReq, opts ...grpc.CallOption) (*SetTopPostResp, error)
		SetEssencePost(ctx context.Context, in *SetEssencePostReq, opts ...grpc.CallOption) (*SetEssencePostResp, error)
	}

	defaultContentCenter struct {
		cli zrpc.Client
	}
)

func NewContentCenter(cli zrpc.Client) ContentCenter {
	return &defaultContentCenter{
		cli: cli,
	}
}

func (m *defaultContentCenter) CreatePost(ctx context.Context, in *CreatePostReq, opts ...grpc.CallOption) (*CreatePostResp, error) {
	client := pb.NewContentCenterClient(m.cli.Conn())
	return client.CreatePost(ctx, in, opts...)
}

func (m *defaultContentCenter) UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*UpdatePostResp, error) {
	client := pb.NewContentCenterClient(m.cli.Conn())
	return client.UpdatePost(ctx, in, opts...)
}

func (m *defaultContentCenter) DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*DeletePostResp, error) {
	client := pb.NewContentCenterClient(m.cli.Conn())
	return client.DeletePost(ctx, in, opts...)
}

func (m *defaultContentCenter) GetPostDetail(ctx context.Context, in *GetPostDetailReq, opts ...grpc.CallOption) (*GetPostDetailResp, error) {
	client := pb.NewContentCenterClient(m.cli.Conn())
	return client.GetPostDetail(ctx, in, opts...)
}

func (m *defaultContentCenter) GetPostList(ctx context.Context, in *GetPostListReq, opts ...grpc.CallOption) (*GetPostListResp, error) {
	client := pb.NewContentCenterClient(m.cli.Conn())
	return client.GetPostList(ctx, in, opts...)
}

func (m *defaultContentCenter) BatchGetPost(ctx context.Context, in *BatchGetPostReq, opts ...grpc.CallOption) (*BatchGetPostResp, error) {
	client := pb.NewContentCenterClient(m.cli.Conn())
	return client.BatchGetPost(ctx, in, opts...)
}

func (m *defaultContentCenter) BatchGetPostSummary(ctx context.Context, in *BatchGetPostSummaryReq, opts ...grpc.CallOption) (*BatchGetPostSummaryResp, error) {
	client := pb.NewContentCenterClient(m.cli.Conn())
	return client.BatchGetPostSummary(ctx, in, opts...)
}

func (m *defaultContentCenter) IncViewCount(ctx context.Context, in *IncViewCountReq, opts ...grpc.CallOption) (*IncViewCountResp, error) {
	client := pb.NewContentCenterClient(m.cli.Conn())
	return client.IncViewCount(ctx, in, opts...)
}

func (m *defaultContentCenter) GetTopicList(ctx context.Context, in *GetTopicListReq, opts ...grpc.CallOption) (*GetTopicListResp, error) {
	client := pb.NewContentCenterClient(m.cli.Conn())
	return client.GetTopicList(ctx, in, opts...)
}

func (m *defaultContentCenter) SetTopPost(ctx context.Context, in *SetTopPostReq, opts ...grpc.CallOption) (*SetTopPostResp, error) {
	client := pb.NewContentCenterClient(m.cli.Conn())
	return client.SetTopPost(ctx, in, opts...)
}

func (m *defaultContentCenter) SetEssencePost(ctx context.Context, in *SetEssencePostReq, opts ...grpc.CallOption) (*SetEssencePostResp, error) {
	client := pb.NewContentCenterClient(m.cli.Conn())
	return client.SetEssencePost(ctx, in, opts...)
}
