// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: feed.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFeedListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedType      string                 `protobuf:"bytes,1,opt,name=feedType,proto3" json:"feedType,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	CurrentUserId uint64                 `protobuf:"varint,4,opt,name=currentUserId,proto3" json:"currentUserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedListReq) Reset() {
	*x = GetFeedListReq{}
	mi := &file_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedListReq) ProtoMessage() {}

func (x *GetFeedListReq) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedListReq.ProtoReflect.Descriptor instead.
func (*GetFeedListReq) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{0}
}

func (x *GetFeedListReq) GetFeedType() string {
	if x != nil {
		return x.FeedType
	}
	return ""
}

func (x *GetFeedListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetFeedListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetFeedListReq) GetCurrentUserId() uint64 {
	if x != nil {
		return x.CurrentUserId
	}
	return 0
}

type FeedAuthor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedAuthor) Reset() {
	*x = FeedAuthor{}
	mi := &file_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedAuthor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedAuthor) ProtoMessage() {}

func (x *FeedAuthor) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedAuthor.ProtoReflect.Descriptor instead.
func (*FeedAuthor) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{1}
}

func (x *FeedAuthor) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FeedAuthor) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FeedAuthor) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *FeedAuthor) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type FeedViewerState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsStarred         bool                   `protobuf:"varint,1,opt,name=isStarred,proto3" json:"isStarred,omitempty"`
	IsCollected       bool                   `protobuf:"varint,2,opt,name=isCollected,proto3" json:"isCollected,omitempty"`
	IsFollowingAuthor bool                   `protobuf:"varint,3,opt,name=isFollowingAuthor,proto3" json:"isFollowingAuthor,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FeedViewerState) Reset() {
	*x = FeedViewerState{}
	mi := &file_feed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedViewerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedViewerState) ProtoMessage() {}

func (x *FeedViewerState) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedViewerState.ProtoReflect.Descriptor instead.
func (*FeedViewerState) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{2}
}

func (x *FeedViewerState) GetIsStarred() bool {
	if x != nil {
		return x.IsStarred
	}
	return false
}

func (x *FeedViewerState) GetIsCollected() bool {
	if x != nil {
		return x.IsCollected
	}
	return false
}

func (x *FeedViewerState) GetIsFollowingAuthor() bool {
	if x != nil {
		return x.IsFollowingAuthor
	}
	return false
}

type FeedItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PostId          uint64                 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	AuthorId        uint64                 `protobuf:"varint,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Summary         string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Cover           string                 `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	Tags            []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Visibility      int32                  `protobuf:"varint,7,opt,name=visibility,proto3" json:"visibility,omitempty"`
	IsTop           bool                   `protobuf:"varint,8,opt,name=isTop,proto3" json:"isTop,omitempty"`
	IsEssence       bool                   `protobuf:"varint,9,opt,name=isEssence,proto3" json:"isEssence,omitempty"`
	IsLock          bool                   `protobuf:"varint,10,opt,name=isLock,proto3" json:"isLock,omitempty"`
	CommentCount    uint64                 `protobuf:"varint,11,opt,name=commentCount,proto3" json:"commentCount,omitempty"`
	UpvoteCount     uint64                 `protobuf:"varint,12,opt,name=upvoteCount,proto3" json:"upvoteCount,omitempty"`
	CollectionCount uint64                 `protobuf:"varint,13,opt,name=collectionCount,proto3" json:"collectionCount,omitempty"`
	ShareCount      uint64                 `protobuf:"varint,14,opt,name=shareCount,proto3" json:"shareCount,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,15,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,16,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	LatestRepliedAt int64                  `protobuf:"varint,17,opt,name=latestRepliedAt,proto3" json:"latestRepliedAt,omitempty"`
	FeedType        string                 `protobuf:"bytes,18,opt,name=feedType,proto3" json:"feedType,omitempty"`
	Source          string                 `protobuf:"bytes,19,opt,name=source,proto3" json:"source,omitempty"`
	Author          *FeedAuthor            `protobuf:"bytes,20,opt,name=author,proto3" json:"author,omitempty"`
	ViewerState     *FeedViewerState       `protobuf:"bytes,21,opt,name=viewerState,proto3" json:"viewerState,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FeedItem) Reset() {
	*x = FeedItem{}
	mi := &file_feed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedItem) ProtoMessage() {}

func (x *FeedItem) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedItem.ProtoReflect.Descriptor instead.
func (*FeedItem) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{3}
}

func (x *FeedItem) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *FeedItem) GetAuthorId() uint64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *FeedItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FeedItem) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *FeedItem) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *FeedItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FeedItem) GetVisibility() int32 {
	if x != nil {
		return x.Visibility
	}
	return 0
}

func (x *FeedItem) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

func (x *FeedItem) GetIsEssence() bool {
	if x != nil {
		return x.IsEssence
	}
	return false
}

func (x *FeedItem) GetIsLock() bool {
	if x != nil {
		return x.IsLock
	}
	return false
}

func (x *FeedItem) GetCommentCount() uint64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *FeedItem) GetUpvoteCount() uint64 {
	if x != nil {
		return x.UpvoteCount
	}
	return 0
}

func (x *FeedItem) GetCollectionCount() uint64 {
	if x != nil {
		return x.CollectionCount
	}
	return 0
}

func (x *FeedItem) GetShareCount() uint64 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

func (x *FeedItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FeedItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *FeedItem) GetLatestRepliedAt() int64 {
	if x != nil {
		return x.LatestRepliedAt
	}
	return 0
}

func (x *FeedItem) GetFeedType() string {
	if x != nil {
		return x.FeedType
	}
	return ""
}

func (x *FeedItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FeedItem) GetAuthor() *FeedAuthor {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *FeedItem) GetViewerState() *FeedViewerState {
	if x != nil {
		return x.ViewerState
	}
	return nil
}

type GetFeedListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	List          []*FeedItem            `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedListResp) Reset() {
	*x = GetFeedListResp{}
	mi := &file_feed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedListResp) ProtoMessage() {}

func (x *GetFeedListResp) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedListResp.ProtoReflect.Descriptor instead.
func (*GetFeedListResp) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{4}
}

func (x *GetFeedListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetFeedListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetFeedListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetFeedListResp) GetList() []*FeedItem {
	if x != nil {
		return x.List
	}
	return nil
}

var File_feed_proto protoreflect.FileDescriptor

const file_feed_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"feed.proto\x12\x04feed\"\x82\x01\n" +
	"\x0eGetFeedListReq\x12\x1a\n" +
	"\bfeedType\x18\x01 \x01(\tR\bfeedType\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\x12$\n" +
	"\rcurrentUserId\x18\x04 \x01(\x04R\rcurrentUserId\"l\n" +
	"\n" +
	"FeedAuthor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\"\x7f\n" +
	"\x0fFeedViewerState\x12\x1c\n" +
	"\tisStarred\x18\x01 \x01(\bR\tisStarred\x12 \n" +
	"\visCollected\x18\x02 \x01(\bR\visCollected\x12,\n" +
	"\x11isFollowingAuthor\x18\x03 \x01(\bR\x11isFollowingAuthor\"\x91\x05\n" +
	"\bFeedItem\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x04R\x06postId\x12\x1a\n" +
	"\bauthorId\x18\x02 \x01(\x04R\bauthorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x14\n" +
	"\x05cover\x18\x05 \x01(\tR\x05cover\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1e\n" +
	"\n" +
	"visibility\x18\a \x01(\x05R\n" +
	"visibility\x12\x14\n" +
	"\x05isTop\x18\b \x01(\bR\x05isTop\x12\x1c\n" +
	"\tisEssence\x18\t \x01(\bR\tisEssence\x12\x16\n" +
	"\x06isLock\x18\n" +
	" \x01(\bR\x06isLock\x12\"\n" +
	"\fcommentCount\x18\v \x01(\x04R\fcommentCount\x12 \n" +
	"\vupvoteCount\x18\f \x01(\x04R\vupvoteCount\x12(\n" +
	"\x0fcollectionCount\x18\r \x01(\x04R\x0fcollectionCount\x12\x1e\n" +
	"\n" +
	"shareCount\x18\x0e \x01(\x04R\n" +
	"shareCount\x12\x1c\n" +
	"\tcreatedAt\x18\x0f \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x10 \x01(\x03R\tupdatedAt\x12(\n" +
	"\x0flatestRepliedAt\x18\x11 \x01(\x03R\x0flatestRepliedAt\x12\x1a\n" +
	"\bfeedType\x18\x12 \x01(\tR\bfeedType\x12\x16\n" +
	"\x06source\x18\x13 \x01(\tR\x06source\x12(\n" +
	"\x06author\x18\x14 \x01(\v2\x10.feed.FeedAuthorR\x06author\x127\n" +
	"\vviewerState\x18\x15 \x01(\v2\x15.feed.FeedViewerStateR\vviewerState\"q\n" +
	"\x0fGetFeedListResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12\"\n" +
	"\x04list\x18\x04 \x03(\v2\x0e.feed.FeedItemR\x04list2H\n" +
	"\n" +
	"FeedCenter\x12:\n" +
	"\vGetFeedList\x12\x14.feed.GetFeedListReq\x1a\x15.feed.GetFeedListRespB\x05Z\x03/pbb\x06proto3"

var (
	file_feed_proto_rawDescOnce sync.Once
	file_feed_proto_rawDescData []byte
)

func file_feed_proto_rawDescGZIP() []byte {
	file_feed_proto_rawDescOnce.Do(func() {
		file_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feed_proto_rawDesc), len(file_feed_proto_rawDesc)))
	})
	return file_feed_proto_rawDescData
}

var file_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_feed_proto_goTypes = []any{
	(*GetFeedListReq)(nil),  // 0: feed.GetFeedListReq
	(*FeedAuthor)(nil),      // 1: feed.FeedAuthor
	(*FeedViewerState)(nil), // 2: feed.FeedViewerState
	(*FeedItem)(nil),        // 3: feed.FeedItem
	(*GetFeedListResp)(nil), // 4: feed.GetFeedListResp
}
var file_feed_proto_depIdxs = []int32{
	1, // 0: feed.FeedItem.author:type_name -> feed.FeedAuthor
	2, // 1: feed.FeedItem.viewerState:type_name -> feed.FeedViewerState
	3, // 2: feed.GetFeedListResp.list:type_name -> feed.FeedItem
	0, // 3: feed.FeedCenter.GetFeedList:input_type -> feed.GetFeedListReq
	4, // 4: feed.FeedCenter.GetFeedList:output_type -> feed.GetFeedListResp
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_feed_proto_init() }
func file_feed_proto_init() {
	if File_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feed_proto_rawDesc), len(file_feed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feed_proto_goTypes,
		DependencyIndexes: file_feed_proto_depIdxs,
		MessageInfos:      file_feed_proto_msgTypes,
	}.Build()
	File_feed_proto = out.File
	file_feed_proto_goTypes = nil
	file_feed_proto_depIdxs = nil
}
