// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.2
// source: feed.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FeedCenter_GetFeedList_FullMethodName = "/feed.FeedCenter/GetFeedList"
)

// FeedCenterClient is the client API for FeedCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeedCenterClient interface {
	GetFeedList(ctx context.Context, in *GetFeedListReq, opts ...grpc.CallOption) (*GetFeedListResp, error)
}

type feedCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewFeedCenterClient(cc grpc.ClientConnInterface) FeedCenterClient {
	return &feedCenterClient{cc}
}

func (c *feedCenterClient) GetFeedList(ctx context.Context, in *GetFeedListReq, opts ...grpc.CallOption) (*GetFeedListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeedListResp)
	err := c.cc.Invoke(ctx, FeedCenter_GetFeedList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedCenterServer is the server API for FeedCenter service.
// All implementations must embed UnimplementedFeedCenterServer
// for forward compatibility.
type FeedCenterServer interface {
	GetFeedList(context.Context, *GetFeedListReq) (*GetFeedListResp, error)
	mustEmbedUnimplementedFeedCenterServer()
}

// UnimplementedFeedCenterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeedCenterServer struct{}

func (UnimplementedFeedCenterServer) GetFeedList(context.Context, *GetFeedListReq) (*GetFeedListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeedList not implemented")
}
func (UnimplementedFeedCenterServer) mustEmbedUnimplementedFeedCenterServer() {}
func (UnimplementedFeedCenterServer) testEmbeddedByValue()                    {}

// UnsafeFeedCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeedCenterServer will
// result in compilation errors.
type UnsafeFeedCenterServer interface {
	mustEmbedUnimplementedFeedCenterServer()
}

func RegisterFeedCenterServer(s grpc.ServiceRegistrar, srv FeedCenterServer) {
	// If the following call panics, it indicates UnimplementedFeedCenterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FeedCenter_ServiceDesc, srv)
}

func _FeedCenter_GetFeedList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedCenterServer).GetFeedList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedCenter_GetFeedList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedCenterServer).GetFeedList(ctx, req.(*GetFeedListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// FeedCenter_ServiceDesc is the grpc.ServiceDesc for FeedCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeedCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "feed.FeedCenter",
	HandlerType: (*FeedCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeedList",
			Handler:    _FeedCenter_GetFeedList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feed.proto",
}
