// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userProfileFieldNames          = builder.RawFieldNames(&UserProfile{})
	userProfileRows                = strings.Join(userProfileFieldNames, ",")
	userProfileRowsExpectAutoSet   = strings.Join(stringx.Remove(userProfileFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userProfileRowsWithPlaceHolder = strings.Join(stringx.Remove(userProfileFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userProfileModel interface {
		Insert(ctx context.Context, data *UserProfile) (sql.Result, error)
		FindOneByUserId(ctx context.Context, userId uint64) (*UserProfile, error)
		UpdateByUserId(ctx context.Context, data *UserProfile) error
		DeleteByUserId(ctx context.Context, userId uint64) error
	}

	defaultUserProfileModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserProfile struct {
		UserId    uint64       `db:"user_id"`
		Gender    int64        `db:"gender"`    // 性别：0未知，1男，2女
		Birthday  sql.NullTime `db:"birthday"`  // 生日
		Signature string       `db:"signature"` // 个性签名
		Location  string       `db:"location"`  // 所在地
		Website   string       `db:"website"`   // 个人网站
		Company   string       `db:"company"`   // 公司
		JobTitle  string       `db:"job_title"` // 职位
		Education string       `db:"education"` // 教育背景
		CreatedAt time.Time    `db:"created_at"`
		UpdatedAt time.Time    `db:"updated_at"`
	}
)

func newUserProfileModel(conn sqlx.SqlConn) *defaultUserProfileModel {
	return &defaultUserProfileModel{
		conn:  conn,
		table: "`user_profile`",
	}
}

func (m *defaultUserProfileModel) DeleteByUserId(ctx context.Context, userId uint64) error {
	query := fmt.Sprintf("delete from %s where `user_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, userId)
	return err
}


func (m *defaultUserProfileModel) FindOneByUserId(ctx context.Context, userId uint64) (*UserProfile, error) {
	var resp UserProfile
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", userProfileRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserProfileModel) Insert(ctx context.Context, data *UserProfile) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userProfileRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Gender, data.Birthday, data.Signature, data.Location, data.Website, data.Company, data.JobTitle, data.Education)
	return ret, err
}

func (m *defaultUserProfileModel) UpdateByUserId(ctx context.Context, newData *UserProfile) error {
	query := fmt.Sprintf("update %s set %s where `user_id` = ?", m.table, userProfileRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query,newData.UserId,newData.Gender, newData.Birthday, newData.Signature, newData.Location, newData.Website, newData.Company, newData.JobTitle, newData.Education)
	return err
}

func (m *defaultUserProfileModel) tableName() string {
	return m.table
}
