// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userStatFieldNames          = builder.RawFieldNames(&UserStat{})
	userStatRows                = strings.Join(userStatFieldNames, ",")
	userStatRowsExpectAutoSet   = strings.Join(stringx.Remove(userStatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userStatRowsWithPlaceHolder = strings.Join(stringx.Remove(userStatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userStatModel interface {
		Insert(ctx context.Context, data *UserStat) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserStat, error)
		FindOneByUserId(ctx context.Context, userId uint64) (*UserStat, error)
		Update(ctx context.Context, data *UserStat) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserStatModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserStat struct {
		Id              uint64    `db:"id"`
		UserId          uint64    `db:"user_id"`          // 用户ID
		PostCount       uint64    `db:"post_count"`       // 发帖数
		CommentCount    uint64    `db:"comment_count"`    // 评论数
		FollowerCount   uint64    `db:"follower_count"`   // 粉丝数
		FollowingCount  uint64    `db:"following_count"`  // 关注数
		LikeCount       uint64    `db:"like_count"`       // 获赞总数
		CollectionCount uint64    `db:"collection_count"` // 被收藏总数
		LastActiveTime  int64     `db:"last_active_time"` // 最后活跃时间
		CreatedAt       time.Time `db:"created_at"`
		UpdatedAt       time.Time `db:"updated_at"`
	}
)

func newUserStatModel(conn sqlx.SqlConn) *defaultUserStatModel {
	return &defaultUserStatModel{
		conn:  conn,
		table: "`user_stat`",
	}
}

func (m *defaultUserStatModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserStatModel) FindOne(ctx context.Context, id uint64) (*UserStat, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userStatRows, m.table)
	var resp UserStat
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserStatModel) FindOneByUserId(ctx context.Context, userId uint64) (*UserStat, error) {
	var resp UserStat
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", userStatRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserStatModel) Insert(ctx context.Context, data *UserStat) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, userStatRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.PostCount, data.CommentCount, data.FollowerCount, data.FollowingCount, data.LikeCount, data.CollectionCount, data.LastActiveTime)
	return ret, err
}

func (m *defaultUserStatModel) Update(ctx context.Context, newData *UserStat) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userStatRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.PostCount, newData.CommentCount, newData.FollowerCount, newData.FollowingCount, newData.LikeCount, newData.CollectionCount, newData.LastActiveTime, newData.Id)
	return err
}

func (m *defaultUserStatModel) tableName() string {
	return m.table
}
