// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: relation.proto

package server

import (
	"context"

	"SChill/service/relation/rpc/internal/logic"
	"SChill/service/relation/rpc/internal/svc"
	"SChill/service/relation/rpc/pb"
)

type RelationCenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRelationCenterServer
}

func NewRelationCenterServer(svcCtx *svc.ServiceContext) *RelationCenterServer {
	return &RelationCenterServer{
		svcCtx: svcCtx,
	}
}

func (s *RelationCenterServer) Follow(ctx context.Context, in *pb.FollowReq) (*pb.FollowResp, error) {
	l := logic.NewFollowLogic(ctx, s.svcCtx)
	return l.Follow(in)
}

func (s *RelationCenterServer) Unfollow(ctx context.Context, in *pb.UnfollowReq) (*pb.UnfollowResp, error) {
	l := logic.NewUnfollowLogic(ctx, s.svcCtx)
	return l.Unfollow(in)
}

func (s *RelationCenterServer) CheckFollowStatus(ctx context.Context, in *pb.CheckFollowStatusReq) (*pb.CheckFollowStatusResp, error) {
	l := logic.NewCheckFollowStatusLogic(ctx, s.svcCtx)
	return l.CheckFollowStatus(in)
}

func (s *RelationCenterServer) GetFollowingList(ctx context.Context, in *pb.GetFollowingListReq) (*pb.GetFollowingListResp, error) {
	l := logic.NewGetFollowingListLogic(ctx, s.svcCtx)
	return l.GetFollowingList(in)
}

func (s *RelationCenterServer) GetFollowerList(ctx context.Context, in *pb.GetFollowerListReq) (*pb.GetFollowerListResp, error) {
	l := logic.NewGetFollowerListLogic(ctx, s.svcCtx)
	return l.GetFollowerList(in)
}

func (s *RelationCenterServer) BatchCheckFollowStatus(ctx context.Context, in *pb.BatchCheckFollowStatusReq) (*pb.BatchCheckFollowStatusResp, error) {
	l := logic.NewBatchCheckFollowStatusLogic(ctx, s.svcCtx)
	return l.BatchCheckFollowStatus(in)
}
