// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: comment.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommentCenter_CreateComment_FullMethodName  = "/comment.CommentCenter/CreateComment"
	CommentCenter_DeleteComment_FullMethodName  = "/comment.CommentCenter/DeleteComment"
	CommentCenter_GetCommentList_FullMethodName = "/comment.CommentCenter/GetCommentList"
	CommentCenter_GetReplyList_FullMethodName   = "/comment.CommentCenter/GetReplyList"
	CommentCenter_VoteComment_FullMethodName    = "/comment.CommentCenter/VoteComment"
)

// CommentCenterClient is the client API for CommentCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC服务定义
type CommentCenterClient interface {
	CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CreateCommentResp, error)
	DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error)
	GetCommentList(ctx context.Context, in *GetCommentListReq, opts ...grpc.CallOption) (*GetCommentListResp, error)
	GetReplyList(ctx context.Context, in *GetReplyListReq, opts ...grpc.CallOption) (*GetReplyListResp, error)
	VoteComment(ctx context.Context, in *VoteCommentReq, opts ...grpc.CallOption) (*VoteCommentResp, error)
}

type commentCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentCenterClient(cc grpc.ClientConnInterface) CommentCenterClient {
	return &commentCenterClient{cc}
}

func (c *commentCenterClient) CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CreateCommentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCommentResp)
	err := c.cc.Invoke(ctx, CommentCenter_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentCenterClient) DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCommentResp)
	err := c.cc.Invoke(ctx, CommentCenter_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentCenterClient) GetCommentList(ctx context.Context, in *GetCommentListReq, opts ...grpc.CallOption) (*GetCommentListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommentListResp)
	err := c.cc.Invoke(ctx, CommentCenter_GetCommentList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentCenterClient) GetReplyList(ctx context.Context, in *GetReplyListReq, opts ...grpc.CallOption) (*GetReplyListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReplyListResp)
	err := c.cc.Invoke(ctx, CommentCenter_GetReplyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentCenterClient) VoteComment(ctx context.Context, in *VoteCommentReq, opts ...grpc.CallOption) (*VoteCommentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoteCommentResp)
	err := c.cc.Invoke(ctx, CommentCenter_VoteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentCenterServer is the server API for CommentCenter service.
// All implementations must embed UnimplementedCommentCenterServer
// for forward compatibility.
//
// gRPC服务定义
type CommentCenterServer interface {
	CreateComment(context.Context, *CreateCommentReq) (*CreateCommentResp, error)
	DeleteComment(context.Context, *DeleteCommentReq) (*DeleteCommentResp, error)
	GetCommentList(context.Context, *GetCommentListReq) (*GetCommentListResp, error)
	GetReplyList(context.Context, *GetReplyListReq) (*GetReplyListResp, error)
	VoteComment(context.Context, *VoteCommentReq) (*VoteCommentResp, error)
	mustEmbedUnimplementedCommentCenterServer()
}

// UnimplementedCommentCenterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommentCenterServer struct{}

func (UnimplementedCommentCenterServer) CreateComment(context.Context, *CreateCommentReq) (*CreateCommentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedCommentCenterServer) DeleteComment(context.Context, *DeleteCommentReq) (*DeleteCommentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedCommentCenterServer) GetCommentList(context.Context, *GetCommentListReq) (*GetCommentListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentList not implemented")
}
func (UnimplementedCommentCenterServer) GetReplyList(context.Context, *GetReplyListReq) (*GetReplyListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReplyList not implemented")
}
func (UnimplementedCommentCenterServer) VoteComment(context.Context, *VoteCommentReq) (*VoteCommentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoteComment not implemented")
}
func (UnimplementedCommentCenterServer) mustEmbedUnimplementedCommentCenterServer() {}
func (UnimplementedCommentCenterServer) testEmbeddedByValue()                       {}

// UnsafeCommentCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentCenterServer will
// result in compilation errors.
type UnsafeCommentCenterServer interface {
	mustEmbedUnimplementedCommentCenterServer()
}

func RegisterCommentCenterServer(s grpc.ServiceRegistrar, srv CommentCenterServer) {
	// If the following call pancis, it indicates UnimplementedCommentCenterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommentCenter_ServiceDesc, srv)
}

func _CommentCenter_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentCenterServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentCenter_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentCenterServer).CreateComment(ctx, req.(*CreateCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentCenter_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentCenterServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentCenter_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentCenterServer).DeleteComment(ctx, req.(*DeleteCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentCenter_GetCommentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentCenterServer).GetCommentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentCenter_GetCommentList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentCenterServer).GetCommentList(ctx, req.(*GetCommentListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentCenter_GetReplyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReplyListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentCenterServer).GetReplyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentCenter_GetReplyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentCenterServer).GetReplyList(ctx, req.(*GetReplyListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentCenter_VoteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentCenterServer).VoteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentCenter_VoteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentCenterServer).VoteComment(ctx, req.(*VoteCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CommentCenter_ServiceDesc is the grpc.ServiceDesc for CommentCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "comment.CommentCenter",
	HandlerType: (*CommentCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateComment",
			Handler:    _CommentCenter_CreateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _CommentCenter_DeleteComment_Handler,
		},
		{
			MethodName: "GetCommentList",
			Handler:    _CommentCenter_GetCommentList_Handler,
		},
		{
			MethodName: "GetReplyList",
			Handler:    _CommentCenter_GetReplyList_Handler,
		},
		{
			MethodName: "VoteComment",
			Handler:    _CommentCenter_VoteComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comment.proto",
}
