// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: relation.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RelationCenter_Follow_FullMethodName                 = "/relation.RelationCenter/Follow"
	RelationCenter_Unfollow_FullMethodName               = "/relation.RelationCenter/Unfollow"
	RelationCenter_CheckFollowStatus_FullMethodName      = "/relation.RelationCenter/CheckFollowStatus"
	RelationCenter_GetFollowingList_FullMethodName       = "/relation.RelationCenter/GetFollowingList"
	RelationCenter_GetFollowerList_FullMethodName        = "/relation.RelationCenter/GetFollowerList"
	RelationCenter_BatchCheckFollowStatus_FullMethodName = "/relation.RelationCenter/BatchCheckFollowStatus"
)

// RelationCenterClient is the client API for RelationCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC服务定义
type RelationCenterClient interface {
	Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error)
	Unfollow(ctx context.Context, in *UnfollowReq, opts ...grpc.CallOption) (*UnfollowResp, error)
	CheckFollowStatus(ctx context.Context, in *CheckFollowStatusReq, opts ...grpc.CallOption) (*CheckFollowStatusResp, error)
	GetFollowingList(ctx context.Context, in *GetFollowingListReq, opts ...grpc.CallOption) (*GetFollowingListResp, error)
	GetFollowerList(ctx context.Context, in *GetFollowerListReq, opts ...grpc.CallOption) (*GetFollowerListResp, error)
	BatchCheckFollowStatus(ctx context.Context, in *BatchCheckFollowStatusReq, opts ...grpc.CallOption) (*BatchCheckFollowStatusResp, error)
}

type relationCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewRelationCenterClient(cc grpc.ClientConnInterface) RelationCenterClient {
	return &relationCenterClient{cc}
}

func (c *relationCenterClient) Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowResp)
	err := c.cc.Invoke(ctx, RelationCenter_Follow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relationCenterClient) Unfollow(ctx context.Context, in *UnfollowReq, opts ...grpc.CallOption) (*UnfollowResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnfollowResp)
	err := c.cc.Invoke(ctx, RelationCenter_Unfollow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relationCenterClient) CheckFollowStatus(ctx context.Context, in *CheckFollowStatusReq, opts ...grpc.CallOption) (*CheckFollowStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckFollowStatusResp)
	err := c.cc.Invoke(ctx, RelationCenter_CheckFollowStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relationCenterClient) GetFollowingList(ctx context.Context, in *GetFollowingListReq, opts ...grpc.CallOption) (*GetFollowingListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowingListResp)
	err := c.cc.Invoke(ctx, RelationCenter_GetFollowingList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relationCenterClient) GetFollowerList(ctx context.Context, in *GetFollowerListReq, opts ...grpc.CallOption) (*GetFollowerListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowerListResp)
	err := c.cc.Invoke(ctx, RelationCenter_GetFollowerList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relationCenterClient) BatchCheckFollowStatus(ctx context.Context, in *BatchCheckFollowStatusReq, opts ...grpc.CallOption) (*BatchCheckFollowStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCheckFollowStatusResp)
	err := c.cc.Invoke(ctx, RelationCenter_BatchCheckFollowStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelationCenterServer is the server API for RelationCenter service.
// All implementations must embed UnimplementedRelationCenterServer
// for forward compatibility.
//
// gRPC服务定义
type RelationCenterServer interface {
	Follow(context.Context, *FollowReq) (*FollowResp, error)
	Unfollow(context.Context, *UnfollowReq) (*UnfollowResp, error)
	CheckFollowStatus(context.Context, *CheckFollowStatusReq) (*CheckFollowStatusResp, error)
	GetFollowingList(context.Context, *GetFollowingListReq) (*GetFollowingListResp, error)
	GetFollowerList(context.Context, *GetFollowerListReq) (*GetFollowerListResp, error)
	BatchCheckFollowStatus(context.Context, *BatchCheckFollowStatusReq) (*BatchCheckFollowStatusResp, error)
	mustEmbedUnimplementedRelationCenterServer()
}

// UnimplementedRelationCenterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelationCenterServer struct{}

func (UnimplementedRelationCenterServer) Follow(context.Context, *FollowReq) (*FollowResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Follow not implemented")
}
func (UnimplementedRelationCenterServer) Unfollow(context.Context, *UnfollowReq) (*UnfollowResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unfollow not implemented")
}
func (UnimplementedRelationCenterServer) CheckFollowStatus(context.Context, *CheckFollowStatusReq) (*CheckFollowStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckFollowStatus not implemented")
}
func (UnimplementedRelationCenterServer) GetFollowingList(context.Context, *GetFollowingListReq) (*GetFollowingListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowingList not implemented")
}
func (UnimplementedRelationCenterServer) GetFollowerList(context.Context, *GetFollowerListReq) (*GetFollowerListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowerList not implemented")
}
func (UnimplementedRelationCenterServer) BatchCheckFollowStatus(context.Context, *BatchCheckFollowStatusReq) (*BatchCheckFollowStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchCheckFollowStatus not implemented")
}
func (UnimplementedRelationCenterServer) mustEmbedUnimplementedRelationCenterServer() {}
func (UnimplementedRelationCenterServer) testEmbeddedByValue()                        {}

// UnsafeRelationCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelationCenterServer will
// result in compilation errors.
type UnsafeRelationCenterServer interface {
	mustEmbedUnimplementedRelationCenterServer()
}

func RegisterRelationCenterServer(s grpc.ServiceRegistrar, srv RelationCenterServer) {
	// If the following call pancis, it indicates UnimplementedRelationCenterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelationCenter_ServiceDesc, srv)
}

func _RelationCenter_Follow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationCenterServer).Follow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelationCenter_Follow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationCenterServer).Follow(ctx, req.(*FollowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelationCenter_Unfollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfollowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationCenterServer).Unfollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelationCenter_Unfollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationCenterServer).Unfollow(ctx, req.(*UnfollowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelationCenter_CheckFollowStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckFollowStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationCenterServer).CheckFollowStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelationCenter_CheckFollowStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationCenterServer).CheckFollowStatus(ctx, req.(*CheckFollowStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelationCenter_GetFollowingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowingListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationCenterServer).GetFollowingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelationCenter_GetFollowingList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationCenterServer).GetFollowingList(ctx, req.(*GetFollowingListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelationCenter_GetFollowerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowerListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationCenterServer).GetFollowerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelationCenter_GetFollowerList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationCenterServer).GetFollowerList(ctx, req.(*GetFollowerListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelationCenter_BatchCheckFollowStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCheckFollowStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationCenterServer).BatchCheckFollowStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelationCenter_BatchCheckFollowStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationCenterServer).BatchCheckFollowStatus(ctx, req.(*BatchCheckFollowStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RelationCenter_ServiceDesc is the grpc.ServiceDesc for RelationCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelationCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "relation.RelationCenter",
	HandlerType: (*RelationCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Follow",
			Handler:    _RelationCenter_Follow_Handler,
		},
		{
			MethodName: "Unfollow",
			Handler:    _RelationCenter_Unfollow_Handler,
		},
		{
			MethodName: "CheckFollowStatus",
			Handler:    _RelationCenter_CheckFollowStatus_Handler,
		},
		{
			MethodName: "GetFollowingList",
			Handler:    _RelationCenter_GetFollowingList_Handler,
		},
		{
			MethodName: "GetFollowerList",
			Handler:    _RelationCenter_GetFollowerList_Handler,
		},
		{
			MethodName: "BatchCheckFollowStatus",
			Handler:    _RelationCenter_BatchCheckFollowStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "relation.proto",
}
