// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: relation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 关注关系信息
type FollowInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	FollowTime    int64                  `protobuf:"varint,4,opt,name=followTime,proto3" json:"followTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowInfo) Reset() {
	*x = FollowInfo{}
	mi := &file_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowInfo) ProtoMessage() {}

func (x *FollowInfo) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowInfo.ProtoReflect.Descriptor instead.
func (*FollowInfo) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{0}
}

func (x *FollowInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FollowInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *FollowInfo) GetFollowTime() int64 {
	if x != nil {
		return x.FollowTime
	}
	return 0
}

// 关注请求
type FollowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	TargetUserId  uint64                 `protobuf:"varint,2,opt,name=targetUserId,proto3" json:"targetUserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowReq) Reset() {
	*x = FollowReq{}
	mi := &file_relation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowReq) ProtoMessage() {}

func (x *FollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowReq.ProtoReflect.Descriptor instead.
func (*FollowReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{1}
}

func (x *FollowReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowReq) GetTargetUserId() uint64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

// 关注响应
type FollowResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowResp) Reset() {
	*x = FollowResp{}
	mi := &file_relation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResp) ProtoMessage() {}

func (x *FollowResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResp.ProtoReflect.Descriptor instead.
func (*FollowResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{2}
}

func (x *FollowResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 取消关注请求
type UnfollowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	TargetUserId  uint64                 `protobuf:"varint,2,opt,name=targetUserId,proto3" json:"targetUserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowReq) Reset() {
	*x = UnfollowReq{}
	mi := &file_relation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowReq) ProtoMessage() {}

func (x *UnfollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowReq.ProtoReflect.Descriptor instead.
func (*UnfollowReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{3}
}

func (x *UnfollowReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnfollowReq) GetTargetUserId() uint64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

// 取消关注响应
type UnfollowResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowResp) Reset() {
	*x = UnfollowResp{}
	mi := &file_relation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowResp) ProtoMessage() {}

func (x *UnfollowResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowResp.ProtoReflect.Descriptor instead.
func (*UnfollowResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{4}
}

func (x *UnfollowResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 检查关注状态请求
type CheckFollowStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	TargetUserId  uint64                 `protobuf:"varint,2,opt,name=targetUserId,proto3" json:"targetUserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFollowStatusReq) Reset() {
	*x = CheckFollowStatusReq{}
	mi := &file_relation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFollowStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFollowStatusReq) ProtoMessage() {}

func (x *CheckFollowStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFollowStatusReq.ProtoReflect.Descriptor instead.
func (*CheckFollowStatusReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{5}
}

func (x *CheckFollowStatusReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckFollowStatusReq) GetTargetUserId() uint64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

// 检查关注状态响应
type CheckFollowStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFollow      bool                   `protobuf:"varint,1,opt,name=isFollow,proto3" json:"isFollow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFollowStatusResp) Reset() {
	*x = CheckFollowStatusResp{}
	mi := &file_relation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFollowStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFollowStatusResp) ProtoMessage() {}

func (x *CheckFollowStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFollowStatusResp.ProtoReflect.Descriptor instead.
func (*CheckFollowStatusResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{6}
}

func (x *CheckFollowStatusResp) GetIsFollow() bool {
	if x != nil {
		return x.IsFollow
	}
	return false
}

// 获取关注列表请求
type GetFollowingListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingListReq) Reset() {
	*x = GetFollowingListReq{}
	mi := &file_relation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingListReq) ProtoMessage() {}

func (x *GetFollowingListReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingListReq.ProtoReflect.Descriptor instead.
func (*GetFollowingListReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{7}
}

func (x *GetFollowingListReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFollowingListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetFollowingListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取关注列表响应
type GetFollowingListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*FollowInfo          `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingListResp) Reset() {
	*x = GetFollowingListResp{}
	mi := &file_relation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingListResp) ProtoMessage() {}

func (x *GetFollowingListResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingListResp.ProtoReflect.Descriptor instead.
func (*GetFollowingListResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{8}
}

func (x *GetFollowingListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetFollowingListResp) GetList() []*FollowInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// 获取粉丝列表请求
type GetFollowerListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowerListReq) Reset() {
	*x = GetFollowerListReq{}
	mi := &file_relation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowerListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowerListReq) ProtoMessage() {}

func (x *GetFollowerListReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowerListReq.ProtoReflect.Descriptor instead.
func (*GetFollowerListReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{9}
}

func (x *GetFollowerListReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFollowerListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetFollowerListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取粉丝列表响应
type GetFollowerListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*FollowInfo          `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowerListResp) Reset() {
	*x = GetFollowerListResp{}
	mi := &file_relation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowerListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowerListResp) ProtoMessage() {}

func (x *GetFollowerListResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowerListResp.ProtoReflect.Descriptor instead.
func (*GetFollowerListResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{10}
}

func (x *GetFollowerListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetFollowerListResp) GetList() []*FollowInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// 批量检查关注状态请求
type BatchCheckFollowStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	TargetUserIds []uint64               `protobuf:"varint,2,rep,packed,name=targetUserIds,proto3" json:"targetUserIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckFollowStatusReq) Reset() {
	*x = BatchCheckFollowStatusReq{}
	mi := &file_relation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckFollowStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckFollowStatusReq) ProtoMessage() {}

func (x *BatchCheckFollowStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckFollowStatusReq.ProtoReflect.Descriptor instead.
func (*BatchCheckFollowStatusReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{11}
}

func (x *BatchCheckFollowStatusReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BatchCheckFollowStatusReq) GetTargetUserIds() []uint64 {
	if x != nil {
		return x.TargetUserIds
	}
	return nil
}

// 关注状态项
type FollowStatusItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	IsFollow      bool                   `protobuf:"varint,2,opt,name=isFollow,proto3" json:"isFollow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowStatusItem) Reset() {
	*x = FollowStatusItem{}
	mi := &file_relation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowStatusItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowStatusItem) ProtoMessage() {}

func (x *FollowStatusItem) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowStatusItem.ProtoReflect.Descriptor instead.
func (*FollowStatusItem) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{12}
}

func (x *FollowStatusItem) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowStatusItem) GetIsFollow() bool {
	if x != nil {
		return x.IsFollow
	}
	return false
}

// 批量检查关注状态响应
type BatchCheckFollowStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        []*FollowStatusItem    `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckFollowStatusResp) Reset() {
	*x = BatchCheckFollowStatusResp{}
	mi := &file_relation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckFollowStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckFollowStatusResp) ProtoMessage() {}

func (x *BatchCheckFollowStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckFollowStatusResp.ProtoReflect.Descriptor instead.
func (*BatchCheckFollowStatusResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{13}
}

func (x *BatchCheckFollowStatusResp) GetStatus() []*FollowStatusItem {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_relation_proto protoreflect.FileDescriptor

const file_relation_proto_rawDesc = "" +
	"\n" +
	"\x0erelation.proto\x12\brelation\"x\n" +
	"\n" +
	"FollowInfo\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x1e\n" +
	"\n" +
	"followTime\x18\x04 \x01(\x03R\n" +
	"followTime\"G\n" +
	"\tFollowReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\"\n" +
	"\ftargetUserId\x18\x02 \x01(\x04R\ftargetUserId\"&\n" +
	"\n" +
	"FollowResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"I\n" +
	"\vUnfollowReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\"\n" +
	"\ftargetUserId\x18\x02 \x01(\x04R\ftargetUserId\"(\n" +
	"\fUnfollowResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"R\n" +
	"\x14CheckFollowStatusReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\"\n" +
	"\ftargetUserId\x18\x02 \x01(\x04R\ftargetUserId\"3\n" +
	"\x15CheckFollowStatusResp\x12\x1a\n" +
	"\bisFollow\x18\x01 \x01(\bR\bisFollow\"]\n" +
	"\x13GetFollowingListReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\"V\n" +
	"\x14GetFollowingListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12(\n" +
	"\x04list\x18\x02 \x03(\v2\x14.relation.FollowInfoR\x04list\"\\\n" +
	"\x12GetFollowerListReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\"U\n" +
	"\x13GetFollowerListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12(\n" +
	"\x04list\x18\x02 \x03(\v2\x14.relation.FollowInfoR\x04list\"Y\n" +
	"\x19BatchCheckFollowStatusReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12$\n" +
	"\rtargetUserIds\x18\x02 \x03(\x04R\rtargetUserIds\"F\n" +
	"\x10FollowStatusItem\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bisFollow\x18\x02 \x01(\bR\bisFollow\"P\n" +
	"\x1aBatchCheckFollowStatusResp\x122\n" +
	"\x06status\x18\x01 \x03(\v2\x1a.relation.FollowStatusItemR\x06status2\xde\x03\n" +
	"\x0eRelationCenter\x123\n" +
	"\x06Follow\x12\x13.relation.FollowReq\x1a\x14.relation.FollowResp\x129\n" +
	"\bUnfollow\x12\x15.relation.UnfollowReq\x1a\x16.relation.UnfollowResp\x12T\n" +
	"\x11CheckFollowStatus\x12\x1e.relation.CheckFollowStatusReq\x1a\x1f.relation.CheckFollowStatusResp\x12Q\n" +
	"\x10GetFollowingList\x12\x1d.relation.GetFollowingListReq\x1a\x1e.relation.GetFollowingListResp\x12N\n" +
	"\x0fGetFollowerList\x12\x1c.relation.GetFollowerListReq\x1a\x1d.relation.GetFollowerListResp\x12c\n" +
	"\x16BatchCheckFollowStatus\x12#.relation.BatchCheckFollowStatusReq\x1a$.relation.BatchCheckFollowStatusRespB\x05Z\x03/pbb\x06proto3"

var (
	file_relation_proto_rawDescOnce sync.Once
	file_relation_proto_rawDescData []byte
)

func file_relation_proto_rawDescGZIP() []byte {
	file_relation_proto_rawDescOnce.Do(func() {
		file_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relation_proto_rawDesc), len(file_relation_proto_rawDesc)))
	})
	return file_relation_proto_rawDescData
}

var file_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_relation_proto_goTypes = []any{
	(*FollowInfo)(nil),                 // 0: relation.FollowInfo
	(*FollowReq)(nil),                  // 1: relation.FollowReq
	(*FollowResp)(nil),                 // 2: relation.FollowResp
	(*UnfollowReq)(nil),                // 3: relation.UnfollowReq
	(*UnfollowResp)(nil),               // 4: relation.UnfollowResp
	(*CheckFollowStatusReq)(nil),       // 5: relation.CheckFollowStatusReq
	(*CheckFollowStatusResp)(nil),      // 6: relation.CheckFollowStatusResp
	(*GetFollowingListReq)(nil),        // 7: relation.GetFollowingListReq
	(*GetFollowingListResp)(nil),       // 8: relation.GetFollowingListResp
	(*GetFollowerListReq)(nil),         // 9: relation.GetFollowerListReq
	(*GetFollowerListResp)(nil),        // 10: relation.GetFollowerListResp
	(*BatchCheckFollowStatusReq)(nil),  // 11: relation.BatchCheckFollowStatusReq
	(*FollowStatusItem)(nil),           // 12: relation.FollowStatusItem
	(*BatchCheckFollowStatusResp)(nil), // 13: relation.BatchCheckFollowStatusResp
}
var file_relation_proto_depIdxs = []int32{
	0,  // 0: relation.GetFollowingListResp.list:type_name -> relation.FollowInfo
	0,  // 1: relation.GetFollowerListResp.list:type_name -> relation.FollowInfo
	12, // 2: relation.BatchCheckFollowStatusResp.status:type_name -> relation.FollowStatusItem
	1,  // 3: relation.RelationCenter.Follow:input_type -> relation.FollowReq
	3,  // 4: relation.RelationCenter.Unfollow:input_type -> relation.UnfollowReq
	5,  // 5: relation.RelationCenter.CheckFollowStatus:input_type -> relation.CheckFollowStatusReq
	7,  // 6: relation.RelationCenter.GetFollowingList:input_type -> relation.GetFollowingListReq
	9,  // 7: relation.RelationCenter.GetFollowerList:input_type -> relation.GetFollowerListReq
	11, // 8: relation.RelationCenter.BatchCheckFollowStatus:input_type -> relation.BatchCheckFollowStatusReq
	2,  // 9: relation.RelationCenter.Follow:output_type -> relation.FollowResp
	4,  // 10: relation.RelationCenter.Unfollow:output_type -> relation.UnfollowResp
	6,  // 11: relation.RelationCenter.CheckFollowStatus:output_type -> relation.CheckFollowStatusResp
	8,  // 12: relation.RelationCenter.GetFollowingList:output_type -> relation.GetFollowingListResp
	10, // 13: relation.RelationCenter.GetFollowerList:output_type -> relation.GetFollowerListResp
	13, // 14: relation.RelationCenter.BatchCheckFollowStatus:output_type -> relation.BatchCheckFollowStatusResp
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_relation_proto_init() }
func file_relation_proto_init() {
	if File_relation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relation_proto_rawDesc), len(file_relation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relation_proto_goTypes,
		DependencyIndexes: file_relation_proto_depIdxs,
		MessageInfos:      file_relation_proto_msgTypes,
	}.Build()
	File_relation_proto = out.File
	file_relation_proto_goTypes = nil
	file_relation_proto_depIdxs = nil
}
