// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"SChill/service/content/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/content/post",
				Handler: CreatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/content/post",
				Handler: UpdatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/content/post/:postId",
				Handler: DeletePostHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Jwt.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/content/post/:postId",
				Handler: GetPostDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/content/post/:postId/view",
				Handler: IncViewCountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/content/post/batch",
				Handler: BatchGetPostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/content/post/list",
				Handler: GetPostListHandler(serverCtx),
			},
		},
	)
}
