// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"SChill/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/token/refresh",
				Handler: RefreshHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/:id",
				Handler: GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/:id/profile",
				Handler: GetUserProfileInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/:id/stat",
				Handler: GetUserStatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/avatar",
				Handler: UpdateAvatarHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/info",
				Handler: UpdateUserProfileInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Jwt.AccessSecret),
	)
}
