// 用户中心服务协议定义
// 包含用户基本信息、个人资料、统计数据以及认证相关接口

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户基本信息
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`       // 用户ID
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`    // 用户名
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`    // 昵称
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`          // 手机号
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`          // 电子邮箱
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`        // 头像URL
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`       // 用户状态（1:正常 2:禁言 3:冻结）
	IsAdmin       bool                   `protobuf:"varint,8,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`     // 是否为管理员
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"` // 创建时间（Unix时间戳，秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserInfo) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *UserInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 用户个人资料（可扩展信息，字段均为可选）
type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`            // 关联的用户ID
	Gender        *int64                 `protobuf:"varint,2,opt,name=gender,proto3,oneof" json:"gender,omitempty"`      // 性别（0:未知 1:男 2:女）
	Birthday      *string                `protobuf:"bytes,3,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`   // 生日（格式：YYYY-MM-DD）
	Signature     *string                `protobuf:"bytes,4,opt,name=signature,proto3,oneof" json:"signature,omitempty"` // 个性签名
	Location      *string                `protobuf:"bytes,5,opt,name=location,proto3,oneof" json:"location,omitempty"`   // 所在地
	Website       *string                `protobuf:"bytes,6,opt,name=website,proto3,oneof" json:"website,omitempty"`     // 个人网站
	Company       *string                `protobuf:"bytes,7,opt,name=company,proto3,oneof" json:"company,omitempty"`     // 所在公司
	JobTitle      *string                `protobuf:"bytes,8,opt,name=jobTitle,proto3,oneof" json:"jobTitle,omitempty"`   // 职位
	Education     *string                `protobuf:"bytes,9,opt,name=education,proto3,oneof" json:"education,omitempty"` // 教育背景
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserProfile) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserProfile) GetGender() int64 {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return 0
}

func (x *UserProfile) GetBirthday() string {
	if x != nil && x.Birthday != nil {
		return *x.Birthday
	}
	return ""
}

func (x *UserProfile) GetSignature() string {
	if x != nil && x.Signature != nil {
		return *x.Signature
	}
	return ""
}

func (x *UserProfile) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

func (x *UserProfile) GetWebsite() string {
	if x != nil && x.Website != nil {
		return *x.Website
	}
	return ""
}

func (x *UserProfile) GetCompany() string {
	if x != nil && x.Company != nil {
		return *x.Company
	}
	return ""
}

func (x *UserProfile) GetJobTitle() string {
	if x != nil && x.JobTitle != nil {
		return *x.JobTitle
	}
	return ""
}

func (x *UserProfile) GetEducation() string {
	if x != nil && x.Education != nil {
		return *x.Education
	}
	return ""
}

// 用户统计信息
type UserStat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`                   // 用户ID
	PostCount       uint64                 `protobuf:"varint,2,opt,name=postCount,proto3" json:"postCount,omitempty"`             // 发帖数
	CommentCount    uint64                 `protobuf:"varint,3,opt,name=commentCount,proto3" json:"commentCount,omitempty"`       // 评论数
	FollowerCount   uint64                 `protobuf:"varint,4,opt,name=followerCount,proto3" json:"followerCount,omitempty"`     // 粉丝数
	FollowingCount  uint64                 `protobuf:"varint,5,opt,name=followingCount,proto3" json:"followingCount,omitempty"`   // 关注数
	LikeCount       uint64                 `protobuf:"varint,6,opt,name=likeCount,proto3" json:"likeCount,omitempty"`             // 获赞总数
	CollectionCount uint64                 `protobuf:"varint,7,opt,name=collectionCount,proto3" json:"collectionCount,omitempty"` // 收藏总数
	LastActiveTime  int64                  `protobuf:"varint,8,opt,name=lastActiveTime,proto3" json:"lastActiveTime,omitempty"`   // 最后活跃时间（Unix时间戳，秒）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserStat) Reset() {
	*x = UserStat{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStat) ProtoMessage() {}

func (x *UserStat) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStat.ProtoReflect.Descriptor instead.
func (*UserStat) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserStat) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserStat) GetPostCount() uint64 {
	if x != nil {
		return x.PostCount
	}
	return 0
}

func (x *UserStat) GetCommentCount() uint64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *UserStat) GetFollowerCount() uint64 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

func (x *UserStat) GetFollowingCount() uint64 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

func (x *UserStat) GetLikeCount() uint64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *UserStat) GetCollectionCount() uint64 {
	if x != nil {
		return x.CollectionCount
	}
	return 0
}

func (x *UserStat) GetLastActiveTime() int64 {
	if x != nil {
		return x.LastActiveTime
	}
	return 0
}

// 注册请求
type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // 用户名
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // 密码（明文，实际传输应加密）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 注册响应
type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"` // 注册成功后的用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterResp) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 登录请求
type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // 用户名
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // 密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 登录响应
type LoginResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`                   // 用户ID
	AccessToken     string                 `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`          // 访问令牌
	AccessExpireIn  int64                  `protobuf:"varint,3,opt,name=accessExpireIn,proto3" json:"accessExpireIn,omitempty"`   // 访问令牌过期时间（Unix时间戳）
	RefreshToken    string                 `protobuf:"bytes,4,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`        // 刷新令牌
	RefreshExpireIn int64                  `protobuf:"varint,5,opt,name=refreshExpireIn,proto3" json:"refreshExpireIn,omitempty"` // 刷新令牌过期时间（Unix时间戳）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *LoginResp) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResp) GetAccessExpireIn() int64 {
	if x != nil {
		return x.AccessExpireIn
	}
	return 0
}

func (x *LoginResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResp) GetRefreshExpireIn() int64 {
	if x != nil {
		return x.RefreshExpireIn
	}
	return 0
}

// 刷新令牌请求
type RefreshTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"` // 刷新令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenReq) Reset() {
	*x = RefreshTokenReq{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenReq) ProtoMessage() {}

func (x *RefreshTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenReq.ProtoReflect.Descriptor instead.
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshTokenReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// 刷新令牌响应
type RefreshTokenResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`                   // 用户ID
	AccessToken     string                 `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`          // 新的访问令牌
	AccessExpireIn  int64                  `protobuf:"varint,3,opt,name=accessExpireIn,proto3" json:"accessExpireIn,omitempty"`   // 访问令牌过期时间
	RefreshToken    string                 `protobuf:"bytes,4,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`        // 新的刷新令牌
	RefreshExpireIn int64                  `protobuf:"varint,5,opt,name=refreshExpireIn,proto3" json:"refreshExpireIn,omitempty"` // 刷新令牌过期时间
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RefreshTokenResp) Reset() {
	*x = RefreshTokenResp{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResp) ProtoMessage() {}

func (x *RefreshTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResp.ProtoReflect.Descriptor instead.
func (*RefreshTokenResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshTokenResp) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RefreshTokenResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResp) GetAccessExpireIn() int64 {
	if x != nil {
		return x.AccessExpireIn
	}
	return 0
}

func (x *RefreshTokenResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResp) GetRefreshExpireIn() int64 {
	if x != nil {
		return x.RefreshExpireIn
	}
	return 0
}

// 获取用户信息请求
type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserInfoReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取用户信息响应（包含基本信息、个人资料、统计数据）
type GetUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *UserInfo              `protobuf:"bytes,1,opt,name=userInfo,proto3" json:"userInfo,omitempty"` // 基本信息
	Profile       *UserProfile           `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`   // 个人资料
	Stat          *UserStat              `protobuf:"bytes,3,opt,name=stat,proto3" json:"stat,omitempty"`         // 统计数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResp) Reset() {
	*x = GetUserInfoResp{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResp) ProtoMessage() {}

func (x *GetUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserInfoResp) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *GetUserInfoResp) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *GetUserInfoResp) GetStat() *UserStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

// 用户基础信息（用于列表展示等轻量场景）
type UserBasicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`    // 用户ID
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"` // 用户名
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"` // 昵称
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`     // 头像URL
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`    // 用户状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBasicInfo) Reset() {
	*x = UserBasicInfo{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBasicInfo) ProtoMessage() {}

func (x *UserBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBasicInfo.ProtoReflect.Descriptor instead.
func (*UserBasicInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *UserBasicInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserBasicInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserBasicInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserBasicInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserBasicInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 批量获取用户基础信息请求
type BatchGetUserBasicInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []uint64               `protobuf:"varint,1,rep,packed,name=userIds,proto3" json:"userIds,omitempty"` // 用户ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUserBasicInfoReq) Reset() {
	*x = BatchGetUserBasicInfoReq{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUserBasicInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserBasicInfoReq) ProtoMessage() {}

func (x *BatchGetUserBasicInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserBasicInfoReq.ProtoReflect.Descriptor instead.
func (*BatchGetUserBasicInfoReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *BatchGetUserBasicInfoReq) GetUserIds() []uint64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// 批量获取用户基础信息响应
type BatchGetUserBasicInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserBasicInfo       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"` // 用户基础信息列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUserBasicInfoResp) Reset() {
	*x = BatchGetUserBasicInfoResp{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUserBasicInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserBasicInfoResp) ProtoMessage() {}

func (x *BatchGetUserBasicInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserBasicInfoResp.ProtoReflect.Descriptor instead.
func (*BatchGetUserBasicInfoResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *BatchGetUserBasicInfoResp) GetUsers() []*UserBasicInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

// 更新用户状态请求
type UpdateUserStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"` // 用户ID
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 新状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatusReq) Reset() {
	*x = UpdateUserStatusReq{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatusReq) ProtoMessage() {}

func (x *UpdateUserStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateUserStatusReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateUserStatusReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 更新用户状态响应
type UpdateUserStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatusResp) Reset() {
	*x = UpdateUserStatusResp{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatusResp) ProtoMessage() {}

func (x *UpdateUserStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatusResp.ProtoReflect.Descriptor instead.
func (*UpdateUserStatusResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateUserStatusResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 更新用户个人资料请求
type UpdateUserProfileInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserProfile   *UserProfile           `protobuf:"bytes,1,opt,name=userProfile,proto3" json:"userProfile,omitempty"` // 要更新的个人资料
	UserId        uint64                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`          // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileInfoReq) Reset() {
	*x = UpdateUserProfileInfoReq{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileInfoReq) ProtoMessage() {}

func (x *UpdateUserProfileInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileInfoReq.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileInfoReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateUserProfileInfoReq) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

func (x *UpdateUserProfileInfoReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 更新用户个人资料响应
type UpdateUserProfileInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserProfile   *UserProfile           `protobuf:"bytes,1,opt,name=userProfile,proto3" json:"userProfile,omitempty"` // 更新后的个人资料
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileInfoResp) Reset() {
	*x = UpdateUserProfileInfoResp{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileInfoResp) ProtoMessage() {}

func (x *UpdateUserProfileInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileInfoResp.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileInfoResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateUserProfileInfoResp) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

// 获取用户统计信息请求
type GetUserStatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatReq) Reset() {
	*x = GetUserStatReq{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatReq) ProtoMessage() {}

func (x *GetUserStatReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatReq.ProtoReflect.Descriptor instead.
func (*GetUserStatReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserStatReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取用户统计信息响应
type GetUserStatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stat          *UserStat              `protobuf:"bytes,1,opt,name=stat,proto3" json:"stat,omitempty"` // 统计信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatResp) Reset() {
	*x = GetUserStatResp{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatResp) ProtoMessage() {}

func (x *GetUserStatResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatResp.ProtoReflect.Descriptor instead.
func (*GetUserStatResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserStatResp) GetStat() *UserStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

// 获取用户个人资料请求
type GetUserProfileInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileInfoReq) Reset() {
	*x = GetUserProfileInfoReq{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileInfoReq) ProtoMessage() {}

func (x *GetUserProfileInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserProfileInfoReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

func (x *GetUserProfileInfoReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取用户个人资料响应
type GetUserProfileInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"` // 个人资料
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileInfoResp) Reset() {
	*x = GetUserProfileInfoResp{}
	mi := &file_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileInfoResp) ProtoMessage() {}

func (x *GetUserProfileInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserProfileInfoResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{21}
}

func (x *GetUserProfileInfoResp) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// 更新用户头像请求
type UpdateAvatarReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`      // 用户ID
	AvatarUrl     string                 `protobuf:"bytes,2,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"` // 新的头像URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAvatarReq) Reset() {
	*x = UpdateAvatarReq{}
	mi := &file_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAvatarReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAvatarReq) ProtoMessage() {}

func (x *UpdateAvatarReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAvatarReq.ProtoReflect.Descriptor instead.
func (*UpdateAvatarReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateAvatarReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateAvatarReq) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

// 更新用户头像响应
type UpdateAvatarResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvatarUrl     string                 `protobuf:"bytes,1,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"` // 当前的头像URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAvatarResp) Reset() {
	*x = UpdateAvatarResp{}
	mi := &file_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAvatarResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAvatarResp) ProtoMessage() {}

func (x *UpdateAvatarResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAvatarResp.ProtoReflect.Descriptor instead.
func (*UpdateAvatarResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateAvatarResp) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"\xee\x01\n" +
	"\bUserInfo\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x18\n" +
	"\aisAdmin\x18\b \x01(\bR\aisAdmin\x12\x1c\n" +
	"\tcreatedAt\x18\t \x01(\x03R\tcreatedAt\"\x8f\x03\n" +
	"\vUserProfile\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\x06gender\x18\x02 \x01(\x03H\x00R\x06gender\x88\x01\x01\x12\x1f\n" +
	"\bbirthday\x18\x03 \x01(\tH\x01R\bbirthday\x88\x01\x01\x12!\n" +
	"\tsignature\x18\x04 \x01(\tH\x02R\tsignature\x88\x01\x01\x12\x1f\n" +
	"\blocation\x18\x05 \x01(\tH\x03R\blocation\x88\x01\x01\x12\x1d\n" +
	"\awebsite\x18\x06 \x01(\tH\x04R\awebsite\x88\x01\x01\x12\x1d\n" +
	"\acompany\x18\a \x01(\tH\x05R\acompany\x88\x01\x01\x12\x1f\n" +
	"\bjobTitle\x18\b \x01(\tH\x06R\bjobTitle\x88\x01\x01\x12!\n" +
	"\teducation\x18\t \x01(\tH\aR\teducation\x88\x01\x01B\t\n" +
	"\a_genderB\v\n" +
	"\t_birthdayB\f\n" +
	"\n" +
	"_signatureB\v\n" +
	"\t_locationB\n" +
	"\n" +
	"\b_websiteB\n" +
	"\n" +
	"\b_companyB\v\n" +
	"\t_jobTitleB\f\n" +
	"\n" +
	"_education\"\xa2\x02\n" +
	"\bUserStat\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x1c\n" +
	"\tpostCount\x18\x02 \x01(\x04R\tpostCount\x12\"\n" +
	"\fcommentCount\x18\x03 \x01(\x04R\fcommentCount\x12$\n" +
	"\rfollowerCount\x18\x04 \x01(\x04R\rfollowerCount\x12&\n" +
	"\x0efollowingCount\x18\x05 \x01(\x04R\x0efollowingCount\x12\x1c\n" +
	"\tlikeCount\x18\x06 \x01(\x04R\tlikeCount\x12(\n" +
	"\x0fcollectionCount\x18\a \x01(\x04R\x0fcollectionCount\x12&\n" +
	"\x0elastActiveTime\x18\b \x01(\x03R\x0elastActiveTime\"E\n" +
	"\vRegisterReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"&\n" +
	"\fRegisterResp\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xbb\x01\n" +
	"\tLoginResp\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12 \n" +
	"\vaccessToken\x18\x02 \x01(\tR\vaccessToken\x12&\n" +
	"\x0eaccessExpireIn\x18\x03 \x01(\x03R\x0eaccessExpireIn\x12\"\n" +
	"\frefreshToken\x18\x04 \x01(\tR\frefreshToken\x12(\n" +
	"\x0frefreshExpireIn\x18\x05 \x01(\x03R\x0frefreshExpireIn\"5\n" +
	"\x0fRefreshTokenReq\x12\"\n" +
	"\frefreshToken\x18\x01 \x01(\tR\frefreshToken\"\xc2\x01\n" +
	"\x10RefreshTokenResp\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12 \n" +
	"\vaccessToken\x18\x02 \x01(\tR\vaccessToken\x12&\n" +
	"\x0eaccessExpireIn\x18\x03 \x01(\x03R\x0eaccessExpireIn\x12\"\n" +
	"\frefreshToken\x18\x04 \x01(\tR\frefreshToken\x12(\n" +
	"\x0frefreshExpireIn\x18\x05 \x01(\x03R\x0frefreshExpireIn\"(\n" +
	"\x0eGetUserInfoReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\"\x8e\x01\n" +
	"\x0fGetUserInfoResp\x12*\n" +
	"\buserInfo\x18\x01 \x01(\v2\x0e.user.UserInfoR\buserInfo\x12+\n" +
	"\aprofile\x18\x02 \x01(\v2\x11.user.UserProfileR\aprofile\x12\"\n" +
	"\x04stat\x18\x03 \x01(\v2\x0e.user.UserStatR\x04stat\"\x8f\x01\n" +
	"\rUserBasicInfo\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"4\n" +
	"\x18BatchGetUserBasicInfoReq\x12\x18\n" +
	"\auserIds\x18\x01 \x03(\x04R\auserIds\"F\n" +
	"\x19BatchGetUserBasicInfoResp\x12)\n" +
	"\x05users\x18\x01 \x03(\v2\x13.user.UserBasicInfoR\x05users\"E\n" +
	"\x13UpdateUserStatusReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"0\n" +
	"\x14UpdateUserStatusResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"g\n" +
	"\x18UpdateUserProfileInfoReq\x123\n" +
	"\vuserProfile\x18\x01 \x01(\v2\x11.user.UserProfileR\vuserProfile\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x04R\x06userId\"P\n" +
	"\x19UpdateUserProfileInfoResp\x123\n" +
	"\vuserProfile\x18\x01 \x01(\v2\x11.user.UserProfileR\vuserProfile\"(\n" +
	"\x0eGetUserStatReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\"5\n" +
	"\x0fGetUserStatResp\x12\"\n" +
	"\x04stat\x18\x01 \x01(\v2\x0e.user.UserStatR\x04stat\"/\n" +
	"\x15GetUserProfileInfoReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\"E\n" +
	"\x16GetUserProfileInfoResp\x12+\n" +
	"\aprofile\x18\x01 \x01(\v2\x11.user.UserProfileR\aprofile\"G\n" +
	"\x0fUpdateAvatarReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x1c\n" +
	"\tavatarUrl\x18\x02 \x01(\tR\tavatarUrl\"0\n" +
	"\x10UpdateAvatarResp\x12\x1c\n" +
	"\tavatarUrl\x18\x01 \x01(\tR\tavatarUrl2\xaf\x05\n" +
	"\n" +
	"UserCenter\x121\n" +
	"\bRegister\x12\x11.user.RegisterReq\x1a\x12.user.RegisterResp\x12(\n" +
	"\x05Login\x12\x0e.user.LoginReq\x1a\x0f.user.LoginResp\x12=\n" +
	"\fRefreshToken\x12\x15.user.RefreshTokenReq\x1a\x16.user.RefreshTokenResp\x12:\n" +
	"\vGetUserInfo\x12\x14.user.GetUserInfoReq\x1a\x15.user.GetUserInfoResp\x12X\n" +
	"\x15BatchGetUserBasicInfo\x12\x1e.user.BatchGetUserBasicInfoReq\x1a\x1f.user.BatchGetUserBasicInfoResp\x12I\n" +
	"\x10UpdateUserStatus\x12\x19.user.UpdateUserStatusReq\x1a\x1a.user.UpdateUserStatusResp\x12X\n" +
	"\x15UpdateUserProfileInfo\x12\x1e.user.UpdateUserProfileInfoReq\x1a\x1f.user.UpdateUserProfileInfoResp\x12:\n" +
	"\vGetUserStat\x12\x14.user.GetUserStatReq\x1a\x15.user.GetUserStatResp\x12O\n" +
	"\x12GetUserProfileInfo\x12\x1b.user.GetUserProfileInfoReq\x1a\x1c.user.GetUserProfileInfoResp\x12=\n" +
	"\fUpdateAvatar\x12\x15.user.UpdateAvatarReq\x1a\x16.user.UpdateAvatarRespB\x05Z\x03/pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_user_proto_goTypes = []any{
	(*UserInfo)(nil),                  // 0: user.UserInfo
	(*UserProfile)(nil),               // 1: user.UserProfile
	(*UserStat)(nil),                  // 2: user.UserStat
	(*RegisterReq)(nil),               // 3: user.RegisterReq
	(*RegisterResp)(nil),              // 4: user.RegisterResp
	(*LoginReq)(nil),                  // 5: user.LoginReq
	(*LoginResp)(nil),                 // 6: user.LoginResp
	(*RefreshTokenReq)(nil),           // 7: user.RefreshTokenReq
	(*RefreshTokenResp)(nil),          // 8: user.RefreshTokenResp
	(*GetUserInfoReq)(nil),            // 9: user.GetUserInfoReq
	(*GetUserInfoResp)(nil),           // 10: user.GetUserInfoResp
	(*UserBasicInfo)(nil),             // 11: user.UserBasicInfo
	(*BatchGetUserBasicInfoReq)(nil),  // 12: user.BatchGetUserBasicInfoReq
	(*BatchGetUserBasicInfoResp)(nil), // 13: user.BatchGetUserBasicInfoResp
	(*UpdateUserStatusReq)(nil),       // 14: user.UpdateUserStatusReq
	(*UpdateUserStatusResp)(nil),      // 15: user.UpdateUserStatusResp
	(*UpdateUserProfileInfoReq)(nil),  // 16: user.UpdateUserProfileInfoReq
	(*UpdateUserProfileInfoResp)(nil), // 17: user.UpdateUserProfileInfoResp
	(*GetUserStatReq)(nil),            // 18: user.GetUserStatReq
	(*GetUserStatResp)(nil),           // 19: user.GetUserStatResp
	(*GetUserProfileInfoReq)(nil),     // 20: user.GetUserProfileInfoReq
	(*GetUserProfileInfoResp)(nil),    // 21: user.GetUserProfileInfoResp
	(*UpdateAvatarReq)(nil),           // 22: user.UpdateAvatarReq
	(*UpdateAvatarResp)(nil),          // 23: user.UpdateAvatarResp
}
var file_user_proto_depIdxs = []int32{
	0,  // 0: user.GetUserInfoResp.userInfo:type_name -> user.UserInfo
	1,  // 1: user.GetUserInfoResp.profile:type_name -> user.UserProfile
	2,  // 2: user.GetUserInfoResp.stat:type_name -> user.UserStat
	11, // 3: user.BatchGetUserBasicInfoResp.users:type_name -> user.UserBasicInfo
	1,  // 4: user.UpdateUserProfileInfoReq.userProfile:type_name -> user.UserProfile
	1,  // 5: user.UpdateUserProfileInfoResp.userProfile:type_name -> user.UserProfile
	2,  // 6: user.GetUserStatResp.stat:type_name -> user.UserStat
	1,  // 7: user.GetUserProfileInfoResp.profile:type_name -> user.UserProfile
	3,  // 8: user.UserCenter.Register:input_type -> user.RegisterReq
	5,  // 9: user.UserCenter.Login:input_type -> user.LoginReq
	7,  // 10: user.UserCenter.RefreshToken:input_type -> user.RefreshTokenReq
	9,  // 11: user.UserCenter.GetUserInfo:input_type -> user.GetUserInfoReq
	12, // 12: user.UserCenter.BatchGetUserBasicInfo:input_type -> user.BatchGetUserBasicInfoReq
	14, // 13: user.UserCenter.UpdateUserStatus:input_type -> user.UpdateUserStatusReq
	16, // 14: user.UserCenter.UpdateUserProfileInfo:input_type -> user.UpdateUserProfileInfoReq
	18, // 15: user.UserCenter.GetUserStat:input_type -> user.GetUserStatReq
	20, // 16: user.UserCenter.GetUserProfileInfo:input_type -> user.GetUserProfileInfoReq
	22, // 17: user.UserCenter.UpdateAvatar:input_type -> user.UpdateAvatarReq
	4,  // 18: user.UserCenter.Register:output_type -> user.RegisterResp
	6,  // 19: user.UserCenter.Login:output_type -> user.LoginResp
	8,  // 20: user.UserCenter.RefreshToken:output_type -> user.RefreshTokenResp
	10, // 21: user.UserCenter.GetUserInfo:output_type -> user.GetUserInfoResp
	13, // 22: user.UserCenter.BatchGetUserBasicInfo:output_type -> user.BatchGetUserBasicInfoResp
	15, // 23: user.UserCenter.UpdateUserStatus:output_type -> user.UpdateUserStatusResp
	17, // 24: user.UserCenter.UpdateUserProfileInfo:output_type -> user.UpdateUserProfileInfoResp
	19, // 25: user.UserCenter.GetUserStat:output_type -> user.GetUserStatResp
	21, // 26: user.UserCenter.GetUserProfileInfo:output_type -> user.GetUserProfileInfoResp
	23, // 27: user.UserCenter.UpdateAvatar:output_type -> user.UpdateAvatarResp
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_user_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
