// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: service/search/rpc/search.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchReq) Reset() {
	*x = SearchReq{}
	mi := &file_service_search_rpc_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReq) ProtoMessage() {}

func (x *SearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_search_rpc_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReq.ProtoReflect.Descriptor instead.
func (*SearchReq) Descriptor() ([]byte, []int) {
	return file_service_search_rpc_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchPostItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Cover           string                 `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Summary         string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Username        string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Avatar          string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Content         string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	TopicNames      []string               `protobuf:"bytes,9,rep,name=topicNames,proto3" json:"topicNames,omitempty"`
	CommentCount    int64                  `protobuf:"varint,10,opt,name=commentCount,proto3" json:"commentCount,omitempty"`
	CollectionCount int64                  `protobuf:"varint,11,opt,name=collectionCount,proto3" json:"collectionCount,omitempty"`
	UpvoteCount     int64                  `protobuf:"varint,12,opt,name=upvoteCount,proto3" json:"upvoteCount,omitempty"`
	ShareCount      int64                  `protobuf:"varint,13,opt,name=shareCount,proto3" json:"shareCount,omitempty"`
	Visibility      int32                  `protobuf:"varint,14,opt,name=visibility,proto3" json:"visibility,omitempty"`
	IsTop           bool                   `protobuf:"varint,15,opt,name=isTop,proto3" json:"isTop,omitempty"`
	IsEssence       bool                   `protobuf:"varint,16,opt,name=isEssence,proto3" json:"isEssence,omitempty"`
	IsLock          bool                   `protobuf:"varint,17,opt,name=isLock,proto3" json:"isLock,omitempty"`
	Tags            []string               `protobuf:"bytes,18,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,19,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchPostItem) Reset() {
	*x = SearchPostItem{}
	mi := &file_service_search_rpc_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPostItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPostItem) ProtoMessage() {}

func (x *SearchPostItem) ProtoReflect() protoreflect.Message {
	mi := &file_service_search_rpc_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPostItem.ProtoReflect.Descriptor instead.
func (*SearchPostItem) Descriptor() ([]byte, []int) {
	return file_service_search_rpc_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchPostItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchPostItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchPostItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchPostItem) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *SearchPostItem) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SearchPostItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SearchPostItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *SearchPostItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SearchPostItem) GetTopicNames() []string {
	if x != nil {
		return x.TopicNames
	}
	return nil
}

func (x *SearchPostItem) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *SearchPostItem) GetCollectionCount() int64 {
	if x != nil {
		return x.CollectionCount
	}
	return 0
}

func (x *SearchPostItem) GetUpvoteCount() int64 {
	if x != nil {
		return x.UpvoteCount
	}
	return 0
}

func (x *SearchPostItem) GetShareCount() int64 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

func (x *SearchPostItem) GetVisibility() int32 {
	if x != nil {
		return x.Visibility
	}
	return 0
}

func (x *SearchPostItem) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

func (x *SearchPostItem) GetIsEssence() bool {
	if x != nil {
		return x.IsEssence
	}
	return false
}

func (x *SearchPostItem) GetIsLock() bool {
	if x != nil {
		return x.IsLock
	}
	return false
}

func (x *SearchPostItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SearchPostItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type SearchPostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	List          []*SearchPostItem      `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPostResp) Reset() {
	*x = SearchPostResp{}
	mi := &file_service_search_rpc_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPostResp) ProtoMessage() {}

func (x *SearchPostResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_search_rpc_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPostResp.ProtoReflect.Descriptor instead.
func (*SearchPostResp) Descriptor() ([]byte, []int) {
	return file_service_search_rpc_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchPostResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SearchPostResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SearchPostResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchPostResp) GetList() []*SearchPostItem {
	if x != nil {
		return x.List
	}
	return nil
}

type SearchUserItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username        string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Status          int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	IsAdmin         bool                   `protobuf:"varint,4,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`
	PostCount       int32                  `protobuf:"varint,5,opt,name=postCount,proto3" json:"postCount,omitempty"`
	CommentCount    int32                  `protobuf:"varint,6,opt,name=commentCount,proto3" json:"commentCount,omitempty"`
	FollowerCount   int32                  `protobuf:"varint,7,opt,name=followerCount,proto3" json:"followerCount,omitempty"`
	LikeCount       int32                  `protobuf:"varint,8,opt,name=likeCount,proto3" json:"likeCount,omitempty"`
	CollectionCount int32                  `protobuf:"varint,9,opt,name=collectionCount,proto3" json:"collectionCount,omitempty"`
	LastActiveTime  int64                  `protobuf:"varint,10,opt,name=lastActiveTime,proto3" json:"lastActiveTime,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchUserItem) Reset() {
	*x = SearchUserItem{}
	mi := &file_service_search_rpc_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserItem) ProtoMessage() {}

func (x *SearchUserItem) ProtoReflect() protoreflect.Message {
	mi := &file_service_search_rpc_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserItem.ProtoReflect.Descriptor instead.
func (*SearchUserItem) Descriptor() ([]byte, []int) {
	return file_service_search_rpc_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchUserItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchUserItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SearchUserItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SearchUserItem) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *SearchUserItem) GetPostCount() int32 {
	if x != nil {
		return x.PostCount
	}
	return 0
}

func (x *SearchUserItem) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *SearchUserItem) GetFollowerCount() int32 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

func (x *SearchUserItem) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *SearchUserItem) GetCollectionCount() int32 {
	if x != nil {
		return x.CollectionCount
	}
	return 0
}

func (x *SearchUserItem) GetLastActiveTime() int64 {
	if x != nil {
		return x.LastActiveTime
	}
	return 0
}

func (x *SearchUserItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type SearchUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	List          []*SearchUserItem      `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserResp) Reset() {
	*x = SearchUserResp{}
	mi := &file_service_search_rpc_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserResp) ProtoMessage() {}

func (x *SearchUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_search_rpc_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserResp.ProtoReflect.Descriptor instead.
func (*SearchUserResp) Descriptor() ([]byte, []int) {
	return file_service_search_rpc_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchUserResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SearchUserResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SearchUserResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchUserResp) GetList() []*SearchUserItem {
	if x != nil {
		return x.List
	}
	return nil
}

type SearchTopicItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	QuoteNum      int64                  `protobuf:"varint,3,opt,name=quoteNum,proto3" json:"quoteNum,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTopicItem) Reset() {
	*x = SearchTopicItem{}
	mi := &file_service_search_rpc_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTopicItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTopicItem) ProtoMessage() {}

func (x *SearchTopicItem) ProtoReflect() protoreflect.Message {
	mi := &file_service_search_rpc_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTopicItem.ProtoReflect.Descriptor instead.
func (*SearchTopicItem) Descriptor() ([]byte, []int) {
	return file_service_search_rpc_search_proto_rawDescGZIP(), []int{5}
}

func (x *SearchTopicItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchTopicItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchTopicItem) GetQuoteNum() int64 {
	if x != nil {
		return x.QuoteNum
	}
	return 0
}

func (x *SearchTopicItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type SearchTopicResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	List          []*SearchTopicItem     `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTopicResp) Reset() {
	*x = SearchTopicResp{}
	mi := &file_service_search_rpc_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTopicResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTopicResp) ProtoMessage() {}

func (x *SearchTopicResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_search_rpc_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTopicResp.ProtoReflect.Descriptor instead.
func (*SearchTopicResp) Descriptor() ([]byte, []int) {
	return file_service_search_rpc_search_proto_rawDescGZIP(), []int{6}
}

func (x *SearchTopicResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SearchTopicResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SearchTopicResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchTopicResp) GetList() []*SearchTopicItem {
	if x != nil {
		return x.List
	}
	return nil
}

var File_service_search_rpc_search_proto protoreflect.FileDescriptor

const file_service_search_rpc_search_proto_rawDesc = "" +
	"\n" +
	"\x1fservice/search/rpc/search.proto\x12\x06search\"U\n" +
	"\tSearchReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\"\x9a\x04\n" +
	"\x0eSearchPostItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05cover\x18\x04 \x01(\tR\x05cover\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"topicNames\x18\t \x03(\tR\n" +
	"topicNames\x12\"\n" +
	"\fcommentCount\x18\n" +
	" \x01(\x03R\fcommentCount\x12(\n" +
	"\x0fcollectionCount\x18\v \x01(\x03R\x0fcollectionCount\x12 \n" +
	"\vupvoteCount\x18\f \x01(\x03R\vupvoteCount\x12\x1e\n" +
	"\n" +
	"shareCount\x18\r \x01(\x03R\n" +
	"shareCount\x12\x1e\n" +
	"\n" +
	"visibility\x18\x0e \x01(\x05R\n" +
	"visibility\x12\x14\n" +
	"\x05isTop\x18\x0f \x01(\bR\x05isTop\x12\x1c\n" +
	"\tisEssence\x18\x10 \x01(\bR\tisEssence\x12\x16\n" +
	"\x06isLock\x18\x11 \x01(\bR\x06isLock\x12\x12\n" +
	"\x04tags\x18\x12 \x03(\tR\x04tags\x12\x1c\n" +
	"\tcreatedAt\x18\x13 \x01(\x03R\tcreatedAt\"x\n" +
	"\x0eSearchPostResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12*\n" +
	"\x04list\x18\x04 \x03(\v2\x16.search.SearchPostItemR\x04list\"\xe4\x02\n" +
	"\x0eSearchUserItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x18\n" +
	"\aisAdmin\x18\x04 \x01(\bR\aisAdmin\x12\x1c\n" +
	"\tpostCount\x18\x05 \x01(\x05R\tpostCount\x12\"\n" +
	"\fcommentCount\x18\x06 \x01(\x05R\fcommentCount\x12$\n" +
	"\rfollowerCount\x18\a \x01(\x05R\rfollowerCount\x12\x1c\n" +
	"\tlikeCount\x18\b \x01(\x05R\tlikeCount\x12(\n" +
	"\x0fcollectionCount\x18\t \x01(\x05R\x0fcollectionCount\x12&\n" +
	"\x0elastActiveTime\x18\n" +
	" \x01(\x03R\x0elastActiveTime\x12\x1c\n" +
	"\tcreatedAt\x18\v \x01(\x03R\tcreatedAt\"x\n" +
	"\x0eSearchUserResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12*\n" +
	"\x04list\x18\x04 \x03(\v2\x16.search.SearchUserItemR\x04list\"o\n" +
	"\x0fSearchTopicItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bquoteNum\x18\x03 \x01(\x03R\bquoteNum\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\x03R\tcreatedAt\"z\n" +
	"\x0fSearchTopicResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12+\n" +
	"\x04list\x18\x04 \x03(\v2\x17.search.SearchTopicItemR\x04list2\xbb\x01\n" +
	"\fSearchCenter\x127\n" +
	"\n" +
	"SearchPost\x12\x11.search.SearchReq\x1a\x16.search.SearchPostResp\x127\n" +
	"\n" +
	"SearchUser\x12\x11.search.SearchReq\x1a\x16.search.SearchUserResp\x129\n" +
	"\vSearchTopic\x12\x11.search.SearchReq\x1a\x17.search.SearchTopicRespB\x05Z\x03/pbb\x06proto3"

var (
	file_service_search_rpc_search_proto_rawDescOnce sync.Once
	file_service_search_rpc_search_proto_rawDescData []byte
)

func file_service_search_rpc_search_proto_rawDescGZIP() []byte {
	file_service_search_rpc_search_proto_rawDescOnce.Do(func() {
		file_service_search_rpc_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_search_rpc_search_proto_rawDesc), len(file_service_search_rpc_search_proto_rawDesc)))
	})
	return file_service_search_rpc_search_proto_rawDescData
}

var file_service_search_rpc_search_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_service_search_rpc_search_proto_goTypes = []any{
	(*SearchReq)(nil),       // 0: search.SearchReq
	(*SearchPostItem)(nil),  // 1: search.SearchPostItem
	(*SearchPostResp)(nil),  // 2: search.SearchPostResp
	(*SearchUserItem)(nil),  // 3: search.SearchUserItem
	(*SearchUserResp)(nil),  // 4: search.SearchUserResp
	(*SearchTopicItem)(nil), // 5: search.SearchTopicItem
	(*SearchTopicResp)(nil), // 6: search.SearchTopicResp
}
var file_service_search_rpc_search_proto_depIdxs = []int32{
	1, // 0: search.SearchPostResp.list:type_name -> search.SearchPostItem
	3, // 1: search.SearchUserResp.list:type_name -> search.SearchUserItem
	5, // 2: search.SearchTopicResp.list:type_name -> search.SearchTopicItem
	0, // 3: search.SearchCenter.SearchPost:input_type -> search.SearchReq
	0, // 4: search.SearchCenter.SearchUser:input_type -> search.SearchReq
	0, // 5: search.SearchCenter.SearchTopic:input_type -> search.SearchReq
	2, // 6: search.SearchCenter.SearchPost:output_type -> search.SearchPostResp
	4, // 7: search.SearchCenter.SearchUser:output_type -> search.SearchUserResp
	6, // 8: search.SearchCenter.SearchTopic:output_type -> search.SearchTopicResp
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_service_search_rpc_search_proto_init() }
func file_service_search_rpc_search_proto_init() {
	if File_service_search_rpc_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_search_rpc_search_proto_rawDesc), len(file_service_search_rpc_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_search_rpc_search_proto_goTypes,
		DependencyIndexes: file_service_search_rpc_search_proto_depIdxs,
		MessageInfos:      file_service_search_rpc_search_proto_msgTypes,
	}.Build()
	File_service_search_rpc_search_proto = out.File
	file_service_search_rpc_search_proto_goTypes = nil
	file_service_search_rpc_search_proto_depIdxs = nil
}
