// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.2
// source: service/search/rpc/search.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SearchCenter_SearchPost_FullMethodName  = "/search.SearchCenter/SearchPost"
	SearchCenter_SearchUser_FullMethodName  = "/search.SearchCenter/SearchUser"
	SearchCenter_SearchTopic_FullMethodName = "/search.SearchCenter/SearchTopic"
)

// SearchCenterClient is the client API for SearchCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchCenterClient interface {
	SearchPost(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchPostResp, error)
	SearchUser(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchUserResp, error)
	SearchTopic(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchTopicResp, error)
}

type searchCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchCenterClient(cc grpc.ClientConnInterface) SearchCenterClient {
	return &searchCenterClient{cc}
}

func (c *searchCenterClient) SearchPost(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchPostResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchPostResp)
	err := c.cc.Invoke(ctx, SearchCenter_SearchPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchCenterClient) SearchUser(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchUserResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchUserResp)
	err := c.cc.Invoke(ctx, SearchCenter_SearchUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchCenterClient) SearchTopic(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchTopicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchTopicResp)
	err := c.cc.Invoke(ctx, SearchCenter_SearchTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchCenterServer is the server API for SearchCenter service.
// All implementations must embed UnimplementedSearchCenterServer
// for forward compatibility.
type SearchCenterServer interface {
	SearchPost(context.Context, *SearchReq) (*SearchPostResp, error)
	SearchUser(context.Context, *SearchReq) (*SearchUserResp, error)
	SearchTopic(context.Context, *SearchReq) (*SearchTopicResp, error)
	mustEmbedUnimplementedSearchCenterServer()
}

// UnimplementedSearchCenterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchCenterServer struct{}

func (UnimplementedSearchCenterServer) SearchPost(context.Context, *SearchReq) (*SearchPostResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchPost not implemented")
}
func (UnimplementedSearchCenterServer) SearchUser(context.Context, *SearchReq) (*SearchUserResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchUser not implemented")
}
func (UnimplementedSearchCenterServer) SearchTopic(context.Context, *SearchReq) (*SearchTopicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchTopic not implemented")
}
func (UnimplementedSearchCenterServer) mustEmbedUnimplementedSearchCenterServer() {}
func (UnimplementedSearchCenterServer) testEmbeddedByValue()                      {}

// UnsafeSearchCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchCenterServer will
// result in compilation errors.
type UnsafeSearchCenterServer interface {
	mustEmbedUnimplementedSearchCenterServer()
}

func RegisterSearchCenterServer(s grpc.ServiceRegistrar, srv SearchCenterServer) {
	// If the following call panics, it indicates UnimplementedSearchCenterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchCenter_ServiceDesc, srv)
}

func _SearchCenter_SearchPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchCenterServer).SearchPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchCenter_SearchPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchCenterServer).SearchPost(ctx, req.(*SearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchCenter_SearchUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchCenterServer).SearchUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchCenter_SearchUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchCenterServer).SearchUser(ctx, req.(*SearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchCenter_SearchTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchCenterServer).SearchTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchCenter_SearchTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchCenterServer).SearchTopic(ctx, req.(*SearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchCenter_ServiceDesc is the grpc.ServiceDesc for SearchCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.SearchCenter",
	HandlerType: (*SearchCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchPost",
			Handler:    _SearchCenter_SearchPost_Handler,
		},
		{
			MethodName: "SearchUser",
			Handler:    _SearchCenter_SearchUser_Handler,
		},
		{
			MethodName: "SearchTopic",
			Handler:    _SearchCenter_SearchTopic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/search/rpc/search.proto",
}
