// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CommentInfo struct {
	Id              uint64 `json:"id"`
	PostId          uint64 `json:"postId"`
	UserId          uint64 `json:"userId"`
	ParentId        uint64 `json:"parentId"`
	ReplyToUserId   uint64 `json:"replyToUserId"`
	Content         string `json:"content"`
	Level           int32  `json:"level"`
	ReplyCount      int32  `json:"replyCount"`
	LikeCount       int32  `json:"likeCount"`
	CreatedAt       int64  `json:"createdAt"`
	Username        string `json:"username"`
	Avatar          string `json:"avatar"`
	ReplyToUsername string `json:"replyToUsername"`
	IsLiked         bool   `json:"isLiked"`
}

type CommentItem struct {
	Root           CommentInfo   `json:"root"`
	Replies        []CommentInfo `json:"replies"`
	HasMoreReplies bool          `json:"hasMoreReplies"`
}

type CommentListResp struct {
	Code  int           `json:"code"`
	Msg   string        `json:"msg"`
	Total int64         `json:"total"`
	List  []CommentItem `json:"list"`
}

type CreateCommentReq struct {
	PostId        uint64 `json:"postId" validate:"required"`
	ParentId      uint64 `json:"parentId,default=0"`
	ReplyToUserId uint64 `json:"replyToUserId,default=0"`
	Content       string `json:"content" validate:"required,max=2000"`
}

type CreateCommentResp struct {
	Code    int         `json:"code"`
	Msg     string      `json:"msg"`
	Comment CommentInfo `json:"comment"`
}

type DeleteCommentReq struct {
	CommentId uint64 `path:"commentId" validate:"required"`
}

type DeleteCommentResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type GetCommentListReq struct {
	PostId   uint64 `form:"postId" validate:"required"`
	Cursor   int64  `form:"cursor,default=0"`
	PageSize int64  `form:"pageSize,default=20" validate:"min=1,max=50"`
	SortType string `form:"sortType,default=time"` // hot/time
}

type GetReplyListReq struct {
	CommentId uint64 `form:"commentId" validate:"required"`
	Cursor    int64  `form:"cursor,default=0"`
	PageSize  int64  `form:"pageSize,default=20" validate:"min=1,max=50"`
}

type VoteCommentReq struct {
	CommentId uint64 `path:"commentId" validate:"required"`
	VoteType  int32  `json:"voteType" validate:"oneof=0 1 2"` // 0取消,1点赞,2点踩
}

type VoteCommentResp struct {
	Code         int    `json:"code"`
	Msg          string `json:"msg"`
	LikeCount    int32  `json:"likeCount"`
	DislikeCount int32  `json:"dislikeCount"`
	IsLiked      bool   `json:"isLiked"`
	IsDisliked   bool   `json:"isDisliked"`
}
