// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetUserInfoReq struct {
	UserId uint64 `path:"id"`
}

type GetUserInfoResp struct {
	UserInfo UserInfo        `json:"userInfo"`
	Profile  UserProfileInfo `json:"profile,omitempty"`
	Stat     UserStatInfo    `json:"stat,omitempty"`
}

type GetUserStatReq struct {
	UserId uint64 `path:"id"`
}

type GetUserStatResp struct {
	Stat UserStatInfo `json:"stat"`
}

type LoginReq struct {
	Username string `json:"username" validate:"required,min=3,max=20"`
	Password string `json:"password" validate:"required,min=8,max=16"`
}

type LoginResp struct {
	Code            int    `json:"code"`
	Msg             string `json:"msg"`
	UserId          uint64 `json:"userId"`
	AccessToken     string `json:"accessToken"`
	AccessExpireIn  int64  `json:"accessExpireIn"`
	RefreshToken    string `json:"refreshToken"`
	RefreshExpireIn int64  `json:"refreshExpireIn"`
}

type RegisterReq struct {
	Username string `json:"username" validate:"required,min=3,max=20"`
	Password string `json:"password" validate:"required,min=8,max=16"`
}

type RegisterResp struct {
	Code   int    `json:"code"`
	Msg    string `json:"msg"`
	UserId uint64 `json:"userId"`
}

type UpdateUserProfileInfoReq struct {
	UserProfile UserProfileInfo `json:"userProfile" validate:"required"`
}

type UpdateUserProfileInfoResp struct {
	Code        int             `json:"code"`
	Msg         string          `json:"msg"`
	UserProfile UserProfileInfo `json:"userProfile,omitempty"`
}

type UserInfo struct {
	Id        uint64 `json:"id"`
	Username  string `json:"username"`
	Nickname  string `json:"nickname"`
	Phone     string `json:"phone"`
	Email     string `json:"email"`
	Avatar    string `json:"avatar"`
	Status    int    `json:"status"`
	IsAdmin   bool   `json:"isAdmin"`
	CreatedAt int64  `json:"createdAt"`
}

type UserProfileInfo struct {
	UserId    uint64 `json:"userId" validate:"-"`                                        // 不会从请求中读取，由token决定
	Gender    int    `json:"gender" validate:"min=0,max=2"`                              // 0未知,1男,2女
	Birthday  string `json:"birthday,optional" validate:"omitempty,datetime=2006-01-02"` // 格式：YYYY-MM-DD
	Signature string `json:"signature,optional" validate:"max=500"`
	Location  string `json:"location,optional" validate:"max=100"`
	Website   string `json:"website,optional" validate:"max=200,omitempty,url"`
	Company   string `json:"company,optional" validate:"max=100"`
	JobTitle  string `json:"jobTitle,optional" validate:"max=50"`
	Education string `json:"education,optional" validate:"max=50"`
}

type UserStatInfo struct {
	UserId          uint64 `json:"userId"`
	PostCount       uint64 `json:"postCount"`
	CommentCount    uint64 `json:"commentCount"`
	FollowerCount   uint64 `json:"followerCount"`
	FollowingCount  uint64 `json:"followingCount"`
	LikeCount       uint64 `json:"likeCount"`
	CollectionCount uint64 `json:"collectionCount"`
	LastActiveTime  int64  `json:"lastActiveTime"`
}
