// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"SChill/service/relation/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/relation/follow",
				Handler: FollowHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/relation/follow/:targetUserId",
				Handler: UnfollowHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/relation/follow/status",
				Handler: CheckFollowStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/relation/follow/status/batch",
				Handler: BatchCheckFollowStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/relation/follower",
				Handler: GetFollowerListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/relation/following",
				Handler: GetFollowingListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Jwt.AccessSecret),
	)
}
